/* This file was autogenerated from the Unicode mapping 
 * table iso09.uni in the format used by the Linux kbd package */

/*  Unicode mapping table for ISO 8859-9 fonts iso09.* */
/*  [use: unicode_start iso09.f16 iso09] */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0x2302, 
0xffff, 0x00a0, 0xffff, 0x00a1, 0xffff, 0x00a2, 0xffff, 0x00a3, 
0xffff, 0x00a4, 0xffff, 0x00a5, 0xffff, 0x00a6, 0xffff, 0x00a7, 
0xffff, 0x00a8, 0xffff, 0x00a9, 0xffff, 0x00aa, 0xffff, 0x00ab, 
0xffff, 0x00ac, 0xffff, 0x00ad, 0xffff, 0x00ae, 0xffff, 0x00af, 
0xffff, 0x00b0, 0xffff, 0x00b1, 0xffff, 0x00b2, 0xffff, 0x00b3, 
0xffff, 0x00b4, 0xffff, 0x00b5, 0xffff, 0x00b6, 0xffff, 0x00b7, 
0xffff, 0x00b8, 0xffff, 0x00b9, 0xffff, 0x00ba, 0xffff, 0x00bb, 
0xffff, 0x00bc, 0xffff, 0x00bd, 0xffff, 0x00be, 0xffff, 0x00bf, 
0xffff, 0x00c0, 0xffff, 0x00c1, 0xffff, 0x00c2, 0xffff, 0x00c3, 
0xffff, 0x00c4, 0xffff, 0x00c5, 0xffff, 0x00c6, 0xffff, 0x00c7, 
0xffff, 0x00c8, 0xffff, 0x00c9, 0xffff, 0x00ca, 0xffff, 0x00cb, 
0xffff, 0x00cc, 0xffff, 0x00cd, 0xffff, 0x00ce, 0xffff, 0x00cf, 
0xffff, 0x011e, 0xffff, 0x00d1, 0xffff, 0x00d2, 0xffff, 0x00d3, 
0xffff, 0x00d4, 0xffff, 0x00d5, 0xffff, 0x00d6, 0xffff, 0x00d7, 
0xffff, 0x00d8, 0xffff, 0x00d9, 0xffff, 0x00da, 0xffff, 0x00db, 
0xffff, 0x00dc, 0xffff, 0x0130, 0xffff, 0x015e, 0xffff, 0x00df, 
0xffff, 0x00e0, 0xffff, 0x00e1, 0xffff, 0x00e2, 0xffff, 0x00e3, 
0xffff, 0x00e4, 0xffff, 0x00e5, 0xffff, 0x00e6, 0xffff, 0x00e7, 
0xffff, 0x00e8, 0xffff, 0x00e9, 0xffff, 0x00ea, 0xffff, 0x00eb, 
0xffff, 0x00ec, 0xffff, 0x00ed, 0xffff, 0x00ee, 0xffff, 0x00ef, 
0xffff, 0x011f, 0xffff, 0x00f1, 0xffff, 0x00f2, 0xffff, 0x00f3, 
0xffff, 0x00f4, 0xffff, 0x00f5, 0xffff, 0x00f6, 0xffff, 0x00f7, 
0xffff, 0x00f8, 0xffff, 0x00f9, 0xffff, 0x00fa, 0xffff, 0x00fb, 
0xffff, 0x00fc, 0xffff, 0x0131, 0xffff, 0x015f, 0xffff, 0x00ff, 
0xffff, 0xfffd, 0xffff, 0x263a, 0xffff, 0x263b, 0xffff, 0x2665, 
0xffff, 0x2666, 0xffff, 0x2663, 0xffff, 0x2660, 0xffff, 0x2022, 
0xffff, 0x25d8, 0xffff, 0x25cb, 0xffff, 0x25d9, 0xffff, 0x2642, 
0xffff, 0x2640, 0xffff, 0x266a, 0xffff, 0x266b, 0xffff, 0x266c, 
0xffff, 0x263c, 0xffff, 0x25b6, 0xffff, 0x25ba, 0xffff, 0x25c0, 
0xffff, 0x25c4, 0xffff, 0x2195, 0xffff, 0x203c, 0xffff, 0x00b6, 
0xffff, 0x00a7, 0xffff, 0x25ac, 0xffff, 0x21a8, 0xffff, 0x2191, 
0xffff, 0x2193, 0xffff, 0x2192, 0xffff, 0x2190, 0xffff, 0x221f, 
0xffff, 0x2319, 0xffff, 0x2194, 0xffff, 0x25b2, 0xffff, 0x25bc, 
0xffff, };

struct psf_mapping256 m_8859_9 = { "8859-9",
256, {
&values[385], /* 0  */
&values[387], /* 1  */
&values[389], /* 2  */
&values[391], /* 3  */
&values[393], /* 4  */
&values[395], /* 5  */
&values[397], /* 6  */
&values[399], /* 7  */
&values[401], /* 8  */
&values[403], /* 9  */
&values[405], /* 10  */
&values[407], /* 11  */
&values[409], /* 12  */
&values[411], /* 13  */
&values[415], /* 14  */
&values[417], /* 15  */
&values[421], /* 16  */
&values[425], /* 17  */
&values[427], /* 18  */
&values[429], /* 19  */
&values[431], /* 20  */
&values[433], /* 21  */
&values[435], /* 22  */
&values[437], /* 23  */
&values[439], /* 24  */
&values[441], /* 25  */
&values[443], /* 26  */
&values[445], /* 27  */
&values[449], /* 28  */
&values[451], /* 29  */
&values[453], /* 30  */
&values[455], /* 31  */
&values[1], /* 32  */
&values[3], /* 33  */
&values[5], /* 34  */
&values[7], /* 35  */
&values[9], /* 36  */
&values[11], /* 37  */
&values[13], /* 38  */
&values[15], /* 39  */
&values[17], /* 40  */
&values[19], /* 41  */
&values[21], /* 42  */
&values[23], /* 43  */
&values[25], /* 44  */
&values[27], /* 45  */
&values[29], /* 46  */
&values[31], /* 47  */
&values[33], /* 48  */
&values[35], /* 49  */
&values[37], /* 50  */
&values[39], /* 51  */
&values[41], /* 52  */
&values[43], /* 53  */
&values[45], /* 54  */
&values[47], /* 55  */
&values[49], /* 56  */
&values[51], /* 57  */
&values[53], /* 58  */
&values[55], /* 59  */
&values[57], /* 60  */
&values[59], /* 61  */
&values[61], /* 62  */
&values[63], /* 63  */
&values[65], /* 64  */
&values[67], /* 65  */
&values[69], /* 66  */
&values[71], /* 67  */
&values[73], /* 68  */
&values[75], /* 69  */
&values[77], /* 70  */
&values[79], /* 71  */
&values[81], /* 72  */
&values[83], /* 73  */
&values[85], /* 74  */
&values[87], /* 75  */
&values[89], /* 76  */
&values[91], /* 77  */
&values[93], /* 78  */
&values[95], /* 79  */
&values[97], /* 80  */
&values[99], /* 81  */
&values[101], /* 82  */
&values[103], /* 83  */
&values[105], /* 84  */
&values[107], /* 85  */
&values[109], /* 86  */
&values[111], /* 87  */
&values[113], /* 88  */
&values[115], /* 89  */
&values[117], /* 90  */
&values[119], /* 91  */
&values[121], /* 92  */
&values[123], /* 93  */
&values[125], /* 94  */
&values[127], /* 95  */
&values[129], /* 96  */
&values[131], /* 97  */
&values[133], /* 98  */
&values[135], /* 99  */
&values[137], /* 100  */
&values[139], /* 101  */
&values[141], /* 102  */
&values[143], /* 103  */
&values[145], /* 104  */
&values[147], /* 105  */
&values[149], /* 106  */
&values[151], /* 107  */
&values[153], /* 108  */
&values[155], /* 109  */
&values[157], /* 110  */
&values[159], /* 111  */
&values[161], /* 112  */
&values[163], /* 113  */
&values[165], /* 114  */
&values[167], /* 115  */
&values[169], /* 116  */
&values[171], /* 117  */
&values[173], /* 118  */
&values[175], /* 119  */
&values[177], /* 120  */
&values[179], /* 121  */
&values[181], /* 122  */
&values[183], /* 123  */
&values[185], /* 124  */
&values[187], /* 125  */
&values[189], /* 126  */
&values[191], /* 127  */
&values[0], /* 128  */
&values[0], /* 129  */
&values[0], /* 130  */
&values[0], /* 131  */
&values[0], /* 132  */
&values[0], /* 133  */
&values[0], /* 134  */
&values[0], /* 135  */
&values[0], /* 136  */
&values[0], /* 137  */
&values[0], /* 138  */
&values[0], /* 139  */
&values[0], /* 140  */
&values[0], /* 141  */
&values[0], /* 142  */
&values[0], /* 143  */
&values[0], /* 144  */
&values[0], /* 145  */
&values[0], /* 146  */
&values[0], /* 147  */
&values[0], /* 148  */
&values[0], /* 149  */
&values[0], /* 150  */
&values[0], /* 151  */
&values[0], /* 152  */
&values[0], /* 153  */
&values[0], /* 154  */
&values[0], /* 155  */
&values[0], /* 156  */
&values[0], /* 157  */
&values[0], /* 158  */
&values[0], /* 159  */
&values[193], /* 160  */
&values[195], /* 161  */
&values[197], /* 162  */
&values[199], /* 163  */
&values[201], /* 164  */
&values[203], /* 165  */
&values[205], /* 166  */
&values[207], /* 167  */
&values[209], /* 168  */
&values[211], /* 169  */
&values[213], /* 170  */
&values[215], /* 171  */
&values[217], /* 172  */
&values[219], /* 173  */
&values[221], /* 174  */
&values[223], /* 175  */
&values[225], /* 176  */
&values[227], /* 177  */
&values[229], /* 178  */
&values[231], /* 179  */
&values[233], /* 180  */
&values[235], /* 181  */
&values[237], /* 182  */
&values[239], /* 183  */
&values[241], /* 184  */
&values[243], /* 185  */
&values[245], /* 186  */
&values[247], /* 187  */
&values[249], /* 188  */
&values[251], /* 189  */
&values[253], /* 190  */
&values[255], /* 191  */
&values[257], /* 192  */
&values[259], /* 193  */
&values[261], /* 194  */
&values[263], /* 195  */
&values[265], /* 196  */
&values[267], /* 197  */
&values[269], /* 198  */
&values[271], /* 199  */
&values[273], /* 200  */
&values[275], /* 201  */
&values[277], /* 202  */
&values[279], /* 203  */
&values[281], /* 204  */
&values[283], /* 205  */
&values[285], /* 206  */
&values[287], /* 207  */
&values[289], /* 208  */
&values[291], /* 209  */
&values[293], /* 210  */
&values[295], /* 211  */
&values[297], /* 212  */
&values[299], /* 213  */
&values[301], /* 214  */
&values[303], /* 215  */
&values[305], /* 216  */
&values[307], /* 217  */
&values[309], /* 218  */
&values[311], /* 219  */
&values[313], /* 220  */
&values[315], /* 221  */
&values[317], /* 222  */
&values[319], /* 223  */
&values[321], /* 224  */
&values[323], /* 225  */
&values[325], /* 226  */
&values[327], /* 227  */
&values[329], /* 228  */
&values[331], /* 229  */
&values[333], /* 230  */
&values[335], /* 231  */
&values[337], /* 232  */
&values[339], /* 233  */
&values[341], /* 234  */
&values[343], /* 235  */
&values[345], /* 236  */
&values[347], /* 237  */
&values[349], /* 238  */
&values[351], /* 239  */
&values[353], /* 240  */
&values[355], /* 241  */
&values[357], /* 242  */
&values[359], /* 243  */
&values[361], /* 244  */
&values[363], /* 245  */
&values[365], /* 246  */
&values[367], /* 247  */
&values[369], /* 248  */
&values[371], /* 249  */
&values[373], /* 250  */
&values[375], /* 251  */
&values[377], /* 252  */
&values[379], /* 253  */
&values[381], /* 254  */
&values[383], /* 255  */
}};
