/* This file was autogenerated from the Unicode mapping 
 * table amstrad.uni in the format used by the Linux kbd package */

/*  Amstrad PCW <--> Unicode mapping table  */
/*  This uses psftools extensions (U* codes) and so probably won't be  */
/*  acceptable to the utilities in kbd(1) */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0x221e, 0xffff, 0x2299, 0xffff, 0x0393, 0xffff, 0x0394, 
0xffff, 0x2297, 0xffff, 0x00d7, 0xffff, 0x00f7, 0xffff, 0x2234, 
0xffff, 0x220f, 0xffff, 0x2193, 0xffff, 0x2211, 0xffff, 0x2190, 
0xffff, 0x2192, 0xffff, 0x00b1, 0xffff, 0x2194, 0xffff, 0x03a9, 
0xffff, 0x03b1, 0xffff, 0x03b2, 0xffff, 0x03b3, 0xffff, 0x03b4, 
0xffff, 0x03b5, 0xffff, 0x03b8, 0xffff, 0x03bb, 0xffff, 0x03bc, 
0xffff, 0x03c0, 0xffff, 0x03c1, 0xffff, 0x03c3, 0xffff, 0x03c4, 
0xffff, 0x03c6, 0xffff, 0x03c7, 0xffff, 0x03c8, 0xffff, 0x03c9, 
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x2191, 0x1ffff, 0x005e, 
0xffff, 0x005f, 0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 
0xffff, 0x0063, 0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 
0xffff, 0x0067, 0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 
0xffff, 0x006b, 0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 
0xffff, 0x006f, 0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 
0xffff, 0x0073, 0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 
0xffff, 0x0077, 0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 
0xffff, 0x007b, 0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 
0xffff, 0xff10, 0x1ffff, 0x0030, 0xffff, 0x25fc, 0xffff, 0x2567, 
0xffff, 0x255f, 0xffff, 0x255a, 0xffff, 0x2564, 0xffff, 0x2551, 
0xffff, 0x2554, 0xffff, 0x2560, 0xffff, 0x2562, 0xffff, 0x255d, 
0xffff, 0x2550, 0xffff, 0x2569, 0xffff, 0x2557, 0xffff, 0x2563, 
0xffff, 0x2566, 0xffff, 0x256c, 0xffff, 0x25aa, 0xffff, 0x2575, 
0xffff, 0x2576, 0xffff, 0x2570, 0x1ffff, 0x2514, 0xffff, 0x2577, 
0xffff, 0x2502, 0xffff, 0x256d, 0x1ffff, 0x250c, 0xffff, 0x251c, 
0xffff, 0x2574, 0xffff, 0x256f, 0x1ffff, 0x2518, 0xffff, 0x2500, 
0xffff, 0x2534, 0xffff, 0x256e, 0x1ffff, 0x2510, 0xffff, 0x2524, 
0xffff, 0x252c, 0xffff, 0x253c, 0xffff, 0x00aa, 0xffff, 0x00ba, 
0xffff, 0x00b0, 0xffff, 0x00a3, 0xffff, 0x00a9, 0xffff, 0x00b6, 
0xffff, 0x00a7, 0xffff, 0x2020, 0xffff, 0x00bc, 0xffff, 0x00bd, 
0xffff, 0x00be, 0xffff, 0x00ab, 0xffff, 0x00bb, 0xffff, 0x20a7, 
0xffff, 0x00bf, 0xffff, 0x00a1, 0xffff, 0x0192, 0xffff, 0x00a2, 
0xffff, 0x00a8, 0xffff, 0x00b4, 0xffff, 0x005e, 0xffff, 0x2030, 
0xffff, 0x215b, 0xffff, 0x215c, 0xffff, 0x215d, 0xffff, 0x215e, 
0xffff, 0x00df, 0xffff, 0x25cb, 0xffff, 0x25cf, 0x1ffff, 0x2022, 
0xffff, 0x00a5, 0xffff, 0x00ae, 0xffff, 0x2122, 0xffff, 0x00c1, 
0xffff, 0x00c9, 0xffff, 0x00cd, 0xffff, 0x00d3, 0xffff, 0x00da, 
0xffff, 0x00c2, 0xffff, 0x00ca, 0xffff, 0x00ce, 0xffff, 0x00d4, 
0xffff, 0x00db, 0xffff, 0x00c0, 0xffff, 0x00c8, 0xffff, 0x00cc, 
0xffff, 0x00d2, 0xffff, 0x00d9, 0xffff, 0x0178, 0xffff, 0x00c4, 
0xffff, 0x00cb, 0xffff, 0x00cf, 0xffff, 0x00d6, 0xffff, 0x00dc, 
0xffff, 0x00c7, 0xffff, 0x00c6, 0xffff, 0x00c5, 0xffff, 0x00d8, 
0xffff, 0x00d1, 0xffff, 0x00c3, 0xffff, 0x00d5, 0xffff, 0x2265, 
0xffff, 0x2264, 0xffff, 0x2260, 0xffff, 0x2245, 0xffff, 0x00e1, 
0xffff, 0x00e9, 0xffff, 0x00ed, 0xffff, 0x00f3, 0xffff, 0x00fa, 
0xffff, 0x00e2, 0xffff, 0x00ea, 0xffff, 0x00ee, 0xffff, 0x00f4, 
0xffff, 0x00fb, 0xffff, 0x00e0, 0xffff, 0x00e8, 0xffff, 0x00ec, 
0xffff, 0x00f2, 0xffff, 0x00f9, 0xffff, 0x00ff, 0xffff, 0x00e4, 
0xffff, 0x00eb, 0xffff, 0x00ef, 0xffff, 0x00f6, 0xffff, 0x00fc, 
0xffff, 0x00e7, 0xffff, 0x00e6, 0xffff, 0x00e5, 0xffff, 0x00f8, 
0xffff, 0x00f1, 0xffff, 0x00e3, 0xffff, 0x00f5, 0xffff, 0x21d2, 
0xffff, 0x21d0, 0xffff, 0x21d4, 0xffff, 0x2261, 0xffff, };

struct psf_mapping256 m_AMSTRAD = { "AMSTRAD",
256, {
&values[1], /* 0  Infinity  */
&values[3], /* 1  Arrow emerging */
&values[5], /* 2  Big gamma */
&values[7], /* 3  Big delta */
&values[9], /* 4  Arrow receding */
&values[11], /* 5  Multiply */
&values[13], /* 6  Divide */
&values[15], /* 7  Therefore */
&values[17], /* 8  Big pi */
&values[19], /* 9  Down arrow */
&values[21], /* 10  Big sigma */
&values[23], /* 11  Left arrow */
&values[25], /* 12  Right arrow */
&values[27], /* 13  +/- */
&values[29], /* 14  Left/right arrow */
&values[31], /* 15  Big omega */
&values[33], /* 16  Alpha */
&values[35], /* 17  Beta */
&values[37], /* 18  Gamma */
&values[39], /* 19  Delta */
&values[41], /* 20  Epsilon */
&values[43], /* 21  Theta */
&values[45], /* 22  Lambda */
&values[47], /* 23  Mu */
&values[49], /* 24  pi */
&values[51], /* 25  rho */
&values[53], /* 26  sigma */
&values[55], /* 27  tau */
&values[57], /* 28  phi */
&values[59], /* 29  chi */
&values[61], /* 30  psi */
&values[63], /* 31  omega */
&values[65], /* 32  */
&values[67], /* 33  */
&values[69], /* 34  */
&values[71], /* 35  */
&values[73], /* 36  */
&values[75], /* 37  */
&values[77], /* 38  */
&values[79], /* 39  */
&values[81], /* 40  */
&values[83], /* 41  */
&values[85], /* 42  */
&values[87], /* 43  */
&values[89], /* 44  */
&values[91], /* 45  */
&values[93], /* 46  */
&values[95], /* 47  */
&values[97], /* 48  */
&values[99], /* 49  */
&values[101], /* 50  */
&values[103], /* 51  */
&values[105], /* 52  */
&values[107], /* 53  */
&values[109], /* 54  */
&values[111], /* 55  */
&values[113], /* 56  */
&values[115], /* 57  */
&values[117], /* 58  */
&values[119], /* 59  */
&values[121], /* 60  */
&values[123], /* 61  */
&values[125], /* 62  */
&values[127], /* 63  */
&values[129], /* 64  */
&values[131], /* 65  */
&values[133], /* 66  */
&values[135], /* 67  */
&values[137], /* 68  */
&values[139], /* 69  */
&values[141], /* 70  */
&values[143], /* 71  */
&values[145], /* 72  */
&values[147], /* 73  */
&values[149], /* 74  */
&values[151], /* 75  */
&values[153], /* 76  */
&values[155], /* 77  */
&values[157], /* 78  */
&values[159], /* 79  */
&values[161], /* 80  */
&values[163], /* 81  */
&values[165], /* 82  */
&values[167], /* 83  */
&values[169], /* 84  */
&values[171], /* 85  */
&values[173], /* 86  */
&values[175], /* 87  */
&values[177], /* 88  */
&values[179], /* 89  */
&values[181], /* 90  */
&values[183], /* 91  */
&values[185], /* 92  */
&values[187], /* 93  */
&values[189], /* 94  */
&values[193], /* 95  */
&values[195], /* 96  */
&values[197], /* 97  */
&values[199], /* 98  */
&values[201], /* 99  */
&values[203], /* 100  */
&values[205], /* 101  */
&values[207], /* 102  */
&values[209], /* 103  */
&values[211], /* 104  */
&values[213], /* 105  */
&values[215], /* 106  */
&values[217], /* 107  */
&values[219], /* 108  */
&values[221], /* 109  */
&values[223], /* 110  */
&values[225], /* 111  */
&values[227], /* 112  */
&values[229], /* 113  */
&values[231], /* 114  */
&values[233], /* 115  */
&values[235], /* 116  */
&values[237], /* 117  */
&values[239], /* 118  */
&values[241], /* 119  */
&values[243], /* 120  */
&values[245], /* 121  */
&values[247], /* 122  */
&values[249], /* 123  */
&values[251], /* 124  */
&values[253], /* 125  */
&values[255], /* 126  */
&values[257], /* 127  Slashless zero. Map to 'Full width 0', but if that */
&values[261], /* 128  Square dot */
&values[263], /* 129  Junction */
&values[265], /* 130  Junction */
&values[267], /* 131  Bottom left corner */
&values[269], /* 132  Junction */
&values[271], /* 133  Vertical */
&values[273], /* 134  Top left corner */
&values[275], /* 135  Left junction */
&values[277], /* 136  Junction */
&values[279], /* 137  Bottom right corner */
&values[281], /* 138  Horizontal */
&values[283], /* 139  Bottom junction */
&values[285], /* 140  Top right corner */
&values[287], /* 141  Right junction */
&values[289], /* 142  Top junction */
&values[291], /* 143  Crossroads */
&values[293], /* 144  Small dot  */
&values[295], /* 145  Top line segment */
&values[297], /* 146  Right line segment */
&values[299], /* 147  Bottom left corner */
&values[303], /* 148  Bottom line segment */
&values[305], /* 149  Vertical line */
&values[307], /* 150  Top left corner */
&values[311], /* 151  Left junction */
&values[313], /* 152  Left line segment */
&values[315], /* 153  Bottom right corner */
&values[319], /* 154  Horizontal */
&values[321], /* 155  Bottom junction */
&values[323], /* 156  Top right corner */
&values[327], /* 157  Right junction */
&values[329], /* 158  Top junction */
&values[331], /* 159  Crossroads */
&values[333], /* 160  Feminine ordinal */
&values[335], /* 161  Masculine ordinal */
&values[337], /* 162  Degree */
&values[339], /* 163  Pound */
&values[341], /* 164  Copyright */
&values[343], /* 165  Pilcrow */
&values[345], /* 166  Section */
&values[347], /* 167  Dagger */
&values[349], /* 168  Quarter */
&values[351], /* 169  Half */
&values[353], /* 170  Threequarter */
&values[355], /* 171  Open quote */
&values[357], /* 172  Close quote */
&values[359], /* 173  Pesata */
&values[361], /* 174  Upside down question mark */
&values[363], /* 175  Upside down pling */
&values[365], /* 176  Florin */
&values[367], /* 177  Cent */
&values[369], /* 178  Umlaut */
&values[371], /* 179  Acute */
&values[373], /* 180  Circumflex */
&values[375], /* 181  Per mille */
&values[377], /* 182  1/8 */
&values[379], /* 183  3/8 */
&values[381], /* 184  5/8 */
&values[383], /* 185  7/8 */
&values[385], /* 186  Sharp S */
&values[387], /* 187  Hollow bullet */
&values[389], /* 188  Solid bullet */
&values[393], /* 189  Yen */
&values[395], /* 190  Registered */
&values[397], /* 191  Trademark */
&values[399], /* 192  Uppercase accented letters */
&values[401], /* 193  */
&values[403], /* 194  */
&values[405], /* 195  */
&values[407], /* 196  */
&values[409], /* 197  */
&values[411], /* 198  */
&values[413], /* 199  */
&values[415], /* 200  */
&values[417], /* 201  */
&values[419], /* 202  */
&values[421], /* 203  */
&values[423], /* 204  */
&values[425], /* 205  */
&values[427], /* 206  */
&values[429], /* 207  */
&values[431], /* 208  */
&values[433], /* 209  */
&values[435], /* 210  */
&values[437], /* 211  */
&values[439], /* 212  */
&values[441], /* 213  */
&values[443], /* 214  */
&values[445], /* 215  */
&values[447], /* 216  */
&values[449], /* 217  */
&values[451], /* 218  */
&values[453], /* 219  */
&values[455], /* 220  Greater than or equal to */
&values[457], /* 221  Less than or equal to */
&values[459], /* 222  Not equal to */
&values[461], /* 223  Approximately equal to */
&values[463], /* 224  Lowecase accented letters */
&values[465], /* 225  */
&values[467], /* 226  */
&values[469], /* 227  */
&values[471], /* 228  */
&values[473], /* 229  */
&values[475], /* 230  */
&values[477], /* 231  */
&values[479], /* 232  */
&values[481], /* 233  */
&values[483], /* 234  */
&values[485], /* 235  */
&values[487], /* 236  */
&values[489], /* 237  */
&values[491], /* 238  */
&values[493], /* 239  */
&values[495], /* 240  */
&values[497], /* 241  */
&values[499], /* 242  */
&values[501], /* 243  */
&values[503], /* 244  */
&values[505], /* 245  */
&values[507], /* 246  */
&values[509], /* 247  */
&values[511], /* 248  */
&values[513], /* 249  */
&values[515], /* 250  */
&values[517], /* 251  */
&values[519], /* 252  Double shafted arrow pointing right */
&values[521], /* 253  Double shafted arrow pointing left */
&values[523], /* 254  Double shafted arrow pointing both ways */
&values[525], /* 255  Identical to */
}};
