/* This file was autogenerated from the Unicode mapping 
 * table bbcmicro.uni in the format used by the Linux kbd package */

/*  Unicode table for the BBC Micro.  */
/*  [26-1-2008] Added characters 128-255 */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x2032, 
0x1ffff, 0x0027, 0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 
0xffff, 0x002b, 0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 
0xffff, 0x002f, 0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 
0xffff, 0x0033, 0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 
0xffff, 0x0037, 0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 
0xffff, 0x003b, 0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 
0xffff, 0x003f, 0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 
0xffff, 0x0043, 0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 
0xffff, 0x0047, 0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 
0xffff, 0x004b, 0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 
0xffff, 0x004f, 0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 
0xffff, 0x0053, 0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 
0xffff, 0x0057, 0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 
0xffff, 0x005b, 0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 
0xffff, 0x005f, 0xffff, 0x00a3, 0xffff, 0x0061, 0xffff, 0x0062, 
0xffff, 0x0063, 0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 
0xffff, 0x0067, 0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 
0xffff, 0x006b, 0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 
0xffff, 0x006f, 0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 
0xffff, 0x0073, 0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 
0xffff, 0x0077, 0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 
0xffff, 0x007b, 0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 
0xffff, 0x25a0, 0x1ffff, 0x2588, 0xffff, 0x00c4, 0xffff, 0x00c2, 
0xffff, 0x00c6, 0xffff, 0x00c7, 0xffff, 0x00c9, 0xffff, 0x00d6, 
0xffff, 0x00dc, 0xffff, 0x00a9, 0xffff, 0x2190, 0xffff, 0x2192, 
0xffff, 0x2193, 0xffff, 0x2191, 0xffff, 0x00e0, 0xffff, 0x00e8, 
0xffff, 0x00eb, 0xffff, 0x00ea, 0xffff, 0x00e4, 0xffff, 0x00e2, 
0xffff, 0x00e6, 0xffff, 0x00e7, 0xffff, 0x00e9, 0xffff, 0x00f6, 
0xffff, 0x00fc, 0xffff, 0x00ec, 0xffff, 0x00ee, 0xffff, 0x00f2, 
0xffff, 0x00f4, 0xffff, 0x00f9, 0xffff, 0x00fb, 0xffff, 0x00ff, 
0xffff, 0x00a4, 0xffff, 0x00a7, 0xffff, 0x00b0, 0xffff, 0x2577, 
0xffff, 0x2576, 0xffff, 0x250c, 0xffff, 0x2574, 0xffff, 0x2510, 
0xffff, 0x2500, 0xffff, 0x252c, 0xffff, 0x2575, 0xffff, 0x2502, 
0xffff, 0x2514, 0xffff, 0x251c, 0xffff, 0x2518, 0xffff, 0x2524, 
0xffff, 0x2534, 0xffff, 0x253c, 0xffff, 0x256d, 0xffff, 0x256e, 
0xffff, 0x2570, 0xffff, 0x256f, 0xffff, 0x00bf, 0xffff, 0x00a1, 
0xffff, 0x00d1, 0xffff, 0x00f1, 0xffff, 0x2020, 0xffff, 0x2021, 
0xffff, 0x0027, 0xffff, 0x0060, 0xffff, 0x00b6, 0xffff, 0x00b7, 
0xffff, 0x221a, 0xffff, 0x2592, 0xffff, 0x00d8, 0xffff, 0x0391, 
0xffff, 0x0392, 0xffff, 0x0393, 0xffff, 0x0394, 0xffff, 0x0395, 
0xffff, 0x0396, 0xffff, 0x0397, 0xffff, 0x0398, 0xffff, 0x0399, 
0xffff, 0x039a, 0xffff, 0x039b, 0xffff, 0x039c, 0xffff, 0x039d, 
0xffff, 0x039e, 0xffff, 0x039f, 0xffff, 0x03a0, 0xffff, 0x03a1, 
0xffff, 0x03a3, 0xffff, 0x03a4, 0xffff, 0x03a5, 0xffff, 0x03a6, 
0xffff, 0x03a7, 0xffff, 0x03a8, 0xffff, 0x03a9, 0xffff, 0x2207, 
0xffff, 0x00b1, 0xffff, 0x2213, 0xffff, 0x2223, 0x1ffff, 0x007c, 
0x01c0, 0xffff, 0x2225, 0x1ffff, 0x2016, 0x01c1, 0xffff, 0x222a, 
0x1ffff, 0x22c3, 0xffff, 0x2229, 0x1ffff, 0x22c2, 0xffff, 0x00f8, 
0xffff, 0x03b1, 0xffff, 0x03b2, 0xffff, 0x03b3, 0xffff, 0x03b4, 
0xffff, 0x03b5, 0xffff, 0x03b6, 0xffff, 0x03b7, 0xffff, 0x03b8, 
0xffff, 0x03b9, 0xffff, 0x03ba, 0xffff, 0x03bb, 0xffff, 0x03bc, 
0xffff, 0x03bd, 0xffff, 0x03be, 0xffff, 0x03bf, 0xffff, 0x03c0, 
0xffff, 0x03c1, 0xffff, 0x03c3, 0xffff, 0x03c4, 0xffff, 0x03c5, 
0xffff, 0x03c6, 0xffff, 0x03c7, 0xffff, 0x03c8, 0xffff, 0x03c9, 
0xffff, 0x2202, 0xffff, 0x2243, 0x1ffff, 0x2245, 0xffff, 0x2261, 
0xffff, 0x2264, 0xffff, 0x2260, 0xffff, 0x2265, 0xffff, 0x2588, 
0x1ffff, 0x25a0, 0xffff, };

struct psf_mapping256 m_BBCMICRO = { "BBCMICRO",
256, {
&values[0], /* 0  */
&values[0], /* 1  */
&values[0], /* 2  */
&values[0], /* 3  */
&values[0], /* 4  */
&values[0], /* 5  */
&values[0], /* 6  */
&values[0], /* 7  */
&values[0], /* 8  */
&values[0], /* 9  */
&values[0], /* 10  */
&values[0], /* 11  */
&values[0], /* 12  */
&values[0], /* 13  */
&values[0], /* 14  */
&values[0], /* 15  */
&values[0], /* 16  */
&values[0], /* 17  */
&values[0], /* 18  */
&values[0], /* 19  */
&values[0], /* 20  */
&values[0], /* 21  */
&values[0], /* 22  */
&values[0], /* 23  */
&values[0], /* 24  */
&values[0], /* 25  */
&values[0], /* 26  */
&values[0], /* 27  */
&values[0], /* 28  */
&values[0], /* 29  */
&values[0], /* 30  */
&values[0], /* 31  */
&values[1], /* 32  */
&values[3], /* 33  */
&values[5], /* 34  */
&values[7], /* 35  */
&values[9], /* 36  */
&values[11], /* 37  */
&values[13], /* 38  */
&values[15], /* 39  Prime */
&values[19], /* 40  */
&values[21], /* 41  */
&values[23], /* 42  */
&values[25], /* 43  */
&values[27], /* 44  */
&values[29], /* 45  */
&values[31], /* 46  */
&values[33], /* 47  */
&values[35], /* 48  */
&values[37], /* 49  */
&values[39], /* 50  */
&values[41], /* 51  */
&values[43], /* 52  */
&values[45], /* 53  */
&values[47], /* 54  */
&values[49], /* 55  */
&values[51], /* 56  */
&values[53], /* 57  */
&values[55], /* 58  */
&values[57], /* 59  */
&values[59], /* 60  */
&values[61], /* 61  */
&values[63], /* 62  */
&values[65], /* 63  */
&values[67], /* 64  */
&values[69], /* 65  */
&values[71], /* 66  */
&values[73], /* 67  */
&values[75], /* 68  */
&values[77], /* 69  */
&values[79], /* 70  */
&values[81], /* 71  */
&values[83], /* 72  */
&values[85], /* 73  */
&values[87], /* 74  */
&values[89], /* 75  */
&values[91], /* 76  */
&values[93], /* 77  */
&values[95], /* 78  */
&values[97], /* 79  */
&values[99], /* 80  */
&values[101], /* 81  */
&values[103], /* 82  */
&values[105], /* 83  */
&values[107], /* 84  */
&values[109], /* 85  */
&values[111], /* 86  */
&values[113], /* 87  */
&values[115], /* 88  */
&values[117], /* 89  */
&values[119], /* 90  */
&values[121], /* 91  */
&values[123], /* 92  */
&values[125], /* 93  */
&values[127], /* 94  */
&values[129], /* 95  */
&values[131], /* 96  Pound sign */
&values[133], /* 97  */
&values[135], /* 98  */
&values[137], /* 99  */
&values[139], /* 100  */
&values[141], /* 101  */
&values[143], /* 102  */
&values[145], /* 103  */
&values[147], /* 104  */
&values[149], /* 105  */
&values[151], /* 106  */
&values[153], /* 107  */
&values[155], /* 108  */
&values[157], /* 109  */
&values[159], /* 110  */
&values[161], /* 111  */
&values[163], /* 112  */
&values[165], /* 113  */
&values[167], /* 114  */
&values[169], /* 115  */
&values[171], /* 116  */
&values[173], /* 117  */
&values[175], /* 118  */
&values[177], /* 119  */
&values[179], /* 120  */
&values[181], /* 121  */
&values[183], /* 122  */
&values[185], /* 123  */
&values[187], /* 124  */
&values[189], /* 125  */
&values[191], /* 126  */
&values[193], /* 127  Black block */
&values[197], /* 128  */
&values[199], /* 129  */
&values[201], /* 130  */
&values[203], /* 131  */
&values[205], /* 132  */
&values[207], /* 133  */
&values[209], /* 134  */
&values[211], /* 135  Copyright */
&values[213], /* 136  Left arrow */
&values[215], /* 137  Right arrow */
&values[217], /* 138  Down arrow */
&values[219], /* 139  Up arrow */
&values[221], /* 140  */
&values[223], /* 141  */
&values[225], /* 142  */
&values[227], /* 143  */
&values[229], /* 144  */
&values[231], /* 145  */
&values[233], /* 146  */
&values[235], /* 147  */
&values[237], /* 148  */
&values[239], /* 149  */
&values[241], /* 150  */
&values[243], /* 151  */
&values[245], /* 152  */
&values[247], /* 153  */
&values[249], /* 154  */
&values[251], /* 155  */
&values[253], /* 156  */
&values[255], /* 157  */
&values[257], /* 158  */
&values[259], /* 159  */
&values[261], /* 160  */
&values[263], /* 161  Bottom line segment */
&values[265], /* 162  Right line segment */
&values[267], /* 163  Top left corner */
&values[269], /* 164  Left line segment */
&values[271], /* 165  Top right corner */
&values[273], /* 166  Horizontal line */
&values[275], /* 167  Top junction */
&values[277], /* 168  Top line segment */
&values[279], /* 169  Vertical line */
&values[281], /* 170  Bottom left corner */
&values[283], /* 171  Left junction */
&values[285], /* 172  Bottom right corner */
&values[287], /* 173  Right junction */
&values[289], /* 174  Bottom junction */
&values[291], /* 175  Crossroads */
&values[293], /* 176  Top left corner, rounded */
&values[295], /* 177  Top right corner, rounded */
&values[297], /* 178  Bottom left corner, rounded */
&values[299], /* 179  Bottom right corner, rounded */
&values[301], /* 180  Upside-down question mark */
&values[303], /* 181  Upside-down pling */
&values[305], /* 182  */
&values[307], /* 183  */
&values[309], /* 184  Dagger */
&values[311], /* 185  Double-dagger */
&values[313], /* 186  Apostrophe */
&values[315], /* 187  Backtick */
&values[317], /* 188  Pilcrow */
&values[319], /* 189  Middle dot */
&values[321], /* 190  Square root */
&values[323], /* 191  Medium shade */
&values[325], /* 192  */
&values[327], /* 193  Alpha */
&values[329], /* 194  */
&values[331], /* 195  */
&values[333], /* 196  */
&values[335], /* 197  */
&values[337], /* 198  */
&values[339], /* 199  */
&values[341], /* 200  */
&values[343], /* 201  */
&values[345], /* 202  */
&values[347], /* 203  */
&values[349], /* 204  */
&values[351], /* 205  */
&values[353], /* 206  */
&values[355], /* 207  */
&values[357], /* 208  */
&values[359], /* 209  */
&values[361], /* 210  */
&values[363], /* 211  */
&values[365], /* 212  */
&values[367], /* 213  */
&values[369], /* 214  */
&values[371], /* 215  */
&values[373], /* 216  */
&values[375], /* 217  Nabla */
&values[377], /* 218  Plus or minus */
&values[379], /* 219  Minus or plus */
&values[381], /* 220  Divides */
&values[386], /* 221  Parallel to */
&values[391], /* 222  Union */
&values[395], /* 223  Intersection */
&values[399], /* 224  */
&values[401], /* 225  Alpha */
&values[403], /* 226  */
&values[405], /* 227  */
&values[407], /* 228  */
&values[409], /* 229  */
&values[411], /* 230  */
&values[413], /* 231  */
&values[415], /* 232  */
&values[417], /* 233  */
&values[419], /* 234  */
&values[421], /* 235  */
&values[423], /* 236  */
&values[425], /* 237  */
&values[427], /* 238  */
&values[429], /* 239  */
&values[431], /* 240  */
&values[433], /* 241  */
&values[435], /* 242  */
&values[437], /* 243  */
&values[439], /* 244  */
&values[441], /* 245  */
&values[443], /* 246  */
&values[445], /* 247  */
&values[447], /* 248  */
&values[449], /* 249  Partial differential */
&values[451], /* 250  Asymptotically equal to */
&values[455], /* 251  Identical to */
&values[457], /* 252  Less than or equal to */
&values[459], /* 253  Not euqal to */
&values[461], /* 254  Greater than or equal to */
&values[463], /* 255  Solid block */
}};
