/* This file was autogenerated from the file 
 * CP1255.TXT from UNICODE.ORG */

/*     Name:     cp1255 to Unicode table */
/*     Unicode version: 2.0 */
/*     Table version: 2.01 */
/*     Table format:  Format A */
/*     Date:          1/7/2000 */
/*     Contact:       cpxlate@microsoft.com */
/*     General notes: none */
/*     Format: Three tab-separated columns */
/*         Column #1 is the cp1255 code (in hex) */
/*         Column #2 is the Unicode (in hex as 0xXXXX) */
/*         Column #3 is the Unicode name (follows a comment sign, '#') */
/*     The entries are in cp1255 order */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0xffff, 
0x20ac, 0xffff, 0xffff, 0x201a, 0xffff, 0x0192, 0xffff, 0x201e, 
0xffff, 0x2026, 0xffff, 0x2020, 0xffff, 0x2021, 0xffff, 0x02c6, 
0xffff, 0x2030, 0xffff, 0xffff, 0x2039, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0x2018, 0xffff, 0x2019, 0xffff, 0x201c, 
0xffff, 0x201d, 0xffff, 0x2022, 0xffff, 0x2013, 0xffff, 0x2014, 
0xffff, 0x02dc, 0xffff, 0x2122, 0xffff, 0xffff, 0x203a, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0x00a0, 0xffff, 0x00a1, 0xffff, 
0x00a2, 0xffff, 0x00a3, 0xffff, 0x20aa, 0xffff, 0x00a5, 0xffff, 
0x00a6, 0xffff, 0x00a7, 0xffff, 0x00a8, 0xffff, 0x00a9, 0xffff, 
0x00d7, 0xffff, 0x00ab, 0xffff, 0x00ac, 0xffff, 0x00ad, 0xffff, 
0x00ae, 0xffff, 0x00af, 0xffff, 0x00b0, 0xffff, 0x00b1, 0xffff, 
0x00b2, 0xffff, 0x00b3, 0xffff, 0x00b4, 0xffff, 0x00b5, 0xffff, 
0x00b6, 0xffff, 0x00b7, 0xffff, 0x00b8, 0xffff, 0x00b9, 0xffff, 
0x00f7, 0xffff, 0x00bb, 0xffff, 0x00bc, 0xffff, 0x00bd, 0xffff, 
0x00be, 0xffff, 0x00bf, 0xffff, 0x05b0, 0xffff, 0x05b1, 0xffff, 
0x05b2, 0xffff, 0x05b3, 0xffff, 0x05b4, 0xffff, 0x05b5, 0xffff, 
0x05b6, 0xffff, 0x05b7, 0xffff, 0x05b8, 0xffff, 0x05b9, 0xffff, 
0xffff, 0x05bb, 0xffff, 0x05bc, 0xffff, 0x05bd, 0xffff, 0x05be, 
0xffff, 0x05bf, 0xffff, 0x05c0, 0xffff, 0x05c1, 0xffff, 0x05c2, 
0xffff, 0x05c3, 0xffff, 0x05f0, 0xffff, 0x05f1, 0xffff, 0x05f2, 
0xffff, 0x05f3, 0xffff, 0x05f4, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0x05d0, 0xffff, 0x05d1, 0xffff, 
0x05d2, 0xffff, 0x05d3, 0xffff, 0x05d4, 0xffff, 0x05d5, 0xffff, 
0x05d6, 0xffff, 0x05d7, 0xffff, 0x05d8, 0xffff, 0x05d9, 0xffff, 
0x05da, 0xffff, 0x05db, 0xffff, 0x05dc, 0xffff, 0x05dd, 0xffff, 
0x05de, 0xffff, 0x05df, 0xffff, 0x05e0, 0xffff, 0x05e1, 0xffff, 
0x05e2, 0xffff, 0x05e3, 0xffff, 0x05e4, 0xffff, 0x05e5, 0xffff, 
0x05e6, 0xffff, 0x05e7, 0xffff, 0x05e8, 0xffff, 0x05e9, 0xffff, 
0x05ea, 0xffff, 0xffff, 0xffff, 0x200e, 0xffff, 0x200f, 0xffff, 
0xffff, };

struct psf_mapping256 m_CP1255 = { "CP1255", 
256, {
&values[1], /* 0 NULL */
&values[2], /* 1 START OF HEADING */
&values[3], /* 2 START OF TEXT */
&values[4], /* 3 END OF TEXT */
&values[5], /* 4 END OF TRANSMISSION */
&values[6], /* 5 ENQUIRY */
&values[7], /* 6 ACKNOWLEDGE */
&values[8], /* 7 BELL */
&values[9], /* 8 BACKSPACE */
&values[10], /* 9 HORIZONTAL TABULATION */
&values[11], /* 10 LINE FEED */
&values[12], /* 11 VERTICAL TABULATION */
&values[13], /* 12 FORM FEED */
&values[14], /* 13 CARRIAGE RETURN */
&values[15], /* 14 SHIFT OUT */
&values[16], /* 15 SHIFT IN */
&values[17], /* 16 DATA LINK ESCAPE */
&values[18], /* 17 DEVICE CONTROL ONE */
&values[19], /* 18 DEVICE CONTROL TWO */
&values[20], /* 19 DEVICE CONTROL THREE */
&values[21], /* 20 DEVICE CONTROL FOUR */
&values[22], /* 21 NEGATIVE ACKNOWLEDGE */
&values[23], /* 22 SYNCHRONOUS IDLE */
&values[24], /* 23 END OF TRANSMISSION BLOCK */
&values[25], /* 24 CANCEL */
&values[26], /* 25 END OF MEDIUM */
&values[27], /* 26 SUBSTITUTE */
&values[28], /* 27 ESCAPE */
&values[29], /* 28 FILE SEPARATOR */
&values[30], /* 29 GROUP SEPARATOR */
&values[31], /* 30 RECORD SEPARATOR */
&values[32], /* 31 UNIT SEPARATOR */
&values[33], /* 32 SPACE */
&values[35], /* 33 EXCLAMATION MARK */
&values[37], /* 34 QUOTATION MARK */
&values[39], /* 35 NUMBER SIGN */
&values[41], /* 36 DOLLAR SIGN */
&values[43], /* 37 PERCENT SIGN */
&values[45], /* 38 AMPERSAND */
&values[47], /* 39 APOSTROPHE */
&values[49], /* 40 LEFT PARENTHESIS */
&values[51], /* 41 RIGHT PARENTHESIS */
&values[53], /* 42 ASTERISK */
&values[55], /* 43 PLUS SIGN */
&values[57], /* 44 COMMA */
&values[59], /* 45 HYPHEN-MINUS */
&values[61], /* 46 FULL STOP */
&values[63], /* 47 SOLIDUS */
&values[65], /* 48 DIGIT ZERO */
&values[67], /* 49 DIGIT ONE */
&values[69], /* 50 DIGIT TWO */
&values[71], /* 51 DIGIT THREE */
&values[73], /* 52 DIGIT FOUR */
&values[75], /* 53 DIGIT FIVE */
&values[77], /* 54 DIGIT SIX */
&values[79], /* 55 DIGIT SEVEN */
&values[81], /* 56 DIGIT EIGHT */
&values[83], /* 57 DIGIT NINE */
&values[85], /* 58 COLON */
&values[87], /* 59 SEMICOLON */
&values[89], /* 60 LESS-THAN SIGN */
&values[91], /* 61 EQUALS SIGN */
&values[93], /* 62 GREATER-THAN SIGN */
&values[95], /* 63 QUESTION MARK */
&values[97], /* 64 COMMERCIAL AT */
&values[99], /* 65 LATIN CAPITAL LETTER A */
&values[101], /* 66 LATIN CAPITAL LETTER B */
&values[103], /* 67 LATIN CAPITAL LETTER C */
&values[105], /* 68 LATIN CAPITAL LETTER D */
&values[107], /* 69 LATIN CAPITAL LETTER E */
&values[109], /* 70 LATIN CAPITAL LETTER F */
&values[111], /* 71 LATIN CAPITAL LETTER G */
&values[113], /* 72 LATIN CAPITAL LETTER H */
&values[115], /* 73 LATIN CAPITAL LETTER I */
&values[117], /* 74 LATIN CAPITAL LETTER J */
&values[119], /* 75 LATIN CAPITAL LETTER K */
&values[121], /* 76 LATIN CAPITAL LETTER L */
&values[123], /* 77 LATIN CAPITAL LETTER M */
&values[125], /* 78 LATIN CAPITAL LETTER N */
&values[127], /* 79 LATIN CAPITAL LETTER O */
&values[129], /* 80 LATIN CAPITAL LETTER P */
&values[131], /* 81 LATIN CAPITAL LETTER Q */
&values[133], /* 82 LATIN CAPITAL LETTER R */
&values[135], /* 83 LATIN CAPITAL LETTER S */
&values[137], /* 84 LATIN CAPITAL LETTER T */
&values[139], /* 85 LATIN CAPITAL LETTER U */
&values[141], /* 86 LATIN CAPITAL LETTER V */
&values[143], /* 87 LATIN CAPITAL LETTER W */
&values[145], /* 88 LATIN CAPITAL LETTER X */
&values[147], /* 89 LATIN CAPITAL LETTER Y */
&values[149], /* 90 LATIN CAPITAL LETTER Z */
&values[151], /* 91 LEFT SQUARE BRACKET */
&values[153], /* 92 REVERSE SOLIDUS */
&values[155], /* 93 RIGHT SQUARE BRACKET */
&values[157], /* 94 CIRCUMFLEX ACCENT */
&values[159], /* 95 LOW LINE */
&values[161], /* 96 GRAVE ACCENT */
&values[163], /* 97 LATIN SMALL LETTER A */
&values[165], /* 98 LATIN SMALL LETTER B */
&values[167], /* 99 LATIN SMALL LETTER C */
&values[169], /* 100 LATIN SMALL LETTER D */
&values[171], /* 101 LATIN SMALL LETTER E */
&values[173], /* 102 LATIN SMALL LETTER F */
&values[175], /* 103 LATIN SMALL LETTER G */
&values[177], /* 104 LATIN SMALL LETTER H */
&values[179], /* 105 LATIN SMALL LETTER I */
&values[181], /* 106 LATIN SMALL LETTER J */
&values[183], /* 107 LATIN SMALL LETTER K */
&values[185], /* 108 LATIN SMALL LETTER L */
&values[187], /* 109 LATIN SMALL LETTER M */
&values[189], /* 110 LATIN SMALL LETTER N */
&values[191], /* 111 LATIN SMALL LETTER O */
&values[193], /* 112 LATIN SMALL LETTER P */
&values[195], /* 113 LATIN SMALL LETTER Q */
&values[197], /* 114 LATIN SMALL LETTER R */
&values[199], /* 115 LATIN SMALL LETTER S */
&values[201], /* 116 LATIN SMALL LETTER T */
&values[203], /* 117 LATIN SMALL LETTER U */
&values[205], /* 118 LATIN SMALL LETTER V */
&values[207], /* 119 LATIN SMALL LETTER W */
&values[209], /* 120 LATIN SMALL LETTER X */
&values[211], /* 121 LATIN SMALL LETTER Y */
&values[213], /* 122 LATIN SMALL LETTER Z */
&values[215], /* 123 LEFT CURLY BRACKET */
&values[217], /* 124 VERTICAL LINE */
&values[219], /* 125 RIGHT CURLY BRACKET */
&values[221], /* 126 TILDE */
&values[223], /* 127 DELETE */
&values[224], /* 128 EURO SIGN */
&values[226], /* 129 UNDEFINED */
&values[227], /* 130 SINGLE LOW-9 QUOTATION MARK */
&values[229], /* 131 LATIN SMALL LETTER F WITH HOOK */
&values[231], /* 132 DOUBLE LOW-9 QUOTATION MARK */
&values[233], /* 133 HORIZONTAL ELLIPSIS */
&values[235], /* 134 DAGGER */
&values[237], /* 135 DOUBLE DAGGER */
&values[239], /* 136 MODIFIER LETTER CIRCUMFLEX ACCENT */
&values[241], /* 137 PER MILLE SIGN */
&values[243], /* 138 UNDEFINED */
&values[244], /* 139 SINGLE LEFT-POINTING ANGLE QUOTATION MARK */
&values[246], /* 140 UNDEFINED */
&values[247], /* 141 UNDEFINED */
&values[248], /* 142 UNDEFINED */
&values[249], /* 143 UNDEFINED */
&values[250], /* 144 UNDEFINED */
&values[251], /* 145 LEFT SINGLE QUOTATION MARK */
&values[253], /* 146 RIGHT SINGLE QUOTATION MARK */
&values[255], /* 147 LEFT DOUBLE QUOTATION MARK */
&values[257], /* 148 RIGHT DOUBLE QUOTATION MARK */
&values[259], /* 149 BULLET */
&values[261], /* 150 EN DASH */
&values[263], /* 151 EM DASH */
&values[265], /* 152 SMALL TILDE */
&values[267], /* 153 TRADE MARK SIGN */
&values[269], /* 154 UNDEFINED */
&values[270], /* 155 SINGLE RIGHT-POINTING ANGLE QUOTATION MARK */
&values[272], /* 156 UNDEFINED */
&values[273], /* 157 UNDEFINED */
&values[274], /* 158 UNDEFINED */
&values[275], /* 159 UNDEFINED */
&values[276], /* 160 NO-BREAK SPACE */
&values[278], /* 161 INVERTED EXCLAMATION MARK */
&values[280], /* 162 CENT SIGN */
&values[282], /* 163 POUND SIGN */
&values[284], /* 164 NEW SHEQEL SIGN */
&values[286], /* 165 YEN SIGN */
&values[288], /* 166 BROKEN BAR */
&values[290], /* 167 SECTION SIGN */
&values[292], /* 168 DIAERESIS */
&values[294], /* 169 COPYRIGHT SIGN */
&values[296], /* 170 MULTIPLICATION SIGN */
&values[298], /* 171 LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[300], /* 172 NOT SIGN */
&values[302], /* 173 SOFT HYPHEN */
&values[304], /* 174 REGISTERED SIGN */
&values[306], /* 175 MACRON */
&values[308], /* 176 DEGREE SIGN */
&values[310], /* 177 PLUS-MINUS SIGN */
&values[312], /* 178 SUPERSCRIPT TWO */
&values[314], /* 179 SUPERSCRIPT THREE */
&values[316], /* 180 ACUTE ACCENT */
&values[318], /* 181 MICRO SIGN */
&values[320], /* 182 PILCROW SIGN */
&values[322], /* 183 MIDDLE DOT */
&values[324], /* 184 CEDILLA */
&values[326], /* 185 SUPERSCRIPT ONE */
&values[328], /* 186 DIVISION SIGN */
&values[330], /* 187 RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[332], /* 188 VULGAR FRACTION ONE QUARTER */
&values[334], /* 189 VULGAR FRACTION ONE HALF */
&values[336], /* 190 VULGAR FRACTION THREE QUARTERS */
&values[338], /* 191 INVERTED QUESTION MARK */
&values[340], /* 192 HEBREW POINT SHEVA */
&values[342], /* 193 HEBREW POINT HATAF SEGOL */
&values[344], /* 194 HEBREW POINT HATAF PATAH */
&values[346], /* 195 HEBREW POINT HATAF QAMATS */
&values[348], /* 196 HEBREW POINT HIRIQ */
&values[350], /* 197 HEBREW POINT TSERE */
&values[352], /* 198 HEBREW POINT SEGOL */
&values[354], /* 199 HEBREW POINT PATAH */
&values[356], /* 200 HEBREW POINT QAMATS */
&values[358], /* 201 HEBREW POINT HOLAM */
&values[360], /* 202 UNDEFINED */
&values[361], /* 203 HEBREW POINT QUBUTS */
&values[363], /* 204 HEBREW POINT DAGESH OR MAPIQ */
&values[365], /* 205 HEBREW POINT METEG */
&values[367], /* 206 HEBREW PUNCTUATION MAQAF */
&values[369], /* 207 HEBREW POINT RAFE */
&values[371], /* 208 HEBREW PUNCTUATION PASEQ */
&values[373], /* 209 HEBREW POINT SHIN DOT */
&values[375], /* 210 HEBREW POINT SIN DOT */
&values[377], /* 211 HEBREW PUNCTUATION SOF PASUQ */
&values[379], /* 212 HEBREW LIGATURE YIDDISH DOUBLE VAV */
&values[381], /* 213 HEBREW LIGATURE YIDDISH VAV YOD */
&values[383], /* 214 HEBREW LIGATURE YIDDISH DOUBLE YOD */
&values[385], /* 215 HEBREW PUNCTUATION GERESH */
&values[387], /* 216 HEBREW PUNCTUATION GERSHAYIM */
&values[389], /* 217 UNDEFINED */
&values[390], /* 218 UNDEFINED */
&values[391], /* 219 UNDEFINED */
&values[392], /* 220 UNDEFINED */
&values[393], /* 221 UNDEFINED */
&values[394], /* 222 UNDEFINED */
&values[395], /* 223 UNDEFINED */
&values[396], /* 224 HEBREW LETTER ALEF */
&values[398], /* 225 HEBREW LETTER BET */
&values[400], /* 226 HEBREW LETTER GIMEL */
&values[402], /* 227 HEBREW LETTER DALET */
&values[404], /* 228 HEBREW LETTER HE */
&values[406], /* 229 HEBREW LETTER VAV */
&values[408], /* 230 HEBREW LETTER ZAYIN */
&values[410], /* 231 HEBREW LETTER HET */
&values[412], /* 232 HEBREW LETTER TET */
&values[414], /* 233 HEBREW LETTER YOD */
&values[416], /* 234 HEBREW LETTER FINAL KAF */
&values[418], /* 235 HEBREW LETTER KAF */
&values[420], /* 236 HEBREW LETTER LAMED */
&values[422], /* 237 HEBREW LETTER FINAL MEM */
&values[424], /* 238 HEBREW LETTER MEM */
&values[426], /* 239 HEBREW LETTER FINAL NUN */
&values[428], /* 240 HEBREW LETTER NUN */
&values[430], /* 241 HEBREW LETTER SAMEKH */
&values[432], /* 242 HEBREW LETTER AYIN */
&values[434], /* 243 HEBREW LETTER FINAL PE */
&values[436], /* 244 HEBREW LETTER PE */
&values[438], /* 245 HEBREW LETTER FINAL TSADI */
&values[440], /* 246 HEBREW LETTER TSADI */
&values[442], /* 247 HEBREW LETTER QOF */
&values[444], /* 248 HEBREW LETTER RESH */
&values[446], /* 249 HEBREW LETTER SHIN */
&values[448], /* 250 HEBREW LETTER TAV */
&values[450], /* 251 UNDEFINED */
&values[451], /* 252 UNDEFINED */
&values[452], /* 253 LEFT-TO-RIGHT MARK */
&values[454], /* 254 RIGHT-TO-LEFT MARK */
&values[456], /* 255 UNDEFINED */
}};
