/* This file was autogenerated from the file 
 * CP1258.TXT from UNICODE.ORG */

/*     Name:     cp1258 to Unicode table */
/*     Unicode version: 2.0 */
/*     Table version: 2.01 */
/*     Table format:  Format A */
/*     Date:          04/15/98 */
/*     Contact:       cpxlate@microsoft.com */
/*     General notes: none */
/*     Format: Three tab-separated columns */
/*         Column #1 is the cp1258 code (in hex) */
/*         Column #2 is the Unicode (in hex as 0xXXXX) */
/*         Column #3 is the Unicode name (follows a comment sign, '#') */
/*     The entries are in cp1258 order */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0xffff, 
0x20ac, 0xffff, 0xffff, 0x201a, 0xffff, 0x0192, 0xffff, 0x201e, 
0xffff, 0x2026, 0xffff, 0x2020, 0xffff, 0x2021, 0xffff, 0x02c6, 
0xffff, 0x2030, 0xffff, 0xffff, 0x2039, 0xffff, 0x0152, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0x2018, 0xffff, 0x2019, 0xffff, 
0x201c, 0xffff, 0x201d, 0xffff, 0x2022, 0xffff, 0x2013, 0xffff, 
0x2014, 0xffff, 0x02dc, 0xffff, 0x2122, 0xffff, 0xffff, 0x203a, 
0xffff, 0x0153, 0xffff, 0xffff, 0xffff, 0x0178, 0xffff, 0x00a0, 
0xffff, 0x00a1, 0xffff, 0x00a2, 0xffff, 0x00a3, 0xffff, 0x00a4, 
0xffff, 0x00a5, 0xffff, 0x00a6, 0xffff, 0x00a7, 0xffff, 0x00a8, 
0xffff, 0x00a9, 0xffff, 0x00aa, 0xffff, 0x00ab, 0xffff, 0x00ac, 
0xffff, 0x00ad, 0xffff, 0x00ae, 0xffff, 0x00af, 0xffff, 0x00b0, 
0xffff, 0x00b1, 0xffff, 0x00b2, 0xffff, 0x00b3, 0xffff, 0x00b4, 
0xffff, 0x00b5, 0xffff, 0x00b6, 0xffff, 0x00b7, 0xffff, 0x00b8, 
0xffff, 0x00b9, 0xffff, 0x00ba, 0xffff, 0x00bb, 0xffff, 0x00bc, 
0xffff, 0x00bd, 0xffff, 0x00be, 0xffff, 0x00bf, 0xffff, 0x00c0, 
0xffff, 0x00c1, 0xffff, 0x00c2, 0xffff, 0x0102, 0xffff, 0x00c4, 
0xffff, 0x00c5, 0xffff, 0x00c6, 0xffff, 0x00c7, 0xffff, 0x00c8, 
0xffff, 0x00c9, 0xffff, 0x00ca, 0xffff, 0x00cb, 0xffff, 0x0300, 
0xffff, 0x00cd, 0xffff, 0x00ce, 0xffff, 0x00cf, 0xffff, 0x0110, 
0xffff, 0x00d1, 0xffff, 0x0309, 0xffff, 0x00d3, 0xffff, 0x00d4, 
0xffff, 0x01a0, 0xffff, 0x00d6, 0xffff, 0x00d7, 0xffff, 0x00d8, 
0xffff, 0x00d9, 0xffff, 0x00da, 0xffff, 0x00db, 0xffff, 0x00dc, 
0xffff, 0x01af, 0xffff, 0x0303, 0xffff, 0x00df, 0xffff, 0x00e0, 
0xffff, 0x00e1, 0xffff, 0x00e2, 0xffff, 0x0103, 0xffff, 0x00e4, 
0xffff, 0x00e5, 0xffff, 0x00e6, 0xffff, 0x00e7, 0xffff, 0x00e8, 
0xffff, 0x00e9, 0xffff, 0x00ea, 0xffff, 0x00eb, 0xffff, 0x0301, 
0xffff, 0x00ed, 0xffff, 0x00ee, 0xffff, 0x00ef, 0xffff, 0x0111, 
0xffff, 0x00f1, 0xffff, 0x0323, 0xffff, 0x00f3, 0xffff, 0x00f4, 
0xffff, 0x01a1, 0xffff, 0x00f6, 0xffff, 0x00f7, 0xffff, 0x00f8, 
0xffff, 0x00f9, 0xffff, 0x00fa, 0xffff, 0x00fb, 0xffff, 0x00fc, 
0xffff, 0x01b0, 0xffff, 0x20ab, 0xffff, 0x00ff, 0xffff, };

struct psf_mapping256 m_CP1258 = { "CP1258", 
256, {
&values[1], /* 0 NULL */
&values[2], /* 1 START OF HEADING */
&values[3], /* 2 START OF TEXT */
&values[4], /* 3 END OF TEXT */
&values[5], /* 4 END OF TRANSMISSION */
&values[6], /* 5 ENQUIRY */
&values[7], /* 6 ACKNOWLEDGE */
&values[8], /* 7 BELL */
&values[9], /* 8 BACKSPACE */
&values[10], /* 9 HORIZONTAL TABULATION */
&values[11], /* 10 LINE FEED */
&values[12], /* 11 VERTICAL TABULATION */
&values[13], /* 12 FORM FEED */
&values[14], /* 13 CARRIAGE RETURN */
&values[15], /* 14 SHIFT OUT */
&values[16], /* 15 SHIFT IN */
&values[17], /* 16 DATA LINK ESCAPE */
&values[18], /* 17 DEVICE CONTROL ONE */
&values[19], /* 18 DEVICE CONTROL TWO */
&values[20], /* 19 DEVICE CONTROL THREE */
&values[21], /* 20 DEVICE CONTROL FOUR */
&values[22], /* 21 NEGATIVE ACKNOWLEDGE */
&values[23], /* 22 SYNCHRONOUS IDLE */
&values[24], /* 23 END OF TRANSMISSION BLOCK */
&values[25], /* 24 CANCEL */
&values[26], /* 25 END OF MEDIUM */
&values[27], /* 26 SUBSTITUTE */
&values[28], /* 27 ESCAPE */
&values[29], /* 28 FILE SEPARATOR */
&values[30], /* 29 GROUP SEPARATOR */
&values[31], /* 30 RECORD SEPARATOR */
&values[32], /* 31 UNIT SEPARATOR */
&values[33], /* 32 SPACE */
&values[35], /* 33 EXCLAMATION MARK */
&values[37], /* 34 QUOTATION MARK */
&values[39], /* 35 NUMBER SIGN */
&values[41], /* 36 DOLLAR SIGN */
&values[43], /* 37 PERCENT SIGN */
&values[45], /* 38 AMPERSAND */
&values[47], /* 39 APOSTROPHE */
&values[49], /* 40 LEFT PARENTHESIS */
&values[51], /* 41 RIGHT PARENTHESIS */
&values[53], /* 42 ASTERISK */
&values[55], /* 43 PLUS SIGN */
&values[57], /* 44 COMMA */
&values[59], /* 45 HYPHEN-MINUS */
&values[61], /* 46 FULL STOP */
&values[63], /* 47 SOLIDUS */
&values[65], /* 48 DIGIT ZERO */
&values[67], /* 49 DIGIT ONE */
&values[69], /* 50 DIGIT TWO */
&values[71], /* 51 DIGIT THREE */
&values[73], /* 52 DIGIT FOUR */
&values[75], /* 53 DIGIT FIVE */
&values[77], /* 54 DIGIT SIX */
&values[79], /* 55 DIGIT SEVEN */
&values[81], /* 56 DIGIT EIGHT */
&values[83], /* 57 DIGIT NINE */
&values[85], /* 58 COLON */
&values[87], /* 59 SEMICOLON */
&values[89], /* 60 LESS-THAN SIGN */
&values[91], /* 61 EQUALS SIGN */
&values[93], /* 62 GREATER-THAN SIGN */
&values[95], /* 63 QUESTION MARK */
&values[97], /* 64 COMMERCIAL AT */
&values[99], /* 65 LATIN CAPITAL LETTER A */
&values[101], /* 66 LATIN CAPITAL LETTER B */
&values[103], /* 67 LATIN CAPITAL LETTER C */
&values[105], /* 68 LATIN CAPITAL LETTER D */
&values[107], /* 69 LATIN CAPITAL LETTER E */
&values[109], /* 70 LATIN CAPITAL LETTER F */
&values[111], /* 71 LATIN CAPITAL LETTER G */
&values[113], /* 72 LATIN CAPITAL LETTER H */
&values[115], /* 73 LATIN CAPITAL LETTER I */
&values[117], /* 74 LATIN CAPITAL LETTER J */
&values[119], /* 75 LATIN CAPITAL LETTER K */
&values[121], /* 76 LATIN CAPITAL LETTER L */
&values[123], /* 77 LATIN CAPITAL LETTER M */
&values[125], /* 78 LATIN CAPITAL LETTER N */
&values[127], /* 79 LATIN CAPITAL LETTER O */
&values[129], /* 80 LATIN CAPITAL LETTER P */
&values[131], /* 81 LATIN CAPITAL LETTER Q */
&values[133], /* 82 LATIN CAPITAL LETTER R */
&values[135], /* 83 LATIN CAPITAL LETTER S */
&values[137], /* 84 LATIN CAPITAL LETTER T */
&values[139], /* 85 LATIN CAPITAL LETTER U */
&values[141], /* 86 LATIN CAPITAL LETTER V */
&values[143], /* 87 LATIN CAPITAL LETTER W */
&values[145], /* 88 LATIN CAPITAL LETTER X */
&values[147], /* 89 LATIN CAPITAL LETTER Y */
&values[149], /* 90 LATIN CAPITAL LETTER Z */
&values[151], /* 91 LEFT SQUARE BRACKET */
&values[153], /* 92 REVERSE SOLIDUS */
&values[155], /* 93 RIGHT SQUARE BRACKET */
&values[157], /* 94 CIRCUMFLEX ACCENT */
&values[159], /* 95 LOW LINE */
&values[161], /* 96 GRAVE ACCENT */
&values[163], /* 97 LATIN SMALL LETTER A */
&values[165], /* 98 LATIN SMALL LETTER B */
&values[167], /* 99 LATIN SMALL LETTER C */
&values[169], /* 100 LATIN SMALL LETTER D */
&values[171], /* 101 LATIN SMALL LETTER E */
&values[173], /* 102 LATIN SMALL LETTER F */
&values[175], /* 103 LATIN SMALL LETTER G */
&values[177], /* 104 LATIN SMALL LETTER H */
&values[179], /* 105 LATIN SMALL LETTER I */
&values[181], /* 106 LATIN SMALL LETTER J */
&values[183], /* 107 LATIN SMALL LETTER K */
&values[185], /* 108 LATIN SMALL LETTER L */
&values[187], /* 109 LATIN SMALL LETTER M */
&values[189], /* 110 LATIN SMALL LETTER N */
&values[191], /* 111 LATIN SMALL LETTER O */
&values[193], /* 112 LATIN SMALL LETTER P */
&values[195], /* 113 LATIN SMALL LETTER Q */
&values[197], /* 114 LATIN SMALL LETTER R */
&values[199], /* 115 LATIN SMALL LETTER S */
&values[201], /* 116 LATIN SMALL LETTER T */
&values[203], /* 117 LATIN SMALL LETTER U */
&values[205], /* 118 LATIN SMALL LETTER V */
&values[207], /* 119 LATIN SMALL LETTER W */
&values[209], /* 120 LATIN SMALL LETTER X */
&values[211], /* 121 LATIN SMALL LETTER Y */
&values[213], /* 122 LATIN SMALL LETTER Z */
&values[215], /* 123 LEFT CURLY BRACKET */
&values[217], /* 124 VERTICAL LINE */
&values[219], /* 125 RIGHT CURLY BRACKET */
&values[221], /* 126 TILDE */
&values[223], /* 127 DELETE */
&values[224], /* 128 EURO SIGN */
&values[226], /* 129 UNDEFINED */
&values[227], /* 130 SINGLE LOW-9 QUOTATION MARK */
&values[229], /* 131 LATIN SMALL LETTER F WITH HOOK */
&values[231], /* 132 DOUBLE LOW-9 QUOTATION MARK */
&values[233], /* 133 HORIZONTAL ELLIPSIS */
&values[235], /* 134 DAGGER */
&values[237], /* 135 DOUBLE DAGGER */
&values[239], /* 136 MODIFIER LETTER CIRCUMFLEX ACCENT */
&values[241], /* 137 PER MILLE SIGN */
&values[243], /* 138 UNDEFINED */
&values[244], /* 139 SINGLE LEFT-POINTING ANGLE QUOTATION MARK */
&values[246], /* 140 LATIN CAPITAL LIGATURE OE */
&values[248], /* 141 UNDEFINED */
&values[249], /* 142 UNDEFINED */
&values[250], /* 143 UNDEFINED */
&values[251], /* 144 UNDEFINED */
&values[252], /* 145 LEFT SINGLE QUOTATION MARK */
&values[254], /* 146 RIGHT SINGLE QUOTATION MARK */
&values[256], /* 147 LEFT DOUBLE QUOTATION MARK */
&values[258], /* 148 RIGHT DOUBLE QUOTATION MARK */
&values[260], /* 149 BULLET */
&values[262], /* 150 EN DASH */
&values[264], /* 151 EM DASH */
&values[266], /* 152 SMALL TILDE */
&values[268], /* 153 TRADE MARK SIGN */
&values[270], /* 154 UNDEFINED */
&values[271], /* 155 SINGLE RIGHT-POINTING ANGLE QUOTATION MARK */
&values[273], /* 156 LATIN SMALL LIGATURE OE */
&values[275], /* 157 UNDEFINED */
&values[276], /* 158 UNDEFINED */
&values[277], /* 159 LATIN CAPITAL LETTER Y WITH DIAERESIS */
&values[279], /* 160 NO-BREAK SPACE */
&values[281], /* 161 INVERTED EXCLAMATION MARK */
&values[283], /* 162 CENT SIGN */
&values[285], /* 163 POUND SIGN */
&values[287], /* 164 CURRENCY SIGN */
&values[289], /* 165 YEN SIGN */
&values[291], /* 166 BROKEN BAR */
&values[293], /* 167 SECTION SIGN */
&values[295], /* 168 DIAERESIS */
&values[297], /* 169 COPYRIGHT SIGN */
&values[299], /* 170 FEMININE ORDINAL INDICATOR */
&values[301], /* 171 LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[303], /* 172 NOT SIGN */
&values[305], /* 173 SOFT HYPHEN */
&values[307], /* 174 REGISTERED SIGN */
&values[309], /* 175 MACRON */
&values[311], /* 176 DEGREE SIGN */
&values[313], /* 177 PLUS-MINUS SIGN */
&values[315], /* 178 SUPERSCRIPT TWO */
&values[317], /* 179 SUPERSCRIPT THREE */
&values[319], /* 180 ACUTE ACCENT */
&values[321], /* 181 MICRO SIGN */
&values[323], /* 182 PILCROW SIGN */
&values[325], /* 183 MIDDLE DOT */
&values[327], /* 184 CEDILLA */
&values[329], /* 185 SUPERSCRIPT ONE */
&values[331], /* 186 MASCULINE ORDINAL INDICATOR */
&values[333], /* 187 RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[335], /* 188 VULGAR FRACTION ONE QUARTER */
&values[337], /* 189 VULGAR FRACTION ONE HALF */
&values[339], /* 190 VULGAR FRACTION THREE QUARTERS */
&values[341], /* 191 INVERTED QUESTION MARK */
&values[343], /* 192 LATIN CAPITAL LETTER A WITH GRAVE */
&values[345], /* 193 LATIN CAPITAL LETTER A WITH ACUTE */
&values[347], /* 194 LATIN CAPITAL LETTER A WITH CIRCUMFLEX */
&values[349], /* 195 LATIN CAPITAL LETTER A WITH BREVE */
&values[351], /* 196 LATIN CAPITAL LETTER A WITH DIAERESIS */
&values[353], /* 197 LATIN CAPITAL LETTER A WITH RING ABOVE */
&values[355], /* 198 LATIN CAPITAL LETTER AE */
&values[357], /* 199 LATIN CAPITAL LETTER C WITH CEDILLA */
&values[359], /* 200 LATIN CAPITAL LETTER E WITH GRAVE */
&values[361], /* 201 LATIN CAPITAL LETTER E WITH ACUTE */
&values[363], /* 202 LATIN CAPITAL LETTER E WITH CIRCUMFLEX */
&values[365], /* 203 LATIN CAPITAL LETTER E WITH DIAERESIS */
&values[367], /* 204 COMBINING GRAVE ACCENT */
&values[369], /* 205 LATIN CAPITAL LETTER I WITH ACUTE */
&values[371], /* 206 LATIN CAPITAL LETTER I WITH CIRCUMFLEX */
&values[373], /* 207 LATIN CAPITAL LETTER I WITH DIAERESIS */
&values[375], /* 208 LATIN CAPITAL LETTER D WITH STROKE */
&values[377], /* 209 LATIN CAPITAL LETTER N WITH TILDE */
&values[379], /* 210 COMBINING HOOK ABOVE */
&values[381], /* 211 LATIN CAPITAL LETTER O WITH ACUTE */
&values[383], /* 212 LATIN CAPITAL LETTER O WITH CIRCUMFLEX */
&values[385], /* 213 LATIN CAPITAL LETTER O WITH HORN */
&values[387], /* 214 LATIN CAPITAL LETTER O WITH DIAERESIS */
&values[389], /* 215 MULTIPLICATION SIGN */
&values[391], /* 216 LATIN CAPITAL LETTER O WITH STROKE */
&values[393], /* 217 LATIN CAPITAL LETTER U WITH GRAVE */
&values[395], /* 218 LATIN CAPITAL LETTER U WITH ACUTE */
&values[397], /* 219 LATIN CAPITAL LETTER U WITH CIRCUMFLEX */
&values[399], /* 220 LATIN CAPITAL LETTER U WITH DIAERESIS */
&values[401], /* 221 LATIN CAPITAL LETTER U WITH HORN */
&values[403], /* 222 COMBINING TILDE */
&values[405], /* 223 LATIN SMALL LETTER SHARP S */
&values[407], /* 224 LATIN SMALL LETTER A WITH GRAVE */
&values[409], /* 225 LATIN SMALL LETTER A WITH ACUTE */
&values[411], /* 226 LATIN SMALL LETTER A WITH CIRCUMFLEX */
&values[413], /* 227 LATIN SMALL LETTER A WITH BREVE */
&values[415], /* 228 LATIN SMALL LETTER A WITH DIAERESIS */
&values[417], /* 229 LATIN SMALL LETTER A WITH RING ABOVE */
&values[419], /* 230 LATIN SMALL LETTER AE */
&values[421], /* 231 LATIN SMALL LETTER C WITH CEDILLA */
&values[423], /* 232 LATIN SMALL LETTER E WITH GRAVE */
&values[425], /* 233 LATIN SMALL LETTER E WITH ACUTE */
&values[427], /* 234 LATIN SMALL LETTER E WITH CIRCUMFLEX */
&values[429], /* 235 LATIN SMALL LETTER E WITH DIAERESIS */
&values[431], /* 236 COMBINING ACUTE ACCENT */
&values[433], /* 237 LATIN SMALL LETTER I WITH ACUTE */
&values[435], /* 238 LATIN SMALL LETTER I WITH CIRCUMFLEX */
&values[437], /* 239 LATIN SMALL LETTER I WITH DIAERESIS */
&values[439], /* 240 LATIN SMALL LETTER D WITH STROKE */
&values[441], /* 241 LATIN SMALL LETTER N WITH TILDE */
&values[443], /* 242 COMBINING DOT BELOW */
&values[445], /* 243 LATIN SMALL LETTER O WITH ACUTE */
&values[447], /* 244 LATIN SMALL LETTER O WITH CIRCUMFLEX */
&values[449], /* 245 LATIN SMALL LETTER O WITH HORN */
&values[451], /* 246 LATIN SMALL LETTER O WITH DIAERESIS */
&values[453], /* 247 DIVISION SIGN */
&values[455], /* 248 LATIN SMALL LETTER O WITH STROKE */
&values[457], /* 249 LATIN SMALL LETTER U WITH GRAVE */
&values[459], /* 250 LATIN SMALL LETTER U WITH ACUTE */
&values[461], /* 251 LATIN SMALL LETTER U WITH CIRCUMFLEX */
&values[463], /* 252 LATIN SMALL LETTER U WITH DIAERESIS */
&values[465], /* 253 LATIN SMALL LETTER U WITH HORN */
&values[467], /* 254 DONG SIGN */
&values[469], /* 255 LATIN SMALL LETTER Y WITH DIAERESIS */
}};
