/* This file was autogenerated from the file 
 * CP1253.TXT from UNICODE.ORG */

/*     Name:     cp1253 to Unicode table */
/*     Unicode version: 2.0 */
/*     Table version: 2.01 */
/*     Table format:  Format A */
/*     Date:          04/15/98 */
/*     Contact:       cpxlate@microsoft.com */
/*     General notes: none */
/*     Format: Three tab-separated columns */
/*         Column #1 is the cp1253 code (in hex) */
/*         Column #2 is the Unicode (in hex as 0xXXXX) */
/*         Column #3 is the Unicode name (follows a comment sign, '#') */
/*     The entries are in cp1253 order */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0xffff, 
0x20ac, 0xffff, 0xffff, 0x201a, 0xffff, 0x0192, 0xffff, 0x201e, 
0xffff, 0x2026, 0xffff, 0x2020, 0xffff, 0x2021, 0xffff, 0xffff, 
0x2030, 0xffff, 0xffff, 0x2039, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0x2018, 0xffff, 0x2019, 0xffff, 0x201c, 0xffff, 
0x201d, 0xffff, 0x2022, 0xffff, 0x2013, 0xffff, 0x2014, 0xffff, 
0xffff, 0x2122, 0xffff, 0xffff, 0x203a, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0x00a0, 0xffff, 0x0385, 0xffff, 0x0386, 0xffff, 
0x00a3, 0xffff, 0x00a4, 0xffff, 0x00a5, 0xffff, 0x00a6, 0xffff, 
0x00a7, 0xffff, 0x00a8, 0xffff, 0x00a9, 0xffff, 0xffff, 0x00ab, 
0xffff, 0x00ac, 0xffff, 0x00ad, 0xffff, 0x00ae, 0xffff, 0x2015, 
0xffff, 0x00b0, 0xffff, 0x00b1, 0xffff, 0x00b2, 0xffff, 0x00b3, 
0xffff, 0x0384, 0xffff, 0x00b5, 0xffff, 0x00b6, 0xffff, 0x00b7, 
0xffff, 0x0388, 0xffff, 0x0389, 0xffff, 0x038a, 0xffff, 0x00bb, 
0xffff, 0x038c, 0xffff, 0x00bd, 0xffff, 0x038e, 0xffff, 0x038f, 
0xffff, 0x0390, 0xffff, 0x0391, 0xffff, 0x0392, 0xffff, 0x0393, 
0xffff, 0x0394, 0xffff, 0x0395, 0xffff, 0x0396, 0xffff, 0x0397, 
0xffff, 0x0398, 0xffff, 0x0399, 0xffff, 0x039a, 0xffff, 0x039b, 
0xffff, 0x039c, 0xffff, 0x039d, 0xffff, 0x039e, 0xffff, 0x039f, 
0xffff, 0x03a0, 0xffff, 0x03a1, 0xffff, 0xffff, 0x03a3, 0xffff, 
0x03a4, 0xffff, 0x03a5, 0xffff, 0x03a6, 0xffff, 0x03a7, 0xffff, 
0x03a8, 0xffff, 0x03a9, 0xffff, 0x03aa, 0xffff, 0x03ab, 0xffff, 
0x03ac, 0xffff, 0x03ad, 0xffff, 0x03ae, 0xffff, 0x03af, 0xffff, 
0x03b0, 0xffff, 0x03b1, 0xffff, 0x03b2, 0xffff, 0x03b3, 0xffff, 
0x03b4, 0xffff, 0x03b5, 0xffff, 0x03b6, 0xffff, 0x03b7, 0xffff, 
0x03b8, 0xffff, 0x03b9, 0xffff, 0x03ba, 0xffff, 0x03bb, 0xffff, 
0x03bc, 0xffff, 0x03bd, 0xffff, 0x03be, 0xffff, 0x03bf, 0xffff, 
0x03c0, 0xffff, 0x03c1, 0xffff, 0x03c2, 0xffff, 0x03c3, 0xffff, 
0x03c4, 0xffff, 0x03c5, 0xffff, 0x03c6, 0xffff, 0x03c7, 0xffff, 
0x03c8, 0xffff, 0x03c9, 0xffff, 0x03ca, 0xffff, 0x03cb, 0xffff, 
0x03cc, 0xffff, 0x03cd, 0xffff, 0x03ce, 0xffff, 0xffff, };

struct psf_mapping256 m_CP1253 = { "CP1253", 
256, {
&values[1], /* 0 NULL */
&values[2], /* 1 START OF HEADING */
&values[3], /* 2 START OF TEXT */
&values[4], /* 3 END OF TEXT */
&values[5], /* 4 END OF TRANSMISSION */
&values[6], /* 5 ENQUIRY */
&values[7], /* 6 ACKNOWLEDGE */
&values[8], /* 7 BELL */
&values[9], /* 8 BACKSPACE */
&values[10], /* 9 HORIZONTAL TABULATION */
&values[11], /* 10 LINE FEED */
&values[12], /* 11 VERTICAL TABULATION */
&values[13], /* 12 FORM FEED */
&values[14], /* 13 CARRIAGE RETURN */
&values[15], /* 14 SHIFT OUT */
&values[16], /* 15 SHIFT IN */
&values[17], /* 16 DATA LINK ESCAPE */
&values[18], /* 17 DEVICE CONTROL ONE */
&values[19], /* 18 DEVICE CONTROL TWO */
&values[20], /* 19 DEVICE CONTROL THREE */
&values[21], /* 20 DEVICE CONTROL FOUR */
&values[22], /* 21 NEGATIVE ACKNOWLEDGE */
&values[23], /* 22 SYNCHRONOUS IDLE */
&values[24], /* 23 END OF TRANSMISSION BLOCK */
&values[25], /* 24 CANCEL */
&values[26], /* 25 END OF MEDIUM */
&values[27], /* 26 SUBSTITUTE */
&values[28], /* 27 ESCAPE */
&values[29], /* 28 FILE SEPARATOR */
&values[30], /* 29 GROUP SEPARATOR */
&values[31], /* 30 RECORD SEPARATOR */
&values[32], /* 31 UNIT SEPARATOR */
&values[33], /* 32 SPACE */
&values[35], /* 33 EXCLAMATION MARK */
&values[37], /* 34 QUOTATION MARK */
&values[39], /* 35 NUMBER SIGN */
&values[41], /* 36 DOLLAR SIGN */
&values[43], /* 37 PERCENT SIGN */
&values[45], /* 38 AMPERSAND */
&values[47], /* 39 APOSTROPHE */
&values[49], /* 40 LEFT PARENTHESIS */
&values[51], /* 41 RIGHT PARENTHESIS */
&values[53], /* 42 ASTERISK */
&values[55], /* 43 PLUS SIGN */
&values[57], /* 44 COMMA */
&values[59], /* 45 HYPHEN-MINUS */
&values[61], /* 46 FULL STOP */
&values[63], /* 47 SOLIDUS */
&values[65], /* 48 DIGIT ZERO */
&values[67], /* 49 DIGIT ONE */
&values[69], /* 50 DIGIT TWO */
&values[71], /* 51 DIGIT THREE */
&values[73], /* 52 DIGIT FOUR */
&values[75], /* 53 DIGIT FIVE */
&values[77], /* 54 DIGIT SIX */
&values[79], /* 55 DIGIT SEVEN */
&values[81], /* 56 DIGIT EIGHT */
&values[83], /* 57 DIGIT NINE */
&values[85], /* 58 COLON */
&values[87], /* 59 SEMICOLON */
&values[89], /* 60 LESS-THAN SIGN */
&values[91], /* 61 EQUALS SIGN */
&values[93], /* 62 GREATER-THAN SIGN */
&values[95], /* 63 QUESTION MARK */
&values[97], /* 64 COMMERCIAL AT */
&values[99], /* 65 LATIN CAPITAL LETTER A */
&values[101], /* 66 LATIN CAPITAL LETTER B */
&values[103], /* 67 LATIN CAPITAL LETTER C */
&values[105], /* 68 LATIN CAPITAL LETTER D */
&values[107], /* 69 LATIN CAPITAL LETTER E */
&values[109], /* 70 LATIN CAPITAL LETTER F */
&values[111], /* 71 LATIN CAPITAL LETTER G */
&values[113], /* 72 LATIN CAPITAL LETTER H */
&values[115], /* 73 LATIN CAPITAL LETTER I */
&values[117], /* 74 LATIN CAPITAL LETTER J */
&values[119], /* 75 LATIN CAPITAL LETTER K */
&values[121], /* 76 LATIN CAPITAL LETTER L */
&values[123], /* 77 LATIN CAPITAL LETTER M */
&values[125], /* 78 LATIN CAPITAL LETTER N */
&values[127], /* 79 LATIN CAPITAL LETTER O */
&values[129], /* 80 LATIN CAPITAL LETTER P */
&values[131], /* 81 LATIN CAPITAL LETTER Q */
&values[133], /* 82 LATIN CAPITAL LETTER R */
&values[135], /* 83 LATIN CAPITAL LETTER S */
&values[137], /* 84 LATIN CAPITAL LETTER T */
&values[139], /* 85 LATIN CAPITAL LETTER U */
&values[141], /* 86 LATIN CAPITAL LETTER V */
&values[143], /* 87 LATIN CAPITAL LETTER W */
&values[145], /* 88 LATIN CAPITAL LETTER X */
&values[147], /* 89 LATIN CAPITAL LETTER Y */
&values[149], /* 90 LATIN CAPITAL LETTER Z */
&values[151], /* 91 LEFT SQUARE BRACKET */
&values[153], /* 92 REVERSE SOLIDUS */
&values[155], /* 93 RIGHT SQUARE BRACKET */
&values[157], /* 94 CIRCUMFLEX ACCENT */
&values[159], /* 95 LOW LINE */
&values[161], /* 96 GRAVE ACCENT */
&values[163], /* 97 LATIN SMALL LETTER A */
&values[165], /* 98 LATIN SMALL LETTER B */
&values[167], /* 99 LATIN SMALL LETTER C */
&values[169], /* 100 LATIN SMALL LETTER D */
&values[171], /* 101 LATIN SMALL LETTER E */
&values[173], /* 102 LATIN SMALL LETTER F */
&values[175], /* 103 LATIN SMALL LETTER G */
&values[177], /* 104 LATIN SMALL LETTER H */
&values[179], /* 105 LATIN SMALL LETTER I */
&values[181], /* 106 LATIN SMALL LETTER J */
&values[183], /* 107 LATIN SMALL LETTER K */
&values[185], /* 108 LATIN SMALL LETTER L */
&values[187], /* 109 LATIN SMALL LETTER M */
&values[189], /* 110 LATIN SMALL LETTER N */
&values[191], /* 111 LATIN SMALL LETTER O */
&values[193], /* 112 LATIN SMALL LETTER P */
&values[195], /* 113 LATIN SMALL LETTER Q */
&values[197], /* 114 LATIN SMALL LETTER R */
&values[199], /* 115 LATIN SMALL LETTER S */
&values[201], /* 116 LATIN SMALL LETTER T */
&values[203], /* 117 LATIN SMALL LETTER U */
&values[205], /* 118 LATIN SMALL LETTER V */
&values[207], /* 119 LATIN SMALL LETTER W */
&values[209], /* 120 LATIN SMALL LETTER X */
&values[211], /* 121 LATIN SMALL LETTER Y */
&values[213], /* 122 LATIN SMALL LETTER Z */
&values[215], /* 123 LEFT CURLY BRACKET */
&values[217], /* 124 VERTICAL LINE */
&values[219], /* 125 RIGHT CURLY BRACKET */
&values[221], /* 126 TILDE */
&values[223], /* 127 DELETE */
&values[224], /* 128 EURO SIGN */
&values[226], /* 129 UNDEFINED */
&values[227], /* 130 SINGLE LOW-9 QUOTATION MARK */
&values[229], /* 131 LATIN SMALL LETTER F WITH HOOK */
&values[231], /* 132 DOUBLE LOW-9 QUOTATION MARK */
&values[233], /* 133 HORIZONTAL ELLIPSIS */
&values[235], /* 134 DAGGER */
&values[237], /* 135 DOUBLE DAGGER */
&values[239], /* 136 UNDEFINED */
&values[240], /* 137 PER MILLE SIGN */
&values[242], /* 138 UNDEFINED */
&values[243], /* 139 SINGLE LEFT-POINTING ANGLE QUOTATION MARK */
&values[245], /* 140 UNDEFINED */
&values[246], /* 141 UNDEFINED */
&values[247], /* 142 UNDEFINED */
&values[248], /* 143 UNDEFINED */
&values[249], /* 144 UNDEFINED */
&values[250], /* 145 LEFT SINGLE QUOTATION MARK */
&values[252], /* 146 RIGHT SINGLE QUOTATION MARK */
&values[254], /* 147 LEFT DOUBLE QUOTATION MARK */
&values[256], /* 148 RIGHT DOUBLE QUOTATION MARK */
&values[258], /* 149 BULLET */
&values[260], /* 150 EN DASH */
&values[262], /* 151 EM DASH */
&values[264], /* 152 UNDEFINED */
&values[265], /* 153 TRADE MARK SIGN */
&values[267], /* 154 UNDEFINED */
&values[268], /* 155 SINGLE RIGHT-POINTING ANGLE QUOTATION MARK */
&values[270], /* 156 UNDEFINED */
&values[271], /* 157 UNDEFINED */
&values[272], /* 158 UNDEFINED */
&values[273], /* 159 UNDEFINED */
&values[274], /* 160 NO-BREAK SPACE */
&values[276], /* 161 GREEK DIALYTIKA TONOS */
&values[278], /* 162 GREEK CAPITAL LETTER ALPHA WITH TONOS */
&values[280], /* 163 POUND SIGN */
&values[282], /* 164 CURRENCY SIGN */
&values[284], /* 165 YEN SIGN */
&values[286], /* 166 BROKEN BAR */
&values[288], /* 167 SECTION SIGN */
&values[290], /* 168 DIAERESIS */
&values[292], /* 169 COPYRIGHT SIGN */
&values[294], /* 170 UNDEFINED */
&values[295], /* 171 LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[297], /* 172 NOT SIGN */
&values[299], /* 173 SOFT HYPHEN */
&values[301], /* 174 REGISTERED SIGN */
&values[303], /* 175 HORIZONTAL BAR */
&values[305], /* 176 DEGREE SIGN */
&values[307], /* 177 PLUS-MINUS SIGN */
&values[309], /* 178 SUPERSCRIPT TWO */
&values[311], /* 179 SUPERSCRIPT THREE */
&values[313], /* 180 GREEK TONOS */
&values[315], /* 181 MICRO SIGN */
&values[317], /* 182 PILCROW SIGN */
&values[319], /* 183 MIDDLE DOT */
&values[321], /* 184 GREEK CAPITAL LETTER EPSILON WITH TONOS */
&values[323], /* 185 GREEK CAPITAL LETTER ETA WITH TONOS */
&values[325], /* 186 GREEK CAPITAL LETTER IOTA WITH TONOS */
&values[327], /* 187 RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[329], /* 188 GREEK CAPITAL LETTER OMICRON WITH TONOS */
&values[331], /* 189 VULGAR FRACTION ONE HALF */
&values[333], /* 190 GREEK CAPITAL LETTER UPSILON WITH TONOS */
&values[335], /* 191 GREEK CAPITAL LETTER OMEGA WITH TONOS */
&values[337], /* 192 GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS */
&values[339], /* 193 GREEK CAPITAL LETTER ALPHA */
&values[341], /* 194 GREEK CAPITAL LETTER BETA */
&values[343], /* 195 GREEK CAPITAL LETTER GAMMA */
&values[345], /* 196 GREEK CAPITAL LETTER DELTA */
&values[347], /* 197 GREEK CAPITAL LETTER EPSILON */
&values[349], /* 198 GREEK CAPITAL LETTER ZETA */
&values[351], /* 199 GREEK CAPITAL LETTER ETA */
&values[353], /* 200 GREEK CAPITAL LETTER THETA */
&values[355], /* 201 GREEK CAPITAL LETTER IOTA */
&values[357], /* 202 GREEK CAPITAL LETTER KAPPA */
&values[359], /* 203 GREEK CAPITAL LETTER LAMDA */
&values[361], /* 204 GREEK CAPITAL LETTER MU */
&values[363], /* 205 GREEK CAPITAL LETTER NU */
&values[365], /* 206 GREEK CAPITAL LETTER XI */
&values[367], /* 207 GREEK CAPITAL LETTER OMICRON */
&values[369], /* 208 GREEK CAPITAL LETTER PI */
&values[371], /* 209 GREEK CAPITAL LETTER RHO */
&values[373], /* 210 UNDEFINED */
&values[374], /* 211 GREEK CAPITAL LETTER SIGMA */
&values[376], /* 212 GREEK CAPITAL LETTER TAU */
&values[378], /* 213 GREEK CAPITAL LETTER UPSILON */
&values[380], /* 214 GREEK CAPITAL LETTER PHI */
&values[382], /* 215 GREEK CAPITAL LETTER CHI */
&values[384], /* 216 GREEK CAPITAL LETTER PSI */
&values[386], /* 217 GREEK CAPITAL LETTER OMEGA */
&values[388], /* 218 GREEK CAPITAL LETTER IOTA WITH DIALYTIKA */
&values[390], /* 219 GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA */
&values[392], /* 220 GREEK SMALL LETTER ALPHA WITH TONOS */
&values[394], /* 221 GREEK SMALL LETTER EPSILON WITH TONOS */
&values[396], /* 222 GREEK SMALL LETTER ETA WITH TONOS */
&values[398], /* 223 GREEK SMALL LETTER IOTA WITH TONOS */
&values[400], /* 224 GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS */
&values[402], /* 225 GREEK SMALL LETTER ALPHA */
&values[404], /* 226 GREEK SMALL LETTER BETA */
&values[406], /* 227 GREEK SMALL LETTER GAMMA */
&values[408], /* 228 GREEK SMALL LETTER DELTA */
&values[410], /* 229 GREEK SMALL LETTER EPSILON */
&values[412], /* 230 GREEK SMALL LETTER ZETA */
&values[414], /* 231 GREEK SMALL LETTER ETA */
&values[416], /* 232 GREEK SMALL LETTER THETA */
&values[418], /* 233 GREEK SMALL LETTER IOTA */
&values[420], /* 234 GREEK SMALL LETTER KAPPA */
&values[422], /* 235 GREEK SMALL LETTER LAMDA */
&values[424], /* 236 GREEK SMALL LETTER MU */
&values[426], /* 237 GREEK SMALL LETTER NU */
&values[428], /* 238 GREEK SMALL LETTER XI */
&values[430], /* 239 GREEK SMALL LETTER OMICRON */
&values[432], /* 240 GREEK SMALL LETTER PI */
&values[434], /* 241 GREEK SMALL LETTER RHO */
&values[436], /* 242 GREEK SMALL LETTER FINAL SIGMA */
&values[438], /* 243 GREEK SMALL LETTER SIGMA */
&values[440], /* 244 GREEK SMALL LETTER TAU */
&values[442], /* 245 GREEK SMALL LETTER UPSILON */
&values[444], /* 246 GREEK SMALL LETTER PHI */
&values[446], /* 247 GREEK SMALL LETTER CHI */
&values[448], /* 248 GREEK SMALL LETTER PSI */
&values[450], /* 249 GREEK SMALL LETTER OMEGA */
&values[452], /* 250 GREEK SMALL LETTER IOTA WITH DIALYTIKA */
&values[454], /* 251 GREEK SMALL LETTER UPSILON WITH DIALYTIKA */
&values[456], /* 252 GREEK SMALL LETTER OMICRON WITH TONOS */
&values[458], /* 253 GREEK SMALL LETTER UPSILON WITH TONOS */
&values[460], /* 254 GREEK SMALL LETTER OMEGA WITH TONOS */
&values[462], /* 255 UNDEFINED */
}};
