/* This file was autogenerated from the file 
 * CP1257.TXT from UNICODE.ORG */

/*     Name:     cp1257 to Unicode table */
/*     Unicode version: 2.0 */
/*     Table version: 2.01 */
/*     Table format:  Format A */
/*     Date:          04/15/98 */
/*     Contact:       cpxlate@microsoft.com */
/*     General notes: none */
/*     Format: Three tab-separated columns */
/*         Column #1 is the cp1257 code (in hex) */
/*         Column #2 is the Unicode (in hex as 0xXXXX) */
/*         Column #3 is the Unicode name (follows a comment sign, '#') */
/*     The entries are in cp1257 order */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0xffff, 
0x20ac, 0xffff, 0xffff, 0x201a, 0xffff, 0xffff, 0x201e, 0xffff, 
0x2026, 0xffff, 0x2020, 0xffff, 0x2021, 0xffff, 0xffff, 0x2030, 
0xffff, 0xffff, 0x2039, 0xffff, 0xffff, 0x00a8, 0xffff, 0x02c7, 
0xffff, 0x00b8, 0xffff, 0xffff, 0x2018, 0xffff, 0x2019, 0xffff, 
0x201c, 0xffff, 0x201d, 0xffff, 0x2022, 0xffff, 0x2013, 0xffff, 
0x2014, 0xffff, 0xffff, 0x2122, 0xffff, 0xffff, 0x203a, 0xffff, 
0xffff, 0x00af, 0xffff, 0x02db, 0xffff, 0xffff, 0x00a0, 0xffff, 
0xffff, 0x00a2, 0xffff, 0x00a3, 0xffff, 0x00a4, 0xffff, 0xffff, 
0x00a6, 0xffff, 0x00a7, 0xffff, 0x00d8, 0xffff, 0x00a9, 0xffff, 
0x0156, 0xffff, 0x00ab, 0xffff, 0x00ac, 0xffff, 0x00ad, 0xffff, 
0x00ae, 0xffff, 0x00c6, 0xffff, 0x00b0, 0xffff, 0x00b1, 0xffff, 
0x00b2, 0xffff, 0x00b3, 0xffff, 0x00b4, 0xffff, 0x00b5, 0xffff, 
0x00b6, 0xffff, 0x00b7, 0xffff, 0x00f8, 0xffff, 0x00b9, 0xffff, 
0x0157, 0xffff, 0x00bb, 0xffff, 0x00bc, 0xffff, 0x00bd, 0xffff, 
0x00be, 0xffff, 0x00e6, 0xffff, 0x0104, 0xffff, 0x012e, 0xffff, 
0x0100, 0xffff, 0x0106, 0xffff, 0x00c4, 0xffff, 0x00c5, 0xffff, 
0x0118, 0xffff, 0x0112, 0xffff, 0x010c, 0xffff, 0x00c9, 0xffff, 
0x0179, 0xffff, 0x0116, 0xffff, 0x0122, 0xffff, 0x0136, 0xffff, 
0x012a, 0xffff, 0x013b, 0xffff, 0x0160, 0xffff, 0x0143, 0xffff, 
0x0145, 0xffff, 0x00d3, 0xffff, 0x014c, 0xffff, 0x00d5, 0xffff, 
0x00d6, 0xffff, 0x00d7, 0xffff, 0x0172, 0xffff, 0x0141, 0xffff, 
0x015a, 0xffff, 0x016a, 0xffff, 0x00dc, 0xffff, 0x017b, 0xffff, 
0x017d, 0xffff, 0x00df, 0xffff, 0x0105, 0xffff, 0x012f, 0xffff, 
0x0101, 0xffff, 0x0107, 0xffff, 0x00e4, 0xffff, 0x00e5, 0xffff, 
0x0119, 0xffff, 0x0113, 0xffff, 0x010d, 0xffff, 0x00e9, 0xffff, 
0x017a, 0xffff, 0x0117, 0xffff, 0x0123, 0xffff, 0x0137, 0xffff, 
0x012b, 0xffff, 0x013c, 0xffff, 0x0161, 0xffff, 0x0144, 0xffff, 
0x0146, 0xffff, 0x00f3, 0xffff, 0x014d, 0xffff, 0x00f5, 0xffff, 
0x00f6, 0xffff, 0x00f7, 0xffff, 0x0173, 0xffff, 0x0142, 0xffff, 
0x015b, 0xffff, 0x016b, 0xffff, 0x00fc, 0xffff, 0x017c, 0xffff, 
0x017e, 0xffff, 0x02d9, 0xffff, };

struct psf_mapping256 m_CP1257 = { "CP1257", 
256, {
&values[1], /* 0 NULL */
&values[2], /* 1 START OF HEADING */
&values[3], /* 2 START OF TEXT */
&values[4], /* 3 END OF TEXT */
&values[5], /* 4 END OF TRANSMISSION */
&values[6], /* 5 ENQUIRY */
&values[7], /* 6 ACKNOWLEDGE */
&values[8], /* 7 BELL */
&values[9], /* 8 BACKSPACE */
&values[10], /* 9 HORIZONTAL TABULATION */
&values[11], /* 10 LINE FEED */
&values[12], /* 11 VERTICAL TABULATION */
&values[13], /* 12 FORM FEED */
&values[14], /* 13 CARRIAGE RETURN */
&values[15], /* 14 SHIFT OUT */
&values[16], /* 15 SHIFT IN */
&values[17], /* 16 DATA LINK ESCAPE */
&values[18], /* 17 DEVICE CONTROL ONE */
&values[19], /* 18 DEVICE CONTROL TWO */
&values[20], /* 19 DEVICE CONTROL THREE */
&values[21], /* 20 DEVICE CONTROL FOUR */
&values[22], /* 21 NEGATIVE ACKNOWLEDGE */
&values[23], /* 22 SYNCHRONOUS IDLE */
&values[24], /* 23 END OF TRANSMISSION BLOCK */
&values[25], /* 24 CANCEL */
&values[26], /* 25 END OF MEDIUM */
&values[27], /* 26 SUBSTITUTE */
&values[28], /* 27 ESCAPE */
&values[29], /* 28 FILE SEPARATOR */
&values[30], /* 29 GROUP SEPARATOR */
&values[31], /* 30 RECORD SEPARATOR */
&values[32], /* 31 UNIT SEPARATOR */
&values[33], /* 32 SPACE */
&values[35], /* 33 EXCLAMATION MARK */
&values[37], /* 34 QUOTATION MARK */
&values[39], /* 35 NUMBER SIGN */
&values[41], /* 36 DOLLAR SIGN */
&values[43], /* 37 PERCENT SIGN */
&values[45], /* 38 AMPERSAND */
&values[47], /* 39 APOSTROPHE */
&values[49], /* 40 LEFT PARENTHESIS */
&values[51], /* 41 RIGHT PARENTHESIS */
&values[53], /* 42 ASTERISK */
&values[55], /* 43 PLUS SIGN */
&values[57], /* 44 COMMA */
&values[59], /* 45 HYPHEN-MINUS */
&values[61], /* 46 FULL STOP */
&values[63], /* 47 SOLIDUS */
&values[65], /* 48 DIGIT ZERO */
&values[67], /* 49 DIGIT ONE */
&values[69], /* 50 DIGIT TWO */
&values[71], /* 51 DIGIT THREE */
&values[73], /* 52 DIGIT FOUR */
&values[75], /* 53 DIGIT FIVE */
&values[77], /* 54 DIGIT SIX */
&values[79], /* 55 DIGIT SEVEN */
&values[81], /* 56 DIGIT EIGHT */
&values[83], /* 57 DIGIT NINE */
&values[85], /* 58 COLON */
&values[87], /* 59 SEMICOLON */
&values[89], /* 60 LESS-THAN SIGN */
&values[91], /* 61 EQUALS SIGN */
&values[93], /* 62 GREATER-THAN SIGN */
&values[95], /* 63 QUESTION MARK */
&values[97], /* 64 COMMERCIAL AT */
&values[99], /* 65 LATIN CAPITAL LETTER A */
&values[101], /* 66 LATIN CAPITAL LETTER B */
&values[103], /* 67 LATIN CAPITAL LETTER C */
&values[105], /* 68 LATIN CAPITAL LETTER D */
&values[107], /* 69 LATIN CAPITAL LETTER E */
&values[109], /* 70 LATIN CAPITAL LETTER F */
&values[111], /* 71 LATIN CAPITAL LETTER G */
&values[113], /* 72 LATIN CAPITAL LETTER H */
&values[115], /* 73 LATIN CAPITAL LETTER I */
&values[117], /* 74 LATIN CAPITAL LETTER J */
&values[119], /* 75 LATIN CAPITAL LETTER K */
&values[121], /* 76 LATIN CAPITAL LETTER L */
&values[123], /* 77 LATIN CAPITAL LETTER M */
&values[125], /* 78 LATIN CAPITAL LETTER N */
&values[127], /* 79 LATIN CAPITAL LETTER O */
&values[129], /* 80 LATIN CAPITAL LETTER P */
&values[131], /* 81 LATIN CAPITAL LETTER Q */
&values[133], /* 82 LATIN CAPITAL LETTER R */
&values[135], /* 83 LATIN CAPITAL LETTER S */
&values[137], /* 84 LATIN CAPITAL LETTER T */
&values[139], /* 85 LATIN CAPITAL LETTER U */
&values[141], /* 86 LATIN CAPITAL LETTER V */
&values[143], /* 87 LATIN CAPITAL LETTER W */
&values[145], /* 88 LATIN CAPITAL LETTER X */
&values[147], /* 89 LATIN CAPITAL LETTER Y */
&values[149], /* 90 LATIN CAPITAL LETTER Z */
&values[151], /* 91 LEFT SQUARE BRACKET */
&values[153], /* 92 REVERSE SOLIDUS */
&values[155], /* 93 RIGHT SQUARE BRACKET */
&values[157], /* 94 CIRCUMFLEX ACCENT */
&values[159], /* 95 LOW LINE */
&values[161], /* 96 GRAVE ACCENT */
&values[163], /* 97 LATIN SMALL LETTER A */
&values[165], /* 98 LATIN SMALL LETTER B */
&values[167], /* 99 LATIN SMALL LETTER C */
&values[169], /* 100 LATIN SMALL LETTER D */
&values[171], /* 101 LATIN SMALL LETTER E */
&values[173], /* 102 LATIN SMALL LETTER F */
&values[175], /* 103 LATIN SMALL LETTER G */
&values[177], /* 104 LATIN SMALL LETTER H */
&values[179], /* 105 LATIN SMALL LETTER I */
&values[181], /* 106 LATIN SMALL LETTER J */
&values[183], /* 107 LATIN SMALL LETTER K */
&values[185], /* 108 LATIN SMALL LETTER L */
&values[187], /* 109 LATIN SMALL LETTER M */
&values[189], /* 110 LATIN SMALL LETTER N */
&values[191], /* 111 LATIN SMALL LETTER O */
&values[193], /* 112 LATIN SMALL LETTER P */
&values[195], /* 113 LATIN SMALL LETTER Q */
&values[197], /* 114 LATIN SMALL LETTER R */
&values[199], /* 115 LATIN SMALL LETTER S */
&values[201], /* 116 LATIN SMALL LETTER T */
&values[203], /* 117 LATIN SMALL LETTER U */
&values[205], /* 118 LATIN SMALL LETTER V */
&values[207], /* 119 LATIN SMALL LETTER W */
&values[209], /* 120 LATIN SMALL LETTER X */
&values[211], /* 121 LATIN SMALL LETTER Y */
&values[213], /* 122 LATIN SMALL LETTER Z */
&values[215], /* 123 LEFT CURLY BRACKET */
&values[217], /* 124 VERTICAL LINE */
&values[219], /* 125 RIGHT CURLY BRACKET */
&values[221], /* 126 TILDE */
&values[223], /* 127 DELETE */
&values[224], /* 128 EURO SIGN */
&values[226], /* 129 UNDEFINED */
&values[227], /* 130 SINGLE LOW-9 QUOTATION MARK */
&values[229], /* 131 UNDEFINED */
&values[230], /* 132 DOUBLE LOW-9 QUOTATION MARK */
&values[232], /* 133 HORIZONTAL ELLIPSIS */
&values[234], /* 134 DAGGER */
&values[236], /* 135 DOUBLE DAGGER */
&values[238], /* 136 UNDEFINED */
&values[239], /* 137 PER MILLE SIGN */
&values[241], /* 138 UNDEFINED */
&values[242], /* 139 SINGLE LEFT-POINTING ANGLE QUOTATION MARK */
&values[244], /* 140 UNDEFINED */
&values[245], /* 141 DIAERESIS */
&values[247], /* 142 CARON */
&values[249], /* 143 CEDILLA */
&values[251], /* 144 UNDEFINED */
&values[252], /* 145 LEFT SINGLE QUOTATION MARK */
&values[254], /* 146 RIGHT SINGLE QUOTATION MARK */
&values[256], /* 147 LEFT DOUBLE QUOTATION MARK */
&values[258], /* 148 RIGHT DOUBLE QUOTATION MARK */
&values[260], /* 149 BULLET */
&values[262], /* 150 EN DASH */
&values[264], /* 151 EM DASH */
&values[266], /* 152 UNDEFINED */
&values[267], /* 153 TRADE MARK SIGN */
&values[269], /* 154 UNDEFINED */
&values[270], /* 155 SINGLE RIGHT-POINTING ANGLE QUOTATION MARK */
&values[272], /* 156 UNDEFINED */
&values[273], /* 157 MACRON */
&values[275], /* 158 OGONEK */
&values[277], /* 159 UNDEFINED */
&values[278], /* 160 NO-BREAK SPACE */
&values[280], /* 161 UNDEFINED */
&values[281], /* 162 CENT SIGN */
&values[283], /* 163 POUND SIGN */
&values[285], /* 164 CURRENCY SIGN */
&values[287], /* 165 UNDEFINED */
&values[288], /* 166 BROKEN BAR */
&values[290], /* 167 SECTION SIGN */
&values[292], /* 168 LATIN CAPITAL LETTER O WITH STROKE */
&values[294], /* 169 COPYRIGHT SIGN */
&values[296], /* 170 LATIN CAPITAL LETTER R WITH CEDILLA */
&values[298], /* 171 LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[300], /* 172 NOT SIGN */
&values[302], /* 173 SOFT HYPHEN */
&values[304], /* 174 REGISTERED SIGN */
&values[306], /* 175 LATIN CAPITAL LETTER AE */
&values[308], /* 176 DEGREE SIGN */
&values[310], /* 177 PLUS-MINUS SIGN */
&values[312], /* 178 SUPERSCRIPT TWO */
&values[314], /* 179 SUPERSCRIPT THREE */
&values[316], /* 180 ACUTE ACCENT */
&values[318], /* 181 MICRO SIGN */
&values[320], /* 182 PILCROW SIGN */
&values[322], /* 183 MIDDLE DOT */
&values[324], /* 184 LATIN SMALL LETTER O WITH STROKE */
&values[326], /* 185 SUPERSCRIPT ONE */
&values[328], /* 186 LATIN SMALL LETTER R WITH CEDILLA */
&values[330], /* 187 RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[332], /* 188 VULGAR FRACTION ONE QUARTER */
&values[334], /* 189 VULGAR FRACTION ONE HALF */
&values[336], /* 190 VULGAR FRACTION THREE QUARTERS */
&values[338], /* 191 LATIN SMALL LETTER AE */
&values[340], /* 192 LATIN CAPITAL LETTER A WITH OGONEK */
&values[342], /* 193 LATIN CAPITAL LETTER I WITH OGONEK */
&values[344], /* 194 LATIN CAPITAL LETTER A WITH MACRON */
&values[346], /* 195 LATIN CAPITAL LETTER C WITH ACUTE */
&values[348], /* 196 LATIN CAPITAL LETTER A WITH DIAERESIS */
&values[350], /* 197 LATIN CAPITAL LETTER A WITH RING ABOVE */
&values[352], /* 198 LATIN CAPITAL LETTER E WITH OGONEK */
&values[354], /* 199 LATIN CAPITAL LETTER E WITH MACRON */
&values[356], /* 200 LATIN CAPITAL LETTER C WITH CARON */
&values[358], /* 201 LATIN CAPITAL LETTER E WITH ACUTE */
&values[360], /* 202 LATIN CAPITAL LETTER Z WITH ACUTE */
&values[362], /* 203 LATIN CAPITAL LETTER E WITH DOT ABOVE */
&values[364], /* 204 LATIN CAPITAL LETTER G WITH CEDILLA */
&values[366], /* 205 LATIN CAPITAL LETTER K WITH CEDILLA */
&values[368], /* 206 LATIN CAPITAL LETTER I WITH MACRON */
&values[370], /* 207 LATIN CAPITAL LETTER L WITH CEDILLA */
&values[372], /* 208 LATIN CAPITAL LETTER S WITH CARON */
&values[374], /* 209 LATIN CAPITAL LETTER N WITH ACUTE */
&values[376], /* 210 LATIN CAPITAL LETTER N WITH CEDILLA */
&values[378], /* 211 LATIN CAPITAL LETTER O WITH ACUTE */
&values[380], /* 212 LATIN CAPITAL LETTER O WITH MACRON */
&values[382], /* 213 LATIN CAPITAL LETTER O WITH TILDE */
&values[384], /* 214 LATIN CAPITAL LETTER O WITH DIAERESIS */
&values[386], /* 215 MULTIPLICATION SIGN */
&values[388], /* 216 LATIN CAPITAL LETTER U WITH OGONEK */
&values[390], /* 217 LATIN CAPITAL LETTER L WITH STROKE */
&values[392], /* 218 LATIN CAPITAL LETTER S WITH ACUTE */
&values[394], /* 219 LATIN CAPITAL LETTER U WITH MACRON */
&values[396], /* 220 LATIN CAPITAL LETTER U WITH DIAERESIS */
&values[398], /* 221 LATIN CAPITAL LETTER Z WITH DOT ABOVE */
&values[400], /* 222 LATIN CAPITAL LETTER Z WITH CARON */
&values[402], /* 223 LATIN SMALL LETTER SHARP S */
&values[404], /* 224 LATIN SMALL LETTER A WITH OGONEK */
&values[406], /* 225 LATIN SMALL LETTER I WITH OGONEK */
&values[408], /* 226 LATIN SMALL LETTER A WITH MACRON */
&values[410], /* 227 LATIN SMALL LETTER C WITH ACUTE */
&values[412], /* 228 LATIN SMALL LETTER A WITH DIAERESIS */
&values[414], /* 229 LATIN SMALL LETTER A WITH RING ABOVE */
&values[416], /* 230 LATIN SMALL LETTER E WITH OGONEK */
&values[418], /* 231 LATIN SMALL LETTER E WITH MACRON */
&values[420], /* 232 LATIN SMALL LETTER C WITH CARON */
&values[422], /* 233 LATIN SMALL LETTER E WITH ACUTE */
&values[424], /* 234 LATIN SMALL LETTER Z WITH ACUTE */
&values[426], /* 235 LATIN SMALL LETTER E WITH DOT ABOVE */
&values[428], /* 236 LATIN SMALL LETTER G WITH CEDILLA */
&values[430], /* 237 LATIN SMALL LETTER K WITH CEDILLA */
&values[432], /* 238 LATIN SMALL LETTER I WITH MACRON */
&values[434], /* 239 LATIN SMALL LETTER L WITH CEDILLA */
&values[436], /* 240 LATIN SMALL LETTER S WITH CARON */
&values[438], /* 241 LATIN SMALL LETTER N WITH ACUTE */
&values[440], /* 242 LATIN SMALL LETTER N WITH CEDILLA */
&values[442], /* 243 LATIN SMALL LETTER O WITH ACUTE */
&values[444], /* 244 LATIN SMALL LETTER O WITH MACRON */
&values[446], /* 245 LATIN SMALL LETTER O WITH TILDE */
&values[448], /* 246 LATIN SMALL LETTER O WITH DIAERESIS */
&values[450], /* 247 DIVISION SIGN */
&values[452], /* 248 LATIN SMALL LETTER U WITH OGONEK */
&values[454], /* 249 LATIN SMALL LETTER L WITH STROKE */
&values[456], /* 250 LATIN SMALL LETTER S WITH ACUTE */
&values[458], /* 251 LATIN SMALL LETTER U WITH MACRON */
&values[460], /* 252 LATIN SMALL LETTER U WITH DIAERESIS */
&values[462], /* 253 LATIN SMALL LETTER Z WITH DOT ABOVE */
&values[464], /* 254 LATIN SMALL LETTER Z WITH CARON */
&values[466], /* 255 DOT ABOVE */
}};
