/* This file was autogenerated from the file 
 * CP1256.TXT from UNICODE.ORG */

/*     Name:     cp1256 to Unicode table */
/*     Unicode version: 2.1 */
/*     Table version: 2.01 */
/*     Table format:  Format A */
/*     Date:          01/5/99 */
/*     Contact:       cpxlate@microsoft.com */
/*     General notes: none */
/*     Format: Three tab-separated columns */
/*         Column #1 is the cp1256 code (in hex) */
/*         Column #2 is the Unicode (in hex as 0xXXXX) */
/*         Column #3 is the Unicode name (follows a comment sign, '#') */
/*     The entries are in cp1256 order */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0xffff, 
0x20ac, 0xffff, 0x067e, 0xffff, 0x201a, 0xffff, 0x0192, 0xffff, 
0x201e, 0xffff, 0x2026, 0xffff, 0x2020, 0xffff, 0x2021, 0xffff, 
0x02c6, 0xffff, 0x2030, 0xffff, 0x0679, 0xffff, 0x2039, 0xffff, 
0x0152, 0xffff, 0x0686, 0xffff, 0x0698, 0xffff, 0x0688, 0xffff, 
0x06af, 0xffff, 0x2018, 0xffff, 0x2019, 0xffff, 0x201c, 0xffff, 
0x201d, 0xffff, 0x2022, 0xffff, 0x2013, 0xffff, 0x2014, 0xffff, 
0x06a9, 0xffff, 0x2122, 0xffff, 0x0691, 0xffff, 0x203a, 0xffff, 
0x0153, 0xffff, 0x200c, 0xffff, 0x200d, 0xffff, 0x06ba, 0xffff, 
0x00a0, 0xffff, 0x060c, 0xffff, 0x00a2, 0xffff, 0x00a3, 0xffff, 
0x00a4, 0xffff, 0x00a5, 0xffff, 0x00a6, 0xffff, 0x00a7, 0xffff, 
0x00a8, 0xffff, 0x00a9, 0xffff, 0x06be, 0xffff, 0x00ab, 0xffff, 
0x00ac, 0xffff, 0x00ad, 0xffff, 0x00ae, 0xffff, 0x00af, 0xffff, 
0x00b0, 0xffff, 0x00b1, 0xffff, 0x00b2, 0xffff, 0x00b3, 0xffff, 
0x00b4, 0xffff, 0x00b5, 0xffff, 0x00b6, 0xffff, 0x00b7, 0xffff, 
0x00b8, 0xffff, 0x00b9, 0xffff, 0x061b, 0xffff, 0x00bb, 0xffff, 
0x00bc, 0xffff, 0x00bd, 0xffff, 0x00be, 0xffff, 0x061f, 0xffff, 
0x06c1, 0xffff, 0x0621, 0xffff, 0x0622, 0xffff, 0x0623, 0xffff, 
0x0624, 0xffff, 0x0625, 0xffff, 0x0626, 0xffff, 0x0627, 0xffff, 
0x0628, 0xffff, 0x0629, 0xffff, 0x062a, 0xffff, 0x062b, 0xffff, 
0x062c, 0xffff, 0x062d, 0xffff, 0x062e, 0xffff, 0x062f, 0xffff, 
0x0630, 0xffff, 0x0631, 0xffff, 0x0632, 0xffff, 0x0633, 0xffff, 
0x0634, 0xffff, 0x0635, 0xffff, 0x0636, 0xffff, 0x00d7, 0xffff, 
0x0637, 0xffff, 0x0638, 0xffff, 0x0639, 0xffff, 0x063a, 0xffff, 
0x0640, 0xffff, 0x0641, 0xffff, 0x0642, 0xffff, 0x0643, 0xffff, 
0x00e0, 0xffff, 0x0644, 0xffff, 0x00e2, 0xffff, 0x0645, 0xffff, 
0x0646, 0xffff, 0x0647, 0xffff, 0x0648, 0xffff, 0x00e7, 0xffff, 
0x00e8, 0xffff, 0x00e9, 0xffff, 0x00ea, 0xffff, 0x00eb, 0xffff, 
0x0649, 0xffff, 0x064a, 0xffff, 0x00ee, 0xffff, 0x00ef, 0xffff, 
0x064b, 0xffff, 0x064c, 0xffff, 0x064d, 0xffff, 0x064e, 0xffff, 
0x00f4, 0xffff, 0x064f, 0xffff, 0x0650, 0xffff, 0x00f7, 0xffff, 
0x0651, 0xffff, 0x00f9, 0xffff, 0x0652, 0xffff, 0x00fb, 0xffff, 
0x00fc, 0xffff, 0x200e, 0xffff, 0x200f, 0xffff, 0x06d2, 0xffff, 
};

struct psf_mapping256 m_CP1256 = { "CP1256", 
256, {
&values[1], /* 0 NULL */
&values[2], /* 1 START OF HEADING */
&values[3], /* 2 START OF TEXT */
&values[4], /* 3 END OF TEXT */
&values[5], /* 4 END OF TRANSMISSION */
&values[6], /* 5 ENQUIRY */
&values[7], /* 6 ACKNOWLEDGE */
&values[8], /* 7 BELL */
&values[9], /* 8 BACKSPACE */
&values[10], /* 9 HORIZONTAL TABULATION */
&values[11], /* 10 LINE FEED */
&values[12], /* 11 VERTICAL TABULATION */
&values[13], /* 12 FORM FEED */
&values[14], /* 13 CARRIAGE RETURN */
&values[15], /* 14 SHIFT OUT */
&values[16], /* 15 SHIFT IN */
&values[17], /* 16 DATA LINK ESCAPE */
&values[18], /* 17 DEVICE CONTROL ONE */
&values[19], /* 18 DEVICE CONTROL TWO */
&values[20], /* 19 DEVICE CONTROL THREE */
&values[21], /* 20 DEVICE CONTROL FOUR */
&values[22], /* 21 NEGATIVE ACKNOWLEDGE */
&values[23], /* 22 SYNCHRONOUS IDLE */
&values[24], /* 23 END OF TRANSMISSION BLOCK */
&values[25], /* 24 CANCEL */
&values[26], /* 25 END OF MEDIUM */
&values[27], /* 26 SUBSTITUTE */
&values[28], /* 27 ESCAPE */
&values[29], /* 28 FILE SEPARATOR */
&values[30], /* 29 GROUP SEPARATOR */
&values[31], /* 30 RECORD SEPARATOR */
&values[32], /* 31 UNIT SEPARATOR */
&values[33], /* 32 SPACE */
&values[35], /* 33 EXCLAMATION MARK */
&values[37], /* 34 QUOTATION MARK */
&values[39], /* 35 NUMBER SIGN */
&values[41], /* 36 DOLLAR SIGN */
&values[43], /* 37 PERCENT SIGN */
&values[45], /* 38 AMPERSAND */
&values[47], /* 39 APOSTROPHE */
&values[49], /* 40 LEFT PARENTHESIS */
&values[51], /* 41 RIGHT PARENTHESIS */
&values[53], /* 42 ASTERISK */
&values[55], /* 43 PLUS SIGN */
&values[57], /* 44 COMMA */
&values[59], /* 45 HYPHEN-MINUS */
&values[61], /* 46 FULL STOP */
&values[63], /* 47 SOLIDUS */
&values[65], /* 48 DIGIT ZERO */
&values[67], /* 49 DIGIT ONE */
&values[69], /* 50 DIGIT TWO */
&values[71], /* 51 DIGIT THREE */
&values[73], /* 52 DIGIT FOUR */
&values[75], /* 53 DIGIT FIVE */
&values[77], /* 54 DIGIT SIX */
&values[79], /* 55 DIGIT SEVEN */
&values[81], /* 56 DIGIT EIGHT */
&values[83], /* 57 DIGIT NINE */
&values[85], /* 58 COLON */
&values[87], /* 59 SEMICOLON */
&values[89], /* 60 LESS-THAN SIGN */
&values[91], /* 61 EQUALS SIGN */
&values[93], /* 62 GREATER-THAN SIGN */
&values[95], /* 63 QUESTION MARK */
&values[97], /* 64 COMMERCIAL AT */
&values[99], /* 65 LATIN CAPITAL LETTER A */
&values[101], /* 66 LATIN CAPITAL LETTER B */
&values[103], /* 67 LATIN CAPITAL LETTER C */
&values[105], /* 68 LATIN CAPITAL LETTER D */
&values[107], /* 69 LATIN CAPITAL LETTER E */
&values[109], /* 70 LATIN CAPITAL LETTER F */
&values[111], /* 71 LATIN CAPITAL LETTER G */
&values[113], /* 72 LATIN CAPITAL LETTER H */
&values[115], /* 73 LATIN CAPITAL LETTER I */
&values[117], /* 74 LATIN CAPITAL LETTER J */
&values[119], /* 75 LATIN CAPITAL LETTER K */
&values[121], /* 76 LATIN CAPITAL LETTER L */
&values[123], /* 77 LATIN CAPITAL LETTER M */
&values[125], /* 78 LATIN CAPITAL LETTER N */
&values[127], /* 79 LATIN CAPITAL LETTER O */
&values[129], /* 80 LATIN CAPITAL LETTER P */
&values[131], /* 81 LATIN CAPITAL LETTER Q */
&values[133], /* 82 LATIN CAPITAL LETTER R */
&values[135], /* 83 LATIN CAPITAL LETTER S */
&values[137], /* 84 LATIN CAPITAL LETTER T */
&values[139], /* 85 LATIN CAPITAL LETTER U */
&values[141], /* 86 LATIN CAPITAL LETTER V */
&values[143], /* 87 LATIN CAPITAL LETTER W */
&values[145], /* 88 LATIN CAPITAL LETTER X */
&values[147], /* 89 LATIN CAPITAL LETTER Y */
&values[149], /* 90 LATIN CAPITAL LETTER Z */
&values[151], /* 91 LEFT SQUARE BRACKET */
&values[153], /* 92 REVERSE SOLIDUS */
&values[155], /* 93 RIGHT SQUARE BRACKET */
&values[157], /* 94 CIRCUMFLEX ACCENT */
&values[159], /* 95 LOW LINE */
&values[161], /* 96 GRAVE ACCENT */
&values[163], /* 97 LATIN SMALL LETTER A */
&values[165], /* 98 LATIN SMALL LETTER B */
&values[167], /* 99 LATIN SMALL LETTER C */
&values[169], /* 100 LATIN SMALL LETTER D */
&values[171], /* 101 LATIN SMALL LETTER E */
&values[173], /* 102 LATIN SMALL LETTER F */
&values[175], /* 103 LATIN SMALL LETTER G */
&values[177], /* 104 LATIN SMALL LETTER H */
&values[179], /* 105 LATIN SMALL LETTER I */
&values[181], /* 106 LATIN SMALL LETTER J */
&values[183], /* 107 LATIN SMALL LETTER K */
&values[185], /* 108 LATIN SMALL LETTER L */
&values[187], /* 109 LATIN SMALL LETTER M */
&values[189], /* 110 LATIN SMALL LETTER N */
&values[191], /* 111 LATIN SMALL LETTER O */
&values[193], /* 112 LATIN SMALL LETTER P */
&values[195], /* 113 LATIN SMALL LETTER Q */
&values[197], /* 114 LATIN SMALL LETTER R */
&values[199], /* 115 LATIN SMALL LETTER S */
&values[201], /* 116 LATIN SMALL LETTER T */
&values[203], /* 117 LATIN SMALL LETTER U */
&values[205], /* 118 LATIN SMALL LETTER V */
&values[207], /* 119 LATIN SMALL LETTER W */
&values[209], /* 120 LATIN SMALL LETTER X */
&values[211], /* 121 LATIN SMALL LETTER Y */
&values[213], /* 122 LATIN SMALL LETTER Z */
&values[215], /* 123 LEFT CURLY BRACKET */
&values[217], /* 124 VERTICAL LINE */
&values[219], /* 125 RIGHT CURLY BRACKET */
&values[221], /* 126 TILDE */
&values[223], /* 127 DELETE */
&values[224], /* 128 EURO SIGN */
&values[226], /* 129 ARABIC LETTER PEH */
&values[228], /* 130 SINGLE LOW-9 QUOTATION MARK */
&values[230], /* 131 LATIN SMALL LETTER F WITH HOOK */
&values[232], /* 132 DOUBLE LOW-9 QUOTATION MARK */
&values[234], /* 133 HORIZONTAL ELLIPSIS */
&values[236], /* 134 DAGGER */
&values[238], /* 135 DOUBLE DAGGER */
&values[240], /* 136 MODIFIER LETTER CIRCUMFLEX ACCENT */
&values[242], /* 137 PER MILLE SIGN */
&values[244], /* 138 ARABIC LETTER TTEH */
&values[246], /* 139 SINGLE LEFT-POINTING ANGLE QUOTATION MARK */
&values[248], /* 140 LATIN CAPITAL LIGATURE OE */
&values[250], /* 141 ARABIC LETTER TCHEH */
&values[252], /* 142 ARABIC LETTER JEH */
&values[254], /* 143 ARABIC LETTER DDAL */
&values[256], /* 144 ARABIC LETTER GAF */
&values[258], /* 145 LEFT SINGLE QUOTATION MARK */
&values[260], /* 146 RIGHT SINGLE QUOTATION MARK */
&values[262], /* 147 LEFT DOUBLE QUOTATION MARK */
&values[264], /* 148 RIGHT DOUBLE QUOTATION MARK */
&values[266], /* 149 BULLET */
&values[268], /* 150 EN DASH */
&values[270], /* 151 EM DASH */
&values[272], /* 152 ARABIC LETTER KEHEH */
&values[274], /* 153 TRADE MARK SIGN */
&values[276], /* 154 ARABIC LETTER RREH */
&values[278], /* 155 SINGLE RIGHT-POINTING ANGLE QUOTATION MARK */
&values[280], /* 156 LATIN SMALL LIGATURE OE */
&values[282], /* 157 ZERO WIDTH NON-JOINER */
&values[284], /* 158 ZERO WIDTH JOINER */
&values[286], /* 159 ARABIC LETTER NOON GHUNNA */
&values[288], /* 160 NO-BREAK SPACE */
&values[290], /* 161 ARABIC COMMA */
&values[292], /* 162 CENT SIGN */
&values[294], /* 163 POUND SIGN */
&values[296], /* 164 CURRENCY SIGN */
&values[298], /* 165 YEN SIGN */
&values[300], /* 166 BROKEN BAR */
&values[302], /* 167 SECTION SIGN */
&values[304], /* 168 DIAERESIS */
&values[306], /* 169 COPYRIGHT SIGN */
&values[308], /* 170 ARABIC LETTER HEH DOACHASHMEE */
&values[310], /* 171 LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[312], /* 172 NOT SIGN */
&values[314], /* 173 SOFT HYPHEN */
&values[316], /* 174 REGISTERED SIGN */
&values[318], /* 175 MACRON */
&values[320], /* 176 DEGREE SIGN */
&values[322], /* 177 PLUS-MINUS SIGN */
&values[324], /* 178 SUPERSCRIPT TWO */
&values[326], /* 179 SUPERSCRIPT THREE */
&values[328], /* 180 ACUTE ACCENT */
&values[330], /* 181 MICRO SIGN */
&values[332], /* 182 PILCROW SIGN */
&values[334], /* 183 MIDDLE DOT */
&values[336], /* 184 CEDILLA */
&values[338], /* 185 SUPERSCRIPT ONE */
&values[340], /* 186 ARABIC SEMICOLON */
&values[342], /* 187 RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[344], /* 188 VULGAR FRACTION ONE QUARTER */
&values[346], /* 189 VULGAR FRACTION ONE HALF */
&values[348], /* 190 VULGAR FRACTION THREE QUARTERS */
&values[350], /* 191 ARABIC QUESTION MARK */
&values[352], /* 192 ARABIC LETTER HEH GOAL */
&values[354], /* 193 ARABIC LETTER HAMZA */
&values[356], /* 194 ARABIC LETTER ALEF WITH MADDA ABOVE */
&values[358], /* 195 ARABIC LETTER ALEF WITH HAMZA ABOVE */
&values[360], /* 196 ARABIC LETTER WAW WITH HAMZA ABOVE */
&values[362], /* 197 ARABIC LETTER ALEF WITH HAMZA BELOW */
&values[364], /* 198 ARABIC LETTER YEH WITH HAMZA ABOVE */
&values[366], /* 199 ARABIC LETTER ALEF */
&values[368], /* 200 ARABIC LETTER BEH */
&values[370], /* 201 ARABIC LETTER TEH MARBUTA */
&values[372], /* 202 ARABIC LETTER TEH */
&values[374], /* 203 ARABIC LETTER THEH */
&values[376], /* 204 ARABIC LETTER JEEM */
&values[378], /* 205 ARABIC LETTER HAH */
&values[380], /* 206 ARABIC LETTER KHAH */
&values[382], /* 207 ARABIC LETTER DAL */
&values[384], /* 208 ARABIC LETTER THAL */
&values[386], /* 209 ARABIC LETTER REH */
&values[388], /* 210 ARABIC LETTER ZAIN */
&values[390], /* 211 ARABIC LETTER SEEN */
&values[392], /* 212 ARABIC LETTER SHEEN */
&values[394], /* 213 ARABIC LETTER SAD */
&values[396], /* 214 ARABIC LETTER DAD */
&values[398], /* 215 MULTIPLICATION SIGN */
&values[400], /* 216 ARABIC LETTER TAH */
&values[402], /* 217 ARABIC LETTER ZAH */
&values[404], /* 218 ARABIC LETTER AIN */
&values[406], /* 219 ARABIC LETTER GHAIN */
&values[408], /* 220 ARABIC TATWEEL */
&values[410], /* 221 ARABIC LETTER FEH */
&values[412], /* 222 ARABIC LETTER QAF */
&values[414], /* 223 ARABIC LETTER KAF */
&values[416], /* 224 LATIN SMALL LETTER A WITH GRAVE */
&values[418], /* 225 ARABIC LETTER LAM */
&values[420], /* 226 LATIN SMALL LETTER A WITH CIRCUMFLEX */
&values[422], /* 227 ARABIC LETTER MEEM */
&values[424], /* 228 ARABIC LETTER NOON */
&values[426], /* 229 ARABIC LETTER HEH */
&values[428], /* 230 ARABIC LETTER WAW */
&values[430], /* 231 LATIN SMALL LETTER C WITH CEDILLA */
&values[432], /* 232 LATIN SMALL LETTER E WITH GRAVE */
&values[434], /* 233 LATIN SMALL LETTER E WITH ACUTE */
&values[436], /* 234 LATIN SMALL LETTER E WITH CIRCUMFLEX */
&values[438], /* 235 LATIN SMALL LETTER E WITH DIAERESIS */
&values[440], /* 236 ARABIC LETTER ALEF MAKSURA */
&values[442], /* 237 ARABIC LETTER YEH */
&values[444], /* 238 LATIN SMALL LETTER I WITH CIRCUMFLEX */
&values[446], /* 239 LATIN SMALL LETTER I WITH DIAERESIS */
&values[448], /* 240 ARABIC FATHATAN */
&values[450], /* 241 ARABIC DAMMATAN */
&values[452], /* 242 ARABIC KASRATAN */
&values[454], /* 243 ARABIC FATHA */
&values[456], /* 244 LATIN SMALL LETTER O WITH CIRCUMFLEX */
&values[458], /* 245 ARABIC DAMMA */
&values[460], /* 246 ARABIC KASRA */
&values[462], /* 247 DIVISION SIGN */
&values[464], /* 248 ARABIC SHADDA */
&values[466], /* 249 LATIN SMALL LETTER U WITH GRAVE */
&values[468], /* 250 ARABIC SUKUN */
&values[470], /* 251 LATIN SMALL LETTER U WITH CIRCUMFLEX */
&values[472], /* 252 LATIN SMALL LETTER U WITH DIAERESIS */
&values[474], /* 253 LEFT-TO-RIGHT MARK */
&values[476], /* 254 RIGHT-TO-LEFT MARK */
&values[478], /* 255 ARABIC LETTER YEH BARREE */
}};
