/* This file was autogenerated from the Unicode mapping 
 * table CP367.uni in the format used by the Linux kbd package */

/*  Unicode table for IBM Codepage 367. This is just plain ASCII - no  */
/*  glyphs outside the range 0x20-0x7e, and an identity mapping inside that */
/*  range. */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, };

struct psf_mapping256 m_CP367 = { "CP367",
127, {
&values[0], /* 0  */
&values[0], /* 1  */
&values[0], /* 2  */
&values[0], /* 3  */
&values[0], /* 4  */
&values[0], /* 5  */
&values[0], /* 6  */
&values[0], /* 7  */
&values[0], /* 8  */
&values[0], /* 9  */
&values[0], /* 10  */
&values[0], /* 11  */
&values[0], /* 12  */
&values[0], /* 13  */
&values[0], /* 14  */
&values[0], /* 15  */
&values[0], /* 16  */
&values[0], /* 17  */
&values[0], /* 18  */
&values[0], /* 19  */
&values[0], /* 20  */
&values[0], /* 21  */
&values[0], /* 22  */
&values[0], /* 23  */
&values[0], /* 24  */
&values[0], /* 25  */
&values[0], /* 26  */
&values[0], /* 27  */
&values[0], /* 28  */
&values[0], /* 29  */
&values[0], /* 30  */
&values[0], /* 31  */
&values[1], /* 32  */
&values[3], /* 33  */
&values[5], /* 34  */
&values[7], /* 35  */
&values[9], /* 36  */
&values[11], /* 37  */
&values[13], /* 38  */
&values[15], /* 39  */
&values[17], /* 40  */
&values[19], /* 41  */
&values[21], /* 42  */
&values[23], /* 43  */
&values[25], /* 44  */
&values[27], /* 45  */
&values[29], /* 46  */
&values[31], /* 47  */
&values[33], /* 48  */
&values[35], /* 49  */
&values[37], /* 50  */
&values[39], /* 51  */
&values[41], /* 52  */
&values[43], /* 53  */
&values[45], /* 54  */
&values[47], /* 55  */
&values[49], /* 56  */
&values[51], /* 57  */
&values[53], /* 58  */
&values[55], /* 59  */
&values[57], /* 60  */
&values[59], /* 61  */
&values[61], /* 62  */
&values[63], /* 63  */
&values[65], /* 64  */
&values[67], /* 65  */
&values[69], /* 66  */
&values[71], /* 67  */
&values[73], /* 68  */
&values[75], /* 69  */
&values[77], /* 70  */
&values[79], /* 71  */
&values[81], /* 72  */
&values[83], /* 73  */
&values[85], /* 74  */
&values[87], /* 75  */
&values[89], /* 76  */
&values[91], /* 77  */
&values[93], /* 78  */
&values[95], /* 79  */
&values[97], /* 80  */
&values[99], /* 81  */
&values[101], /* 82  */
&values[103], /* 83  */
&values[105], /* 84  */
&values[107], /* 85  */
&values[109], /* 86  */
&values[111], /* 87  */
&values[113], /* 88  */
&values[115], /* 89  */
&values[117], /* 90  */
&values[119], /* 91  */
&values[121], /* 92  */
&values[123], /* 93  */
&values[125], /* 94  */
&values[127], /* 95  */
&values[129], /* 96  */
&values[131], /* 97  */
&values[133], /* 98  */
&values[135], /* 99  */
&values[137], /* 100  */
&values[139], /* 101  */
&values[141], /* 102  */
&values[143], /* 103  */
&values[145], /* 104  */
&values[147], /* 105  */
&values[149], /* 106  */
&values[151], /* 107  */
&values[153], /* 108  */
&values[155], /* 109  */
&values[157], /* 110  */
&values[159], /* 111  */
&values[161], /* 112  */
&values[163], /* 113  */
&values[165], /* 114  */
&values[167], /* 115  */
&values[169], /* 116  */
&values[171], /* 117  */
&values[173], /* 118  */
&values[175], /* 119  */
&values[177], /* 120  */
&values[179], /* 121  */
&values[181], /* 122  */
&values[183], /* 123  */
&values[185], /* 124  */
&values[187], /* 125  */
&values[189], /* 126  */
&values[0], /* 127  */
&values[0], /* 128  */
&values[0], /* 129  */
&values[0], /* 130  */
&values[0], /* 131  */
&values[0], /* 132  */
&values[0], /* 133  */
&values[0], /* 134  */
&values[0], /* 135  */
&values[0], /* 136  */
&values[0], /* 137  */
&values[0], /* 138  */
&values[0], /* 139  */
&values[0], /* 140  */
&values[0], /* 141  */
&values[0], /* 142  */
&values[0], /* 143  */
&values[0], /* 144  */
&values[0], /* 145  */
&values[0], /* 146  */
&values[0], /* 147  */
&values[0], /* 148  */
&values[0], /* 149  */
&values[0], /* 150  */
&values[0], /* 151  */
&values[0], /* 152  */
&values[0], /* 153  */
&values[0], /* 154  */
&values[0], /* 155  */
&values[0], /* 156  */
&values[0], /* 157  */
&values[0], /* 158  */
&values[0], /* 159  */
&values[0], /* 160  */
&values[0], /* 161  */
&values[0], /* 162  */
&values[0], /* 163  */
&values[0], /* 164  */
&values[0], /* 165  */
&values[0], /* 166  */
&values[0], /* 167  */
&values[0], /* 168  */
&values[0], /* 169  */
&values[0], /* 170  */
&values[0], /* 171  */
&values[0], /* 172  */
&values[0], /* 173  */
&values[0], /* 174  */
&values[0], /* 175  */
&values[0], /* 176  */
&values[0], /* 177  */
&values[0], /* 178  */
&values[0], /* 179  */
&values[0], /* 180  */
&values[0], /* 181  */
&values[0], /* 182  */
&values[0], /* 183  */
&values[0], /* 184  */
&values[0], /* 185  */
&values[0], /* 186  */
&values[0], /* 187  */
&values[0], /* 188  */
&values[0], /* 189  */
&values[0], /* 190  */
&values[0], /* 191  */
&values[0], /* 192  */
&values[0], /* 193  */
&values[0], /* 194  */
&values[0], /* 195  */
&values[0], /* 196  */
&values[0], /* 197  */
&values[0], /* 198  */
&values[0], /* 199  */
&values[0], /* 200  */
&values[0], /* 201  */
&values[0], /* 202  */
&values[0], /* 203  */
&values[0], /* 204  */
&values[0], /* 205  */
&values[0], /* 206  */
&values[0], /* 207  */
&values[0], /* 208  */
&values[0], /* 209  */
&values[0], /* 210  */
&values[0], /* 211  */
&values[0], /* 212  */
&values[0], /* 213  */
&values[0], /* 214  */
&values[0], /* 215  */
&values[0], /* 216  */
&values[0], /* 217  */
&values[0], /* 218  */
&values[0], /* 219  */
&values[0], /* 220  */
&values[0], /* 221  */
&values[0], /* 222  */
&values[0], /* 223  */
&values[0], /* 224  */
&values[0], /* 225  */
&values[0], /* 226  */
&values[0], /* 227  */
&values[0], /* 228  */
&values[0], /* 229  */
&values[0], /* 230  */
&values[0], /* 231  */
&values[0], /* 232  */
&values[0], /* 233  */
&values[0], /* 234  */
&values[0], /* 235  */
&values[0], /* 236  */
&values[0], /* 237  */
&values[0], /* 238  */
&values[0], /* 239  */
&values[0], /* 240  */
&values[0], /* 241  */
&values[0], /* 242  */
&values[0], /* 243  */
&values[0], /* 244  */
&values[0], /* 245  */
&values[0], /* 246  */
&values[0], /* 247  */
&values[0], /* 248  */
&values[0], /* 249  */
&values[0], /* 250  */
&values[0], /* 251  */
&values[0], /* 252  */
&values[0], /* 253  */
&values[0], /* 254  */
&values[0], /* 255  */
}};
