/* This file was autogenerated from the Unicode mapping 
 * table cp858.uni in the format used by the Linux kbd package */

/*  Modified by John Elliott to have CP437-style glyphs rather than control */
/*  codes - see cp437. */
/*  CP858 */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0x0000, 0xffff, 0x263a, 0xffff, 0x263b, 0xffff, 0x2665, 
0xffff, 0x2666, 0x25c6, 0xffff, 0x2663, 0xffff, 0x2660, 0xffff, 
0x2022, 0xffff, 0x25d8, 0xffff, 0x25cb, 0xffff, 0x25d9, 0xffff, 
0x2642, 0xffff, 0x2640, 0xffff, 0x266a, 0xffff, 0x266b, 0xffff, 
0x263c, 0xffff, 0x25b6, 0x25ba, 0xffff, 0x25c0, 0x25c4, 0xffff, 
0x2195, 0xffff, 0x203c, 0xffff, 0x00b6, 0xffff, 0x00a7, 0xffff, 
0x25ac, 0xffff, 0x21a8, 0xffff, 0x2191, 0xffff, 0x2193, 0xffff, 
0x2192, 0xffff, 0x2190, 0xffff, 0x221f, 0xffff, 0x2194, 0xffff, 
0x25b2, 0xffff, 0x25bc, 0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 
0x0022, 0xffff, 0x0023, 0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 
0x0026, 0xffff, 0x0027, 0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 
0x002a, 0xffff, 0x002b, 0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 
0x002e, 0xffff, 0x002f, 0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 
0x0032, 0xffff, 0x0033, 0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 
0x0036, 0xffff, 0x0037, 0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 
0x003a, 0xffff, 0x003b, 0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 
0x003e, 0xffff, 0x003f, 0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 
0x0042, 0xffff, 0x0043, 0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 
0x0046, 0xffff, 0x0047, 0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 
0x004a, 0xffff, 0x004b, 0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 
0x004e, 0xffff, 0x004f, 0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 
0x0052, 0xffff, 0x0053, 0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 
0x0056, 0xffff, 0x0057, 0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 
0x005a, 0xffff, 0x005b, 0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 
0x005e, 0xffff, 0x005f, 0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 
0x0062, 0xffff, 0x0063, 0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 
0x0066, 0xffff, 0x0067, 0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 
0x006a, 0xffff, 0x006b, 0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 
0x006e, 0xffff, 0x006f, 0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 
0x0072, 0xffff, 0x0073, 0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 
0x0076, 0xffff, 0x0077, 0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 
0x007a, 0xffff, 0x007b, 0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 
0x007e, 0xffff, 0x2302, 0xffff, 0x00c7, 0xffff, 0x00fc, 0xffff, 
0x00e9, 0xffff, 0x00e2, 0xffff, 0x00e4, 0xffff, 0x00e0, 0xffff, 
0x00e5, 0xffff, 0x00e7, 0xffff, 0x00ea, 0xffff, 0x00eb, 0xffff, 
0x00e8, 0xffff, 0x00ef, 0xffff, 0x00ee, 0xffff, 0x00ec, 0xffff, 
0x00c4, 0xffff, 0x00c5, 0xffff, 0x00c9, 0xffff, 0x00e6, 0xffff, 
0x00c6, 0xffff, 0x00f4, 0xffff, 0x00f6, 0xffff, 0x00f2, 0xffff, 
0x00fb, 0xffff, 0x00f9, 0xffff, 0x00ff, 0xffff, 0x00d6, 0xffff, 
0x00dc, 0xffff, 0x00f8, 0xffff, 0x00a3, 0xffff, 0x00d8, 0xffff, 
0x00d7, 0xffff, 0x0192, 0xffff, 0x00e1, 0xffff, 0x00ed, 0xffff, 
0x00f3, 0xffff, 0x00fa, 0xffff, 0x00f1, 0xffff, 0x00d1, 0xffff, 
0x00aa, 0xffff, 0x00ba, 0xffff, 0x00bf, 0xffff, 0x00ae, 0xffff, 
0x00ac, 0xffff, 0x00bd, 0xffff, 0x00bc, 0xffff, 0x00a1, 0xffff, 
0x00ab, 0xffff, 0x00bb, 0xffff, 0x2591, 0xffff, 0x2592, 0xffff, 
0x2593, 0xffff, 0x2502, 0xffff, 0x2524, 0xffff, 0x00c1, 0xffff, 
0x00c2, 0xffff, 0x00c0, 0xffff, 0x00a9, 0xffff, 0x2563, 0xffff, 
0x2551, 0xffff, 0x2557, 0xffff, 0x255d, 0xffff, 0x00a2, 0xffff, 
0x00a5, 0xffff, 0x2510, 0xffff, 0x2514, 0xffff, 0x2534, 0xffff, 
0x252c, 0xffff, 0x251c, 0xffff, 0x2500, 0xffff, 0x253c, 0xffff, 
0x00e3, 0xffff, 0x00c3, 0xffff, 0x255a, 0xffff, 0x2554, 0xffff, 
0x2569, 0xffff, 0x2566, 0xffff, 0x2560, 0xffff, 0x2550, 0xffff, 
0x256c, 0xffff, 0x00a4, 0xffff, 0x00f0, 0xffff, 0x00d0, 0xffff, 
0x00ca, 0xffff, 0x00cb, 0xffff, 0x00c8, 0xffff, 0x20ac, 0xffff, 
0x00cd, 0xffff, 0x00ce, 0xffff, 0x00cf, 0xffff, 0x2518, 0xffff, 
0x250c, 0xffff, 0x2588, 0xffff, 0x2584, 0xffff, 0x00a6, 0xffff, 
0x00cc, 0xffff, 0x2580, 0xffff, 0x00d3, 0xffff, 0x00df, 0xffff, 
0x00d4, 0xffff, 0x00d2, 0xffff, 0x00f5, 0xffff, 0x00d5, 0xffff, 
0x00b5, 0xffff, 0x00fe, 0xffff, 0x00de, 0xffff, 0x00da, 0xffff, 
0x00db, 0xffff, 0x00d9, 0xffff, 0x00fd, 0xffff, 0x00dd, 0xffff, 
0x00af, 0xffff, 0x00b4, 0xffff, 0x00ad, 0xffff, 0x00b1, 0xffff, 
0x2017, 0xffff, 0x00be, 0xffff, 0x00b6, 0xffff, 0x00a7, 0xffff, 
0x00f7, 0xffff, 0x00b8, 0xffff, 0x00b0, 0xffff, 0x00a8, 0xffff, 
0x00b7, 0xffff, 0x00b9, 0xffff, 0x00b3, 0xffff, 0x00b2, 0xffff, 
0x25a0, 0xffff, 0x00a0, 0xffff, };

struct psf_mapping256 m_CP858 = { "CP858",
256, {
&values[1], /* 0  */
&values[3], /* 1  */
&values[5], /* 2  */
&values[7], /* 3  */
&values[9], /* 4  */
&values[12], /* 5  */
&values[14], /* 6  */
&values[16], /* 7  */
&values[18], /* 8  */
&values[20], /* 9  */
&values[22], /* 10  */
&values[24], /* 11  */
&values[26], /* 12  */
&values[28], /* 13  */
&values[30], /* 14  */
&values[32], /* 15  */
&values[34], /* 16  */
&values[37], /* 17  */
&values[40], /* 18  */
&values[42], /* 19  */
&values[44], /* 20  */
&values[46], /* 21  */
&values[48], /* 22  */
&values[50], /* 23  */
&values[52], /* 24  */
&values[54], /* 25  */
&values[56], /* 26  */
&values[58], /* 27  */
&values[60], /* 28  */
&values[62], /* 29  */
&values[64], /* 30  */
&values[66], /* 31  */
&values[68], /* 32  */
&values[70], /* 33  */
&values[72], /* 34  */
&values[74], /* 35  */
&values[76], /* 36  */
&values[78], /* 37  */
&values[80], /* 38  */
&values[82], /* 39  */
&values[84], /* 40  */
&values[86], /* 41  */
&values[88], /* 42  */
&values[90], /* 43  */
&values[92], /* 44  */
&values[94], /* 45  */
&values[96], /* 46  */
&values[98], /* 47  */
&values[100], /* 48  */
&values[102], /* 49  */
&values[104], /* 50  */
&values[106], /* 51  */
&values[108], /* 52  */
&values[110], /* 53  */
&values[112], /* 54  */
&values[114], /* 55  */
&values[116], /* 56  */
&values[118], /* 57  */
&values[120], /* 58  */
&values[122], /* 59  */
&values[124], /* 60  */
&values[126], /* 61  */
&values[128], /* 62  */
&values[130], /* 63  */
&values[132], /* 64  */
&values[134], /* 65  */
&values[136], /* 66  */
&values[138], /* 67  */
&values[140], /* 68  */
&values[142], /* 69  */
&values[144], /* 70  */
&values[146], /* 71  */
&values[148], /* 72  */
&values[150], /* 73  */
&values[152], /* 74  */
&values[154], /* 75  */
&values[156], /* 76  */
&values[158], /* 77  */
&values[160], /* 78  */
&values[162], /* 79  */
&values[164], /* 80  */
&values[166], /* 81  */
&values[168], /* 82  */
&values[170], /* 83  */
&values[172], /* 84  */
&values[174], /* 85  */
&values[176], /* 86  */
&values[178], /* 87  */
&values[180], /* 88  */
&values[182], /* 89  */
&values[184], /* 90  */
&values[186], /* 91  */
&values[188], /* 92  */
&values[190], /* 93  */
&values[192], /* 94  */
&values[194], /* 95  */
&values[196], /* 96  */
&values[198], /* 97  */
&values[200], /* 98  */
&values[202], /* 99  */
&values[204], /* 100  */
&values[206], /* 101  */
&values[208], /* 102  */
&values[210], /* 103  */
&values[212], /* 104  */
&values[214], /* 105  */
&values[216], /* 106  */
&values[218], /* 107  */
&values[220], /* 108  */
&values[222], /* 109  */
&values[224], /* 110  */
&values[226], /* 111  */
&values[228], /* 112  */
&values[230], /* 113  */
&values[232], /* 114  */
&values[234], /* 115  */
&values[236], /* 116  */
&values[238], /* 117  */
&values[240], /* 118  */
&values[242], /* 119  */
&values[244], /* 120  */
&values[246], /* 121  */
&values[248], /* 122  */
&values[250], /* 123  */
&values[252], /* 124  */
&values[254], /* 125  */
&values[256], /* 126  */
&values[258], /* 127  */
&values[260], /* 128  LATIN CAPITAL LETTER C WITH CEDILLA */
&values[262], /* 129  LATIN SMALL LETTER U WITH DIAERESIS */
&values[264], /* 130  LATIN SMALL LETTER E WITH ACUTE */
&values[266], /* 131  LATIN SMALL LETTER A WITH CIRCUMFLEX */
&values[268], /* 132  LATIN SMALL LETTER A WITH DIAERESIS */
&values[270], /* 133  LATIN SMALL LETTER A WITH GRAVE */
&values[272], /* 134  LATIN SMALL LETTER A WITH RING ABOVE */
&values[274], /* 135  LATIN SMALL LETTER C WITH CEDILLA */
&values[276], /* 136  LATIN SMALL LETTER E WITH CIRCUMFLEX */
&values[278], /* 137  LATIN SMALL LETTER E WITH DIAERESIS */
&values[280], /* 138  LATIN SMALL LETTER E WITH GRAVE */
&values[282], /* 139  LATIN SMALL LETTER I WITH DIAERESIS */
&values[284], /* 140  LATIN SMALL LETTER I WITH CIRCUMFLEX */
&values[286], /* 141  LATIN SMALL LETTER I WITH GRAVE */
&values[288], /* 142  LATIN CAPITAL LETTER A WITH DIAERESIS */
&values[290], /* 143  LATIN CAPITAL LETTER A WITH RING ABOVE */
&values[292], /* 144  LATIN CAPITAL LETTER E WITH ACUTE */
&values[294], /* 145  LATIN SMALL LIGATURE AE */
&values[296], /* 146  LATIN CAPITAL LIGATURE AE */
&values[298], /* 147  LATIN SMALL LETTER O WITH CIRCUMFLEX */
&values[300], /* 148  LATIN SMALL LETTER O WITH DIAERESIS */
&values[302], /* 149  LATIN SMALL LETTER O WITH GRAVE */
&values[304], /* 150  LATIN SMALL LETTER U WITH CIRCUMFLEX */
&values[306], /* 151  LATIN SMALL LETTER U WITH GRAVE */
&values[308], /* 152  LATIN SMALL LETTER Y WITH DIAERESIS */
&values[310], /* 153  LATIN CAPITAL LETTER O WITH DIAERESIS */
&values[312], /* 154  LATIN CAPITAL LETTER U WITH DIAERESIS */
&values[314], /* 155  LATIN SMALL LETTER O WITH STROKE */
&values[316], /* 156  POUND SIGN */
&values[318], /* 157  LATIN CAPITAL LETTER O WITH STROKE */
&values[320], /* 158  MULTIPLICATION SIGN */
&values[322], /* 159  LATIN SMALL LETTER F WITH HOOK */
&values[324], /* 160  LATIN SMALL LETTER A WITH ACUTE */
&values[326], /* 161  LATIN SMALL LETTER I WITH ACUTE */
&values[328], /* 162  LATIN SMALL LETTER O WITH ACUTE */
&values[330], /* 163  LATIN SMALL LETTER U WITH ACUTE */
&values[332], /* 164  LATIN SMALL LETTER N WITH TILDE */
&values[334], /* 165  LATIN CAPITAL LETTER N WITH TILDE */
&values[336], /* 166  FEMININE ORDINAL INDICATOR */
&values[338], /* 167  MASCULINE ORDINAL INDICATOR */
&values[340], /* 168  INVERTED QUESTION MARK */
&values[342], /* 169  REGISTERED SIGN */
&values[344], /* 170  NOT SIGN */
&values[346], /* 171  VULGAR FRACTION ONE HALF */
&values[348], /* 172  VULGAR FRACTION ONE QUARTER */
&values[350], /* 173  INVERTED EXCLAMATION MARK */
&values[352], /* 174  LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[354], /* 175  RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[356], /* 176  LIGHT SHADE */
&values[358], /* 177  MEDIUM SHADE */
&values[360], /* 178  DARK SHADE */
&values[362], /* 179  BOX DRAWINGS LIGHT VERTICAL */
&values[364], /* 180  BOX DRAWINGS LIGHT VERTICAL AND LEFT */
&values[366], /* 181  LATIN CAPITAL LETTER A WITH ACUTE */
&values[368], /* 182  LATIN CAPITAL LETTER A WITH CIRCUMFLEX */
&values[370], /* 183  LATIN CAPITAL LETTER A WITH GRAVE */
&values[372], /* 184  COPYRIGHT SIGN */
&values[374], /* 185  BOX DRAWINGS DOUBLE VERTICAL AND LEFT */
&values[376], /* 186  BOX DRAWINGS DOUBLE VERTICAL */
&values[378], /* 187  BOX DRAWINGS DOUBLE DOWN AND LEFT */
&values[380], /* 188  BOX DRAWINGS DOUBLE UP AND LEFT */
&values[382], /* 189  CENT SIGN */
&values[384], /* 190  YEN SIGN */
&values[386], /* 191  BOX DRAWINGS LIGHT DOWN AND LEFT */
&values[388], /* 192  BOX DRAWINGS LIGHT UP AND RIGHT */
&values[390], /* 193  BOX DRAWINGS LIGHT UP AND HORIZONTAL */
&values[392], /* 194  BOX DRAWINGS LIGHT DOWN AND HORIZONTAL */
&values[394], /* 195  BOX DRAWINGS LIGHT VERTICAL AND RIGHT */
&values[396], /* 196  BOX DRAWINGS LIGHT HORIZONTAL */
&values[398], /* 197  BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL */
&values[400], /* 198  LATIN SMALL LETTER A WITH TILDE */
&values[402], /* 199  LATIN CAPITAL LETTER A WITH TILDE */
&values[404], /* 200  BOX DRAWINGS DOUBLE UP AND RIGHT */
&values[406], /* 201  BOX DRAWINGS DOUBLE DOWN AND RIGHT */
&values[408], /* 202  BOX DRAWINGS DOUBLE UP AND HORIZONTAL */
&values[410], /* 203  BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL */
&values[412], /* 204  BOX DRAWINGS DOUBLE VERTICAL AND RIGHT */
&values[414], /* 205  BOX DRAWINGS DOUBLE HORIZONTAL */
&values[416], /* 206  BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL */
&values[418], /* 207  CURRENCY SIGN */
&values[420], /* 208  LATIN SMALL LETTER ETH */
&values[422], /* 209  LATIN CAPITAL LETTER ETH */
&values[424], /* 210  LATIN CAPITAL LETTER E WITH CIRCUMFLEX */
&values[426], /* 211  LATIN CAPITAL LETTER E WITH DIAERESIS */
&values[428], /* 212  LATIN CAPITAL LETTER E WITH GRAVE */
&values[430], /* 213  Euro sign */
&values[432], /* 214  LATIN CAPITAL LETTER I WITH ACUTE */
&values[434], /* 215  LATIN CAPITAL LETTER I WITH CIRCUMFLEX */
&values[436], /* 216  LATIN CAPITAL LETTER I WITH DIAERESIS */
&values[438], /* 217  BOX DRAWINGS LIGHT UP AND LEFT */
&values[440], /* 218  BOX DRAWINGS LIGHT DOWN AND RIGHT */
&values[442], /* 219  FULL BLOCK */
&values[444], /* 220  LOWER HALF BLOCK */
&values[446], /* 221  BROKEN BAR */
&values[448], /* 222  LATIN CAPITAL LETTER I WITH GRAVE */
&values[450], /* 223  UPPER HALF BLOCK */
&values[452], /* 224  LATIN CAPITAL LETTER O WITH ACUTE */
&values[454], /* 225  LATIN SMALL LETTER SHARP S */
&values[456], /* 226  LATIN CAPITAL LETTER O WITH CIRCUMFLEX */
&values[458], /* 227  LATIN CAPITAL LETTER O WITH GRAVE */
&values[460], /* 228  LATIN SMALL LETTER O WITH TILDE */
&values[462], /* 229  LATIN CAPITAL LETTER O WITH TILDE */
&values[464], /* 230  MICRO SIGN */
&values[466], /* 231  LATIN SMALL LETTER THORN */
&values[468], /* 232  LATIN CAPITAL LETTER THORN */
&values[470], /* 233  LATIN CAPITAL LETTER U WITH ACUTE */
&values[472], /* 234  LATIN CAPITAL LETTER U WITH CIRCUMFLEX */
&values[474], /* 235  LATIN CAPITAL LETTER U WITH GRAVE */
&values[476], /* 236  LATIN SMALL LETTER Y WITH ACUTE */
&values[478], /* 237  LATIN CAPITAL LETTER Y WITH ACUTE */
&values[480], /* 238  MACRON */
&values[482], /* 239  ACUTE ACCENT */
&values[484], /* 240  SOFT HYPHEN */
&values[486], /* 241  PLUS-MINUS SIGN */
&values[488], /* 242  DOUBLE LOW LINE */
&values[490], /* 243  VULGAR FRACTION THREE QUARTERS */
&values[492], /* 244  PILCROW SIGN */
&values[494], /* 245  SECTION SIGN */
&values[496], /* 246  DIVISION SIGN */
&values[498], /* 247  CEDILLA */
&values[500], /* 248  DEGREE SIGN */
&values[502], /* 249  DIAERESIS */
&values[504], /* 250  MIDDLE DOT */
&values[506], /* 251  SUPERSCRIPT ONE */
&values[508], /* 252  SUPERSCRIPT THREE */
&values[510], /* 253  SUPERSCRIPT TWO */
&values[512], /* 254  BLACK SQUARE */
&values[514], /* 255  NO-BREAK SPACE */
}};
