/* This file was autogenerated from the file 
 * CP855.TXT from UNICODE.ORG */

/*     Name:     cp855_DOSCyrillic to Unicode table */
/*     Unicode version: 2.0 */
/*     Table version: 2.00 */
/*     Table format:  Format A */
/*     Date:          04/24/96 */
/*     Authors:       Lori Brownell <loribr@microsoft.com> */
/*                    K.D. Chang    <a-kchang@microsoft.com> */
/*     General notes: none */
/*     Format: Three tab-separated columns */
/*         Column #1 is the cp855_DOSCyrillic code (in hex) */
/*         Column #2 is the Unicode (in hex as 0xXXXX) */
/*         Column #3 is the Unicode name (follows a comment sign, '#') */
/*     The entries are in cp855_DOSCyrillic order */
/*  first 32 positions of cp437 */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0xfffd, 0xffff, 0x263a, 0xffff, 0x263b, 0xffff, 0x2665, 
0xffff, 0x2666, 0xffff, 0x2663, 0xffff, 0x2660, 0xffff, 0x2022, 
0xffff, 0x25d8, 0xffff, 0x25cb, 0xffff, 0x25d9, 0xffff, 0x2642, 
0xffff, 0x2640, 0xffff, 0x266a, 0xffff, 0x266b, 0xffff, 0x263c, 
0xffff, 0x25ba, 0xffff, 0x25c4, 0xffff, 0x2195, 0xffff, 0x203c, 
0xffff, 0x00b6, 0xffff, 0x00a7, 0xffff, 0x25ac, 0xffff, 0x21a8, 
0xffff, 0x2191, 0xffff, 0x2193, 0xffff, 0x2192, 0xffff, 0x2190, 
0xffff, 0x221f, 0xffff, 0x2194, 0xffff, 0x25b2, 0xffff, 0x25bc, 
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0x2302, 
0xffff, 0x0452, 0xffff, 0x0402, 0xffff, 0x0453, 0xffff, 0x0403, 
0xffff, 0x0451, 0xffff, 0x0401, 0xffff, 0x0454, 0xffff, 0x0404, 
0xffff, 0x0455, 0xffff, 0x0405, 0xffff, 0x0456, 0xffff, 0x0406, 
0xffff, 0x0457, 0xffff, 0x0407, 0xffff, 0x0458, 0xffff, 0x0408, 
0xffff, 0x0459, 0xffff, 0x0409, 0xffff, 0x045a, 0xffff, 0x040a, 
0xffff, 0x045b, 0xffff, 0x040b, 0xffff, 0x045c, 0xffff, 0x040c, 
0xffff, 0x045e, 0xffff, 0x040e, 0xffff, 0x045f, 0xffff, 0x040f, 
0xffff, 0x044e, 0xffff, 0x042e, 0xffff, 0x044a, 0xffff, 0x042a, 
0xffff, 0x0430, 0xffff, 0x0410, 0xffff, 0x0431, 0xffff, 0x0411, 
0xffff, 0x0446, 0xffff, 0x0426, 0xffff, 0x0434, 0xffff, 0x0414, 
0xffff, 0x0435, 0xffff, 0x0415, 0xffff, 0x0444, 0xffff, 0x0424, 
0xffff, 0x0433, 0xffff, 0x0413, 0xffff, 0x00ab, 0xffff, 0x00bb, 
0xffff, 0x2591, 0xffff, 0x2592, 0xffff, 0x2593, 0xffff, 0x2502, 
0xffff, 0x2524, 0xffff, 0x0445, 0xffff, 0x0425, 0xffff, 0x0438, 
0xffff, 0x0418, 0xffff, 0x2563, 0xffff, 0x2551, 0xffff, 0x2557, 
0xffff, 0x255d, 0xffff, 0x0439, 0xffff, 0x0419, 0xffff, 0x2510, 
0xffff, 0x2514, 0xffff, 0x2534, 0xffff, 0x252c, 0xffff, 0x251c, 
0xffff, 0x2500, 0xffff, 0x253c, 0xffff, 0x043a, 0xffff, 0x041a, 
0xffff, 0x255a, 0xffff, 0x2554, 0xffff, 0x2569, 0xffff, 0x2566, 
0xffff, 0x2560, 0xffff, 0x2550, 0xffff, 0x256c, 0xffff, 0x00a4, 
0xffff, 0x043b, 0xffff, 0x041b, 0xffff, 0x043c, 0xffff, 0x041c, 
0xffff, 0x043d, 0xffff, 0x041d, 0xffff, 0x043e, 0xffff, 0x041e, 
0xffff, 0x043f, 0xffff, 0x2518, 0xffff, 0x250c, 0xffff, 0x2588, 
0xffff, 0x2584, 0xffff, 0x041f, 0xffff, 0x044f, 0xffff, 0x2580, 
0xffff, 0x042f, 0xffff, 0x0440, 0xffff, 0x0420, 0xffff, 0x0441, 
0xffff, 0x0421, 0xffff, 0x0442, 0xffff, 0x0422, 0xffff, 0x0443, 
0xffff, 0x0423, 0xffff, 0x0436, 0xffff, 0x0416, 0xffff, 0x0432, 
0xffff, 0x0412, 0xffff, 0x044c, 0xffff, 0x042c, 0xffff, 0x2116, 
0xffff, 0x00ad, 0xffff, 0x044b, 0xffff, 0x042b, 0xffff, 0x0437, 
0xffff, 0x0417, 0xffff, 0x0448, 0xffff, 0x0428, 0xffff, 0x044d, 
0xffff, 0x042d, 0xffff, 0x0449, 0xffff, 0x0429, 0xffff, 0x0447, 
0xffff, 0x0427, 0xffff, 0x00a7, 0xffff, 0x25a0, 0xffff, 0x00a0, 
0xffff, };

struct psf_mapping256 m_CP855 = { "CP855", 
256, {
&values[1], /* 0  */
&values[3], /* 1  */
&values[5], /* 2  */
&values[7], /* 3  */
&values[9], /* 4  */
&values[11], /* 5  */
&values[13], /* 6  */
&values[15], /* 7  */
&values[17], /* 8  */
&values[19], /* 9  */
&values[21], /* 10  */
&values[23], /* 11  */
&values[25], /* 12  */
&values[27], /* 13  */
&values[29], /* 14  */
&values[31], /* 15  */
&values[33], /* 16  */
&values[35], /* 17  */
&values[37], /* 18  */
&values[39], /* 19  */
&values[41], /* 20  */
&values[43], /* 21  */
&values[45], /* 22  */
&values[47], /* 23  */
&values[49], /* 24  */
&values[51], /* 25  */
&values[53], /* 26  */
&values[55], /* 27  */
&values[57], /* 28  */
&values[59], /* 29  */
&values[61], /* 30  */
&values[63], /* 31  */
&values[65], /* 32 SPACE */
&values[67], /* 33 EXCLAMATION MARK */
&values[69], /* 34 QUOTATION MARK */
&values[71], /* 35 NUMBER SIGN */
&values[73], /* 36 DOLLAR SIGN */
&values[75], /* 37 PERCENT SIGN */
&values[77], /* 38 AMPERSAND */
&values[79], /* 39 APOSTROPHE */
&values[81], /* 40 LEFT PARENTHESIS */
&values[83], /* 41 RIGHT PARENTHESIS */
&values[85], /* 42 ASTERISK */
&values[87], /* 43 PLUS SIGN */
&values[89], /* 44 COMMA */
&values[91], /* 45 HYPHEN-MINUS */
&values[93], /* 46 FULL STOP */
&values[95], /* 47 SOLIDUS */
&values[97], /* 48 DIGIT ZERO */
&values[99], /* 49 DIGIT ONE */
&values[101], /* 50 DIGIT TWO */
&values[103], /* 51 DIGIT THREE */
&values[105], /* 52 DIGIT FOUR */
&values[107], /* 53 DIGIT FIVE */
&values[109], /* 54 DIGIT SIX */
&values[111], /* 55 DIGIT SEVEN */
&values[113], /* 56 DIGIT EIGHT */
&values[115], /* 57 DIGIT NINE */
&values[117], /* 58 COLON */
&values[119], /* 59 SEMICOLON */
&values[121], /* 60 LESS-THAN SIGN */
&values[123], /* 61 EQUALS SIGN */
&values[125], /* 62 GREATER-THAN SIGN */
&values[127], /* 63 QUESTION MARK */
&values[129], /* 64 COMMERCIAL AT */
&values[131], /* 65 LATIN CAPITAL LETTER A */
&values[133], /* 66 LATIN CAPITAL LETTER B */
&values[135], /* 67 LATIN CAPITAL LETTER C */
&values[137], /* 68 LATIN CAPITAL LETTER D */
&values[139], /* 69 LATIN CAPITAL LETTER E */
&values[141], /* 70 LATIN CAPITAL LETTER F */
&values[143], /* 71 LATIN CAPITAL LETTER G */
&values[145], /* 72 LATIN CAPITAL LETTER H */
&values[147], /* 73 LATIN CAPITAL LETTER I */
&values[149], /* 74 LATIN CAPITAL LETTER J */
&values[151], /* 75 LATIN CAPITAL LETTER K */
&values[153], /* 76 LATIN CAPITAL LETTER L */
&values[155], /* 77 LATIN CAPITAL LETTER M */
&values[157], /* 78 LATIN CAPITAL LETTER N */
&values[159], /* 79 LATIN CAPITAL LETTER O */
&values[161], /* 80 LATIN CAPITAL LETTER P */
&values[163], /* 81 LATIN CAPITAL LETTER Q */
&values[165], /* 82 LATIN CAPITAL LETTER R */
&values[167], /* 83 LATIN CAPITAL LETTER S */
&values[169], /* 84 LATIN CAPITAL LETTER T */
&values[171], /* 85 LATIN CAPITAL LETTER U */
&values[173], /* 86 LATIN CAPITAL LETTER V */
&values[175], /* 87 LATIN CAPITAL LETTER W */
&values[177], /* 88 LATIN CAPITAL LETTER X */
&values[179], /* 89 LATIN CAPITAL LETTER Y */
&values[181], /* 90 LATIN CAPITAL LETTER Z */
&values[183], /* 91 LEFT SQUARE BRACKET */
&values[185], /* 92 REVERSE SOLIDUS */
&values[187], /* 93 RIGHT SQUARE BRACKET */
&values[189], /* 94 CIRCUMFLEX ACCENT */
&values[191], /* 95 LOW LINE */
&values[193], /* 96 GRAVE ACCENT */
&values[195], /* 97 LATIN SMALL LETTER A */
&values[197], /* 98 LATIN SMALL LETTER B */
&values[199], /* 99 LATIN SMALL LETTER C */
&values[201], /* 100 LATIN SMALL LETTER D */
&values[203], /* 101 LATIN SMALL LETTER E */
&values[205], /* 102 LATIN SMALL LETTER F */
&values[207], /* 103 LATIN SMALL LETTER G */
&values[209], /* 104 LATIN SMALL LETTER H */
&values[211], /* 105 LATIN SMALL LETTER I */
&values[213], /* 106 LATIN SMALL LETTER J */
&values[215], /* 107 LATIN SMALL LETTER K */
&values[217], /* 108 LATIN SMALL LETTER L */
&values[219], /* 109 LATIN SMALL LETTER M */
&values[221], /* 110 LATIN SMALL LETTER N */
&values[223], /* 111 LATIN SMALL LETTER O */
&values[225], /* 112 LATIN SMALL LETTER P */
&values[227], /* 113 LATIN SMALL LETTER Q */
&values[229], /* 114 LATIN SMALL LETTER R */
&values[231], /* 115 LATIN SMALL LETTER S */
&values[233], /* 116 LATIN SMALL LETTER T */
&values[235], /* 117 LATIN SMALL LETTER U */
&values[237], /* 118 LATIN SMALL LETTER V */
&values[239], /* 119 LATIN SMALL LETTER W */
&values[241], /* 120 LATIN SMALL LETTER X */
&values[243], /* 121 LATIN SMALL LETTER Y */
&values[245], /* 122 LATIN SMALL LETTER Z */
&values[247], /* 123 LEFT CURLY BRACKET */
&values[249], /* 124 VERTICAL LINE */
&values[251], /* 125 RIGHT CURLY BRACKET */
&values[253], /* 126 TILDE */
&values[255], /* 127 HOUSE */
&values[257], /* 128 CYRILLIC SMALL LETTER DJE */
&values[259], /* 129 CYRILLIC CAPITAL LETTER DJE */
&values[261], /* 130 CYRILLIC SMALL LETTER GJE */
&values[263], /* 131 CYRILLIC CAPITAL LETTER GJE */
&values[265], /* 132 CYRILLIC SMALL LETTER IO */
&values[267], /* 133 CYRILLIC CAPITAL LETTER IO */
&values[269], /* 134 CYRILLIC SMALL LETTER UKRAINIAN IE */
&values[271], /* 135 CYRILLIC CAPITAL LETTER UKRAINIAN IE */
&values[273], /* 136 CYRILLIC SMALL LETTER DZE */
&values[275], /* 137 CYRILLIC CAPITAL LETTER DZE */
&values[277], /* 138 CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I */
&values[279], /* 139 CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I */
&values[281], /* 140 CYRILLIC SMALL LETTER YI */
&values[283], /* 141 CYRILLIC CAPITAL LETTER YI */
&values[285], /* 142 CYRILLIC SMALL LETTER JE */
&values[287], /* 143 CYRILLIC CAPITAL LETTER JE */
&values[289], /* 144 CYRILLIC SMALL LETTER LJE */
&values[291], /* 145 CYRILLIC CAPITAL LETTER LJE */
&values[293], /* 146 CYRILLIC SMALL LETTER NJE */
&values[295], /* 147 CYRILLIC CAPITAL LETTER NJE */
&values[297], /* 148 CYRILLIC SMALL LETTER TSHE */
&values[299], /* 149 CYRILLIC CAPITAL LETTER TSHE */
&values[301], /* 150 CYRILLIC SMALL LETTER KJE */
&values[303], /* 151 CYRILLIC CAPITAL LETTER KJE */
&values[305], /* 152 CYRILLIC SMALL LETTER SHORT U */
&values[307], /* 153 CYRILLIC CAPITAL LETTER SHORT U */
&values[309], /* 154 CYRILLIC SMALL LETTER DZHE */
&values[311], /* 155 CYRILLIC CAPITAL LETTER DZHE */
&values[313], /* 156 CYRILLIC SMALL LETTER YU */
&values[315], /* 157 CYRILLIC CAPITAL LETTER YU */
&values[317], /* 158 CYRILLIC SMALL LETTER HARD SIGN */
&values[319], /* 159 CYRILLIC CAPITAL LETTER HARD SIGN */
&values[321], /* 160 CYRILLIC SMALL LETTER A */
&values[323], /* 161 CYRILLIC CAPITAL LETTER A */
&values[325], /* 162 CYRILLIC SMALL LETTER BE */
&values[327], /* 163 CYRILLIC CAPITAL LETTER BE */
&values[329], /* 164 CYRILLIC SMALL LETTER TSE */
&values[331], /* 165 CYRILLIC CAPITAL LETTER TSE */
&values[333], /* 166 CYRILLIC SMALL LETTER DE */
&values[335], /* 167 CYRILLIC CAPITAL LETTER DE */
&values[337], /* 168 CYRILLIC SMALL LETTER IE */
&values[339], /* 169 CYRILLIC CAPITAL LETTER IE */
&values[341], /* 170 CYRILLIC SMALL LETTER EF */
&values[343], /* 171 CYRILLIC CAPITAL LETTER EF */
&values[345], /* 172 CYRILLIC SMALL LETTER GHE */
&values[347], /* 173 CYRILLIC CAPITAL LETTER GHE */
&values[349], /* 174 LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[351], /* 175 RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[353], /* 176 LIGHT SHADE */
&values[355], /* 177 MEDIUM SHADE */
&values[357], /* 178 DARK SHADE */
&values[359], /* 179 BOX DRAWINGS LIGHT VERTICAL */
&values[361], /* 180 BOX DRAWINGS LIGHT VERTICAL AND LEFT */
&values[363], /* 181 CYRILLIC SMALL LETTER HA */
&values[365], /* 182 CYRILLIC CAPITAL LETTER HA */
&values[367], /* 183 CYRILLIC SMALL LETTER I */
&values[369], /* 184 CYRILLIC CAPITAL LETTER I */
&values[371], /* 185 BOX DRAWINGS DOUBLE VERTICAL AND LEFT */
&values[373], /* 186 BOX DRAWINGS DOUBLE VERTICAL */
&values[375], /* 187 BOX DRAWINGS DOUBLE DOWN AND LEFT */
&values[377], /* 188 BOX DRAWINGS DOUBLE UP AND LEFT */
&values[379], /* 189 CYRILLIC SMALL LETTER SHORT I */
&values[381], /* 190 CYRILLIC CAPITAL LETTER SHORT I */
&values[383], /* 191 BOX DRAWINGS LIGHT DOWN AND LEFT */
&values[385], /* 192 BOX DRAWINGS LIGHT UP AND RIGHT */
&values[387], /* 193 BOX DRAWINGS LIGHT UP AND HORIZONTAL */
&values[389], /* 194 BOX DRAWINGS LIGHT DOWN AND HORIZONTAL */
&values[391], /* 195 BOX DRAWINGS LIGHT VERTICAL AND RIGHT */
&values[393], /* 196 BOX DRAWINGS LIGHT HORIZONTAL */
&values[395], /* 197 BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL */
&values[397], /* 198 CYRILLIC SMALL LETTER KA */
&values[399], /* 199 CYRILLIC CAPITAL LETTER KA */
&values[401], /* 200 BOX DRAWINGS DOUBLE UP AND RIGHT */
&values[403], /* 201 BOX DRAWINGS DOUBLE DOWN AND RIGHT */
&values[405], /* 202 BOX DRAWINGS DOUBLE UP AND HORIZONTAL */
&values[407], /* 203 BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL */
&values[409], /* 204 BOX DRAWINGS DOUBLE VERTICAL AND RIGHT */
&values[411], /* 205 BOX DRAWINGS DOUBLE HORIZONTAL */
&values[413], /* 206 BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL */
&values[415], /* 207 CURRENCY SIGN */
&values[417], /* 208 CYRILLIC SMALL LETTER EL */
&values[419], /* 209 CYRILLIC CAPITAL LETTER EL */
&values[421], /* 210 CYRILLIC SMALL LETTER EM */
&values[423], /* 211 CYRILLIC CAPITAL LETTER EM */
&values[425], /* 212 CYRILLIC SMALL LETTER EN */
&values[427], /* 213 CYRILLIC CAPITAL LETTER EN */
&values[429], /* 214 CYRILLIC SMALL LETTER O */
&values[431], /* 215 CYRILLIC CAPITAL LETTER O */
&values[433], /* 216 CYRILLIC SMALL LETTER PE */
&values[435], /* 217 BOX DRAWINGS LIGHT UP AND LEFT */
&values[437], /* 218 BOX DRAWINGS LIGHT DOWN AND RIGHT */
&values[439], /* 219 FULL BLOCK */
&values[441], /* 220 LOWER HALF BLOCK */
&values[443], /* 221 CYRILLIC CAPITAL LETTER PE */
&values[445], /* 222 CYRILLIC SMALL LETTER YA */
&values[447], /* 223 UPPER HALF BLOCK */
&values[449], /* 224 CYRILLIC CAPITAL LETTER YA */
&values[451], /* 225 CYRILLIC SMALL LETTER ER */
&values[453], /* 226 CYRILLIC CAPITAL LETTER ER */
&values[455], /* 227 CYRILLIC SMALL LETTER ES */
&values[457], /* 228 CYRILLIC CAPITAL LETTER ES */
&values[459], /* 229 CYRILLIC SMALL LETTER TE */
&values[461], /* 230 CYRILLIC CAPITAL LETTER TE */
&values[463], /* 231 CYRILLIC SMALL LETTER U */
&values[465], /* 232 CYRILLIC CAPITAL LETTER U */
&values[467], /* 233 CYRILLIC SMALL LETTER ZHE */
&values[469], /* 234 CYRILLIC CAPITAL LETTER ZHE */
&values[471], /* 235 CYRILLIC SMALL LETTER VE */
&values[473], /* 236 CYRILLIC CAPITAL LETTER VE */
&values[475], /* 237 CYRILLIC SMALL LETTER SOFT SIGN */
&values[477], /* 238 CYRILLIC CAPITAL LETTER SOFT SIGN */
&values[479], /* 239 NUMERO SIGN */
&values[481], /* 240 SOFT HYPHEN */
&values[483], /* 241 CYRILLIC SMALL LETTER YERU */
&values[485], /* 242 CYRILLIC CAPITAL LETTER YERU */
&values[487], /* 243 CYRILLIC SMALL LETTER ZE */
&values[489], /* 244 CYRILLIC CAPITAL LETTER ZE */
&values[491], /* 245 CYRILLIC SMALL LETTER SHA */
&values[493], /* 246 CYRILLIC CAPITAL LETTER SHA */
&values[495], /* 247 CYRILLIC SMALL LETTER E */
&values[497], /* 248 CYRILLIC CAPITAL LETTER E */
&values[499], /* 249 CYRILLIC SMALL LETTER SHCHA */
&values[501], /* 250 CYRILLIC CAPITAL LETTER SHCHA */
&values[503], /* 251 CYRILLIC SMALL LETTER CHE */
&values[505], /* 252 CYRILLIC CAPITAL LETTER CHE */
&values[507], /* 253 SECTION SIGN */
&values[509], /* 254 BLACK SQUARE */
&values[511], /* 255 NO-BREAK SPACE */
}};
