/* This file was autogenerated from the Unicode mapping 
 * table cp850a.uni in the format used by the Linux kbd package */

/*  cp850a */
/*  This is cp850, but with positions 0-31 replaced by cp437 symbols */
/*  first 32 positions of cp437 */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0x0000, 0xffff, 0x263a, 0xffff, 0x263b, 0xffff, 0x2665, 
0xffff, 0x2666, 0xffff, 0x2663, 0xffff, 0x2660, 0xffff, 0x2022, 
0xffff, 0x25d8, 0xffff, 0x25cb, 0xffff, 0x25d9, 0xffff, 0x2642, 
0xffff, 0x2640, 0xffff, 0x266a, 0xffff, 0x266b, 0xffff, 0x263c, 
0xffff, 0x25ba, 0xffff, 0x25c4, 0xffff, 0x2195, 0xffff, 0x203c, 
0xffff, 0x00b6, 0xffff, 0x00a7, 0xffff, 0x25ac, 0xffff, 0x21a8, 
0xffff, 0x2191, 0xffff, 0x2193, 0xffff, 0x2192, 0xffff, 0x2190, 
0xffff, 0x221f, 0xffff, 0x2194, 0xffff, 0x25b2, 0xffff, 0x25bc, 
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0x2302, 
0xffff, 0x00c7, 0xffff, 0x00fc, 0xffff, 0x00e9, 0xffff, 0x00e2, 
0xffff, 0x00e4, 0xffff, 0x00e0, 0xffff, 0x00e5, 0xffff, 0x00e7, 
0xffff, 0x00ea, 0xffff, 0x00eb, 0xffff, 0x00e8, 0xffff, 0x00ef, 
0xffff, 0x00ee, 0xffff, 0x00ec, 0xffff, 0x00c4, 0xffff, 0x00c5, 
0xffff, 0x00c9, 0xffff, 0x00e6, 0xffff, 0x00c6, 0xffff, 0x00f4, 
0xffff, 0x00f6, 0xffff, 0x00f2, 0xffff, 0x00fb, 0xffff, 0x00f9, 
0xffff, 0x00ff, 0xffff, 0x00d6, 0xffff, 0x00dc, 0xffff, 0x00f8, 
0xffff, 0x00a3, 0xffff, 0x00d8, 0xffff, 0x00d7, 0xffff, 0x0192, 
0xffff, 0x00e1, 0xffff, 0x00ed, 0xffff, 0x00f3, 0xffff, 0x00fa, 
0xffff, 0x00f1, 0xffff, 0x00d1, 0xffff, 0x00aa, 0xffff, 0x00ba, 
0xffff, 0x00bf, 0xffff, 0x00ae, 0xffff, 0x00ac, 0xffff, 0x00bd, 
0xffff, 0x00bc, 0xffff, 0x00a1, 0xffff, 0x00ab, 0xffff, 0x00bb, 
0xffff, 0x2591, 0xffff, 0x2592, 0xffff, 0x2593, 0xffff, 0x2502, 
0xffff, 0x2524, 0xffff, 0x00c1, 0xffff, 0x00c2, 0xffff, 0x00c0, 
0xffff, 0x00a9, 0xffff, 0x2563, 0xffff, 0x2551, 0xffff, 0x2557, 
0xffff, 0x255d, 0xffff, 0x00a2, 0xffff, 0x00a5, 0xffff, 0x2510, 
0xffff, 0x2514, 0xffff, 0x2534, 0xffff, 0x252c, 0xffff, 0x251c, 
0xffff, 0x2500, 0xffff, 0x253c, 0xffff, 0x00e3, 0xffff, 0x00c3, 
0xffff, 0x255a, 0xffff, 0x2554, 0xffff, 0x2569, 0xffff, 0x2566, 
0xffff, 0x2560, 0xffff, 0x2550, 0xffff, 0x256c, 0xffff, 0x00a4, 
0xffff, 0x00f0, 0xffff, 0x00d0, 0xffff, 0x00ca, 0xffff, 0x00cb, 
0xffff, 0x00c8, 0xffff, 0x0131, 0xffff, 0x00cd, 0xffff, 0x00ce, 
0xffff, 0x00cf, 0xffff, 0x2518, 0xffff, 0x250c, 0xffff, 0x2588, 
0xffff, 0x2584, 0xffff, 0x00a6, 0xffff, 0x00cc, 0xffff, 0x2580, 
0xffff, 0x00d3, 0xffff, 0x00df, 0xffff, 0x00d4, 0xffff, 0x00d2, 
0xffff, 0x00f5, 0xffff, 0x00d5, 0xffff, 0x00b5, 0xffff, 0x00fe, 
0xffff, 0x00de, 0xffff, 0x00da, 0xffff, 0x00db, 0xffff, 0x00d9, 
0xffff, 0x00fd, 0xffff, 0x00dd, 0xffff, 0x00af, 0xffff, 0x00b4, 
0xffff, 0x00ad, 0xffff, 0x00b1, 0xffff, 0x2017, 0xffff, 0x00be, 
0xffff, 0x00b6, 0xffff, 0x00a7, 0xffff, 0x00f7, 0xffff, 0x00b8, 
0xffff, 0x00b0, 0xffff, 0x00a8, 0xffff, 0x00b7, 0xffff, 0x00b9, 
0xffff, 0x00b3, 0xffff, 0x00b2, 0xffff, 0x25a0, 0xffff, 0x00a0, 
0xffff, };

struct psf_mapping256 m_CP850 = { "CP850",
256, {
&values[1], /* 0  */
&values[3], /* 1  */
&values[5], /* 2  */
&values[7], /* 3  */
&values[9], /* 4  */
&values[11], /* 5  */
&values[13], /* 6  */
&values[15], /* 7  */
&values[17], /* 8  */
&values[19], /* 9  */
&values[21], /* 10  */
&values[23], /* 11  */
&values[25], /* 12  */
&values[27], /* 13  */
&values[29], /* 14  */
&values[31], /* 15  */
&values[33], /* 16  */
&values[35], /* 17  */
&values[37], /* 18  */
&values[39], /* 19  */
&values[41], /* 20  */
&values[43], /* 21  */
&values[45], /* 22  */
&values[47], /* 23  */
&values[49], /* 24  */
&values[51], /* 25  */
&values[53], /* 26  */
&values[55], /* 27  */
&values[57], /* 28  */
&values[59], /* 29  */
&values[61], /* 30  */
&values[63], /* 31  */
&values[65], /* 32  */
&values[67], /* 33  */
&values[69], /* 34  */
&values[71], /* 35  */
&values[73], /* 36  */
&values[75], /* 37  */
&values[77], /* 38  */
&values[79], /* 39  */
&values[81], /* 40  */
&values[83], /* 41  */
&values[85], /* 42  */
&values[87], /* 43  */
&values[89], /* 44  */
&values[91], /* 45  */
&values[93], /* 46  */
&values[95], /* 47  */
&values[97], /* 48  */
&values[99], /* 49  */
&values[101], /* 50  */
&values[103], /* 51  */
&values[105], /* 52  */
&values[107], /* 53  */
&values[109], /* 54  */
&values[111], /* 55  */
&values[113], /* 56  */
&values[115], /* 57  */
&values[117], /* 58  */
&values[119], /* 59  */
&values[121], /* 60  */
&values[123], /* 61  */
&values[125], /* 62  */
&values[127], /* 63  */
&values[129], /* 64  */
&values[131], /* 65  */
&values[133], /* 66  */
&values[135], /* 67  */
&values[137], /* 68  */
&values[139], /* 69  */
&values[141], /* 70  */
&values[143], /* 71  */
&values[145], /* 72  */
&values[147], /* 73  */
&values[149], /* 74  */
&values[151], /* 75  */
&values[153], /* 76  */
&values[155], /* 77  */
&values[157], /* 78  */
&values[159], /* 79  */
&values[161], /* 80  */
&values[163], /* 81  */
&values[165], /* 82  */
&values[167], /* 83  */
&values[169], /* 84  */
&values[171], /* 85  */
&values[173], /* 86  */
&values[175], /* 87  */
&values[177], /* 88  */
&values[179], /* 89  */
&values[181], /* 90  */
&values[183], /* 91  */
&values[185], /* 92  */
&values[187], /* 93  */
&values[189], /* 94  */
&values[191], /* 95  */
&values[193], /* 96  */
&values[195], /* 97  */
&values[197], /* 98  */
&values[199], /* 99  */
&values[201], /* 100  */
&values[203], /* 101  */
&values[205], /* 102  */
&values[207], /* 103  */
&values[209], /* 104  */
&values[211], /* 105  */
&values[213], /* 106  */
&values[215], /* 107  */
&values[217], /* 108  */
&values[219], /* 109  */
&values[221], /* 110  */
&values[223], /* 111  */
&values[225], /* 112  */
&values[227], /* 113  */
&values[229], /* 114  */
&values[231], /* 115  */
&values[233], /* 116  */
&values[235], /* 117  */
&values[237], /* 118  */
&values[239], /* 119  */
&values[241], /* 120  */
&values[243], /* 121  */
&values[245], /* 122  */
&values[247], /* 123  */
&values[249], /* 124  */
&values[251], /* 125  */
&values[253], /* 126  */
&values[255], /* 127  */
&values[257], /* 128  LATIN CAPITAL LETTER C WITH CEDILLA */
&values[259], /* 129  LATIN SMALL LETTER U WITH DIAERESIS */
&values[261], /* 130  LATIN SMALL LETTER E WITH ACUTE */
&values[263], /* 131  LATIN SMALL LETTER A WITH CIRCUMFLEX */
&values[265], /* 132  LATIN SMALL LETTER A WITH DIAERESIS */
&values[267], /* 133  LATIN SMALL LETTER A WITH GRAVE */
&values[269], /* 134  LATIN SMALL LETTER A WITH RING ABOVE */
&values[271], /* 135  LATIN SMALL LETTER C WITH CEDILLA */
&values[273], /* 136  LATIN SMALL LETTER E WITH CIRCUMFLEX */
&values[275], /* 137  LATIN SMALL LETTER E WITH DIAERESIS */
&values[277], /* 138  LATIN SMALL LETTER E WITH GRAVE */
&values[279], /* 139  LATIN SMALL LETTER I WITH DIAERESIS */
&values[281], /* 140  LATIN SMALL LETTER I WITH CIRCUMFLEX */
&values[283], /* 141  LATIN SMALL LETTER I WITH GRAVE */
&values[285], /* 142  LATIN CAPITAL LETTER A WITH DIAERESIS */
&values[287], /* 143  LATIN CAPITAL LETTER A WITH RING ABOVE */
&values[289], /* 144  LATIN CAPITAL LETTER E WITH ACUTE */
&values[291], /* 145  LATIN SMALL LIGATURE AE */
&values[293], /* 146  LATIN CAPITAL LIGATURE AE */
&values[295], /* 147  LATIN SMALL LETTER O WITH CIRCUMFLEX */
&values[297], /* 148  LATIN SMALL LETTER O WITH DIAERESIS */
&values[299], /* 149  LATIN SMALL LETTER O WITH GRAVE */
&values[301], /* 150  LATIN SMALL LETTER U WITH CIRCUMFLEX */
&values[303], /* 151  LATIN SMALL LETTER U WITH GRAVE */
&values[305], /* 152  LATIN SMALL LETTER Y WITH DIAERESIS */
&values[307], /* 153  LATIN CAPITAL LETTER O WITH DIAERESIS */
&values[309], /* 154  LATIN CAPITAL LETTER U WITH DIAERESIS */
&values[311], /* 155  LATIN SMALL LETTER O WITH STROKE */
&values[313], /* 156  POUND SIGN */
&values[315], /* 157  LATIN CAPITAL LETTER O WITH STROKE */
&values[317], /* 158  MULTIPLICATION SIGN */
&values[319], /* 159  LATIN SMALL LETTER F WITH HOOK */
&values[321], /* 160  LATIN SMALL LETTER A WITH ACUTE */
&values[323], /* 161  LATIN SMALL LETTER I WITH ACUTE */
&values[325], /* 162  LATIN SMALL LETTER O WITH ACUTE */
&values[327], /* 163  LATIN SMALL LETTER U WITH ACUTE */
&values[329], /* 164  LATIN SMALL LETTER N WITH TILDE */
&values[331], /* 165  LATIN CAPITAL LETTER N WITH TILDE */
&values[333], /* 166  FEMININE ORDINAL INDICATOR */
&values[335], /* 167  MASCULINE ORDINAL INDICATOR */
&values[337], /* 168  INVERTED QUESTION MARK */
&values[339], /* 169  REGISTERED SIGN */
&values[341], /* 170  NOT SIGN */
&values[343], /* 171  VULGAR FRACTION ONE HALF */
&values[345], /* 172  VULGAR FRACTION ONE QUARTER */
&values[347], /* 173  INVERTED EXCLAMATION MARK */
&values[349], /* 174  LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[351], /* 175  RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[353], /* 176  LIGHT SHADE */
&values[355], /* 177  MEDIUM SHADE */
&values[357], /* 178  DARK SHADE */
&values[359], /* 179  BOX DRAWINGS LIGHT VERTICAL */
&values[361], /* 180  BOX DRAWINGS LIGHT VERTICAL AND LEFT */
&values[363], /* 181  LATIN CAPITAL LETTER A WITH ACUTE */
&values[365], /* 182  LATIN CAPITAL LETTER A WITH CIRCUMFLEX */
&values[367], /* 183  LATIN CAPITAL LETTER A WITH GRAVE */
&values[369], /* 184  COPYRIGHT SIGN */
&values[371], /* 185  BOX DRAWINGS DOUBLE VERTICAL AND LEFT */
&values[373], /* 186  BOX DRAWINGS DOUBLE VERTICAL */
&values[375], /* 187  BOX DRAWINGS DOUBLE DOWN AND LEFT */
&values[377], /* 188  BOX DRAWINGS DOUBLE UP AND LEFT */
&values[379], /* 189  CENT SIGN */
&values[381], /* 190  YEN SIGN */
&values[383], /* 191  BOX DRAWINGS LIGHT DOWN AND LEFT */
&values[385], /* 192  BOX DRAWINGS LIGHT UP AND RIGHT */
&values[387], /* 193  BOX DRAWINGS LIGHT UP AND HORIZONTAL */
&values[389], /* 194  BOX DRAWINGS LIGHT DOWN AND HORIZONTAL */
&values[391], /* 195  BOX DRAWINGS LIGHT VERTICAL AND RIGHT */
&values[393], /* 196  BOX DRAWINGS LIGHT HORIZONTAL */
&values[395], /* 197  BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL */
&values[397], /* 198  LATIN SMALL LETTER A WITH TILDE */
&values[399], /* 199  LATIN CAPITAL LETTER A WITH TILDE */
&values[401], /* 200  BOX DRAWINGS DOUBLE UP AND RIGHT */
&values[403], /* 201  BOX DRAWINGS DOUBLE DOWN AND RIGHT */
&values[405], /* 202  BOX DRAWINGS DOUBLE UP AND HORIZONTAL */
&values[407], /* 203  BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL */
&values[409], /* 204  BOX DRAWINGS DOUBLE VERTICAL AND RIGHT */
&values[411], /* 205  BOX DRAWINGS DOUBLE HORIZONTAL */
&values[413], /* 206  BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL */
&values[415], /* 207  CURRENCY SIGN */
&values[417], /* 208  LATIN SMALL LETTER ETH */
&values[419], /* 209  LATIN CAPITAL LETTER ETH */
&values[421], /* 210  LATIN CAPITAL LETTER E WITH CIRCUMFLEX */
&values[423], /* 211  LATIN CAPITAL LETTER E WITH DIAERESIS */
&values[425], /* 212  LATIN CAPITAL LETTER E WITH GRAVE */
&values[427], /* 213  LATIN SMALL LETTER DOTLESS I */
&values[429], /* 214  LATIN CAPITAL LETTER I WITH ACUTE */
&values[431], /* 215  LATIN CAPITAL LETTER I WITH CIRCUMFLEX */
&values[433], /* 216  LATIN CAPITAL LETTER I WITH DIAERESIS */
&values[435], /* 217  BOX DRAWINGS LIGHT UP AND LEFT */
&values[437], /* 218  BOX DRAWINGS LIGHT DOWN AND RIGHT */
&values[439], /* 219  FULL BLOCK */
&values[441], /* 220  LOWER HALF BLOCK */
&values[443], /* 221  BROKEN BAR */
&values[445], /* 222  LATIN CAPITAL LETTER I WITH GRAVE */
&values[447], /* 223  UPPER HALF BLOCK */
&values[449], /* 224  LATIN CAPITAL LETTER O WITH ACUTE */
&values[451], /* 225  LATIN SMALL LETTER SHARP S */
&values[453], /* 226  LATIN CAPITAL LETTER O WITH CIRCUMFLEX */
&values[455], /* 227  LATIN CAPITAL LETTER O WITH GRAVE */
&values[457], /* 228  LATIN SMALL LETTER O WITH TILDE */
&values[459], /* 229  LATIN CAPITAL LETTER O WITH TILDE */
&values[461], /* 230  MICRO SIGN */
&values[463], /* 231  LATIN SMALL LETTER THORN */
&values[465], /* 232  LATIN CAPITAL LETTER THORN */
&values[467], /* 233  LATIN CAPITAL LETTER U WITH ACUTE */
&values[469], /* 234  LATIN CAPITAL LETTER U WITH CIRCUMFLEX */
&values[471], /* 235  LATIN CAPITAL LETTER U WITH GRAVE */
&values[473], /* 236  LATIN SMALL LETTER Y WITH ACUTE */
&values[475], /* 237  LATIN CAPITAL LETTER Y WITH ACUTE */
&values[477], /* 238  MACRON */
&values[479], /* 239  ACUTE ACCENT */
&values[481], /* 240  SOFT HYPHEN */
&values[483], /* 241  PLUS-MINUS SIGN */
&values[485], /* 242  DOUBLE LOW LINE */
&values[487], /* 243  VULGAR FRACTION THREE QUARTERS */
&values[489], /* 244  PILCROW SIGN */
&values[491], /* 245  SECTION SIGN */
&values[493], /* 246  DIVISION SIGN */
&values[495], /* 247  CEDILLA */
&values[497], /* 248  DEGREE SIGN */
&values[499], /* 249  DIAERESIS */
&values[501], /* 250  MIDDLE DOT */
&values[503], /* 251  SUPERSCRIPT ONE */
&values[505], /* 252  SUPERSCRIPT THREE */
&values[507], /* 253  SUPERSCRIPT TWO */
&values[509], /* 254  BLACK SQUARE */
&values[511], /* 255  NO-BREAK SPACE */
}};
