/* This file was autogenerated from the Unicode mapping 
 * table cp866a.uni in the format used by the Linux kbd package */

/*  This is cp865, but with positions 0-31 replaced by cp437 symbols */
/*  first 32 positions of cp437 */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0x0000, 0xffff, 0x263a, 0xffff, 0x263b, 0xffff, 0x2665, 
0xffff, 0x2666, 0xffff, 0x2663, 0xffff, 0x2660, 0xffff, 0x2022, 
0xffff, 0x25d8, 0xffff, 0x25cb, 0xffff, 0x25d9, 0xffff, 0x2642, 
0xffff, 0x2640, 0xffff, 0x266a, 0xffff, 0x266b, 0xffff, 0x263c, 
0xffff, 0x25ba, 0xffff, 0x25c4, 0xffff, 0x2195, 0xffff, 0x203c, 
0xffff, 0x00b6, 0xffff, 0x00a7, 0xffff, 0x25ac, 0xffff, 0x21a8, 
0xffff, 0x2191, 0xffff, 0x2193, 0xffff, 0x2192, 0xffff, 0x2190, 
0xffff, 0x221f, 0xffff, 0x2194, 0xffff, 0x25b2, 0xffff, 0x25bc, 
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0x2302, 
0xffff, 0x0410, 0xffff, 0x0411, 0xffff, 0x0412, 0xffff, 0x0413, 
0xffff, 0x0414, 0xffff, 0x0415, 0xffff, 0x0416, 0xffff, 0x0417, 
0xffff, 0x0418, 0xffff, 0x0419, 0xffff, 0x041a, 0xffff, 0x041b, 
0xffff, 0x041c, 0xffff, 0x041d, 0xffff, 0x041e, 0xffff, 0x041f, 
0xffff, 0x0420, 0xffff, 0x0421, 0xffff, 0x0422, 0xffff, 0x0423, 
0xffff, 0x0424, 0xffff, 0x0425, 0xffff, 0x0426, 0xffff, 0x0427, 
0xffff, 0x0428, 0xffff, 0x0429, 0xffff, 0x042a, 0xffff, 0x042b, 
0xffff, 0x042c, 0xffff, 0x042d, 0xffff, 0x042e, 0xffff, 0x042f, 
0xffff, 0x0430, 0xffff, 0x0431, 0xffff, 0x0432, 0xffff, 0x0433, 
0xffff, 0x0434, 0xffff, 0x0435, 0xffff, 0x0436, 0xffff, 0x0437, 
0xffff, 0x0438, 0xffff, 0x0439, 0xffff, 0x043a, 0xffff, 0x043b, 
0xffff, 0x043c, 0xffff, 0x043d, 0xffff, 0x043e, 0xffff, 0x043f, 
0xffff, 0x2591, 0xffff, 0x2592, 0xffff, 0x2593, 0xffff, 0x2502, 
0xffff, 0x2524, 0xffff, 0x2561, 0xffff, 0x2562, 0xffff, 0x2556, 
0xffff, 0x2555, 0xffff, 0x2563, 0xffff, 0x2551, 0xffff, 0x2557, 
0xffff, 0x255d, 0xffff, 0x255c, 0xffff, 0x255b, 0xffff, 0x2510, 
0xffff, 0x2514, 0xffff, 0x2534, 0xffff, 0x252c, 0xffff, 0x251c, 
0xffff, 0x2500, 0xffff, 0x253c, 0xffff, 0x255e, 0xffff, 0x255f, 
0xffff, 0x255a, 0xffff, 0x2554, 0xffff, 0x2569, 0xffff, 0x2566, 
0xffff, 0x2560, 0xffff, 0x2550, 0xffff, 0x256c, 0xffff, 0x2567, 
0xffff, 0x2568, 0xffff, 0x2564, 0xffff, 0x2565, 0xffff, 0x2559, 
0xffff, 0x2558, 0xffff, 0x2552, 0xffff, 0x2553, 0xffff, 0x256b, 
0xffff, 0x256a, 0xffff, 0x2518, 0xffff, 0x250c, 0xffff, 0x2588, 
0xffff, 0x2584, 0xffff, 0x258c, 0xffff, 0x2590, 0xffff, 0x2580, 
0xffff, 0x0440, 0xffff, 0x0441, 0xffff, 0x0442, 0xffff, 0x0443, 
0xffff, 0x0444, 0xffff, 0x0445, 0xffff, 0x0446, 0xffff, 0x0447, 
0xffff, 0x0448, 0xffff, 0x0449, 0xffff, 0x044a, 0xffff, 0x044b, 
0xffff, 0x044c, 0xffff, 0x044d, 0xffff, 0x044e, 0xffff, 0x044f, 
0xffff, 0x0401, 0xffff, 0x0451, 0xffff, 0x0404, 0xffff, 0x0454, 
0xffff, 0x0407, 0xffff, 0x0457, 0xffff, 0x040e, 0xffff, 0x045e, 
0xffff, 0x00b0, 0xffff, 0x2219, 0xffff, 0x00b7, 0xffff, 0x221a, 
0xffff, 0x2116, 0xffff, 0x00a4, 0xffff, 0x25a0, 0xffff, 0x00a0, 
0xffff, };

struct psf_mapping256 m_CP866 = { "CP866",
256, {
&values[1], /* 0  */
&values[3], /* 1  */
&values[5], /* 2  */
&values[7], /* 3  */
&values[9], /* 4  */
&values[11], /* 5  */
&values[13], /* 6  */
&values[15], /* 7  */
&values[17], /* 8  */
&values[19], /* 9  */
&values[21], /* 10  */
&values[23], /* 11  */
&values[25], /* 12  */
&values[27], /* 13  */
&values[29], /* 14  */
&values[31], /* 15  */
&values[33], /* 16  */
&values[35], /* 17  */
&values[37], /* 18  */
&values[39], /* 19  */
&values[41], /* 20  */
&values[43], /* 21  */
&values[45], /* 22  */
&values[47], /* 23  */
&values[49], /* 24  */
&values[51], /* 25  */
&values[53], /* 26  */
&values[55], /* 27  */
&values[57], /* 28  */
&values[59], /* 29  */
&values[61], /* 30  */
&values[63], /* 31  */
&values[65], /* 32  */
&values[67], /* 33  */
&values[69], /* 34  */
&values[71], /* 35  */
&values[73], /* 36  */
&values[75], /* 37  */
&values[77], /* 38  */
&values[79], /* 39  */
&values[81], /* 40  */
&values[83], /* 41  */
&values[85], /* 42  */
&values[87], /* 43  */
&values[89], /* 44  */
&values[91], /* 45  */
&values[93], /* 46  */
&values[95], /* 47  */
&values[97], /* 48  */
&values[99], /* 49  */
&values[101], /* 50  */
&values[103], /* 51  */
&values[105], /* 52  */
&values[107], /* 53  */
&values[109], /* 54  */
&values[111], /* 55  */
&values[113], /* 56  */
&values[115], /* 57  */
&values[117], /* 58  */
&values[119], /* 59  */
&values[121], /* 60  */
&values[123], /* 61  */
&values[125], /* 62  */
&values[127], /* 63  */
&values[129], /* 64  */
&values[131], /* 65  */
&values[133], /* 66  */
&values[135], /* 67  */
&values[137], /* 68  */
&values[139], /* 69  */
&values[141], /* 70  */
&values[143], /* 71  */
&values[145], /* 72  */
&values[147], /* 73  */
&values[149], /* 74  */
&values[151], /* 75  */
&values[153], /* 76  */
&values[155], /* 77  */
&values[157], /* 78  */
&values[159], /* 79  */
&values[161], /* 80  */
&values[163], /* 81  */
&values[165], /* 82  */
&values[167], /* 83  */
&values[169], /* 84  */
&values[171], /* 85  */
&values[173], /* 86  */
&values[175], /* 87  */
&values[177], /* 88  */
&values[179], /* 89  */
&values[181], /* 90  */
&values[183], /* 91  */
&values[185], /* 92  */
&values[187], /* 93  */
&values[189], /* 94  */
&values[191], /* 95  */
&values[193], /* 96  */
&values[195], /* 97  */
&values[197], /* 98  */
&values[199], /* 99  */
&values[201], /* 100  */
&values[203], /* 101  */
&values[205], /* 102  */
&values[207], /* 103  */
&values[209], /* 104  */
&values[211], /* 105  */
&values[213], /* 106  */
&values[215], /* 107  */
&values[217], /* 108  */
&values[219], /* 109  */
&values[221], /* 110  */
&values[223], /* 111  */
&values[225], /* 112  */
&values[227], /* 113  */
&values[229], /* 114  */
&values[231], /* 115  */
&values[233], /* 116  */
&values[235], /* 117  */
&values[237], /* 118  */
&values[239], /* 119  */
&values[241], /* 120  */
&values[243], /* 121  */
&values[245], /* 122  */
&values[247], /* 123  */
&values[249], /* 124  */
&values[251], /* 125  */
&values[253], /* 126  */
&values[255], /* 127  */
&values[257], /* 128  CYRILLIC CAPITAL LETTER A */
&values[259], /* 129  CYRILLIC CAPITAL LETTER BE */
&values[261], /* 130  CYRILLIC CAPITAL LETTER VE */
&values[263], /* 131  CYRILLIC CAPITAL LETTER GHE */
&values[265], /* 132  CYRILLIC CAPITAL LETTER DE */
&values[267], /* 133  CYRILLIC CAPITAL LETTER IE */
&values[269], /* 134  CYRILLIC CAPITAL LETTER ZHE */
&values[271], /* 135  CYRILLIC CAPITAL LETTER ZE */
&values[273], /* 136  CYRILLIC CAPITAL LETTER I */
&values[275], /* 137  CYRILLIC CAPITAL LETTER SHORT I */
&values[277], /* 138  CYRILLIC CAPITAL LETTER KA */
&values[279], /* 139  CYRILLIC CAPITAL LETTER EL */
&values[281], /* 140  CYRILLIC CAPITAL LETTER EM */
&values[283], /* 141  CYRILLIC CAPITAL LETTER EN */
&values[285], /* 142  CYRILLIC CAPITAL LETTER O */
&values[287], /* 143  CYRILLIC CAPITAL LETTER PE */
&values[289], /* 144  CYRILLIC CAPITAL LETTER ER */
&values[291], /* 145  CYRILLIC CAPITAL LETTER ES */
&values[293], /* 146  CYRILLIC CAPITAL LETTER TE */
&values[295], /* 147  CYRILLIC CAPITAL LETTER U */
&values[297], /* 148  CYRILLIC CAPITAL LETTER EF */
&values[299], /* 149  CYRILLIC CAPITAL LETTER HA */
&values[301], /* 150  CYRILLIC CAPITAL LETTER TSE */
&values[303], /* 151  CYRILLIC CAPITAL LETTER CHE */
&values[305], /* 152  CYRILLIC CAPITAL LETTER SHA */
&values[307], /* 153  CYRILLIC CAPITAL LETTER SHCHA */
&values[309], /* 154  CYRILLIC CAPITAL LETTER HARD SIGN */
&values[311], /* 155  CYRILLIC CAPITAL LETTER YERU */
&values[313], /* 156  CYRILLIC CAPITAL LETTER SOFT SIGN */
&values[315], /* 157  CYRILLIC CAPITAL LETTER E */
&values[317], /* 158  CYRILLIC CAPITAL LETTER YU */
&values[319], /* 159  CYRILLIC CAPITAL LETTER YA */
&values[321], /* 160  CYRILLIC SMALL LETTER A */
&values[323], /* 161  CYRILLIC SMALL LETTER BE */
&values[325], /* 162  CYRILLIC SMALL LETTER VE */
&values[327], /* 163  CYRILLIC SMALL LETTER GHE */
&values[329], /* 164  CYRILLIC SMALL LETTER DE */
&values[331], /* 165  CYRILLIC SMALL LETTER IE */
&values[333], /* 166  CYRILLIC SMALL LETTER ZHE */
&values[335], /* 167  CYRILLIC SMALL LETTER ZE */
&values[337], /* 168  CYRILLIC SMALL LETTER I */
&values[339], /* 169  CYRILLIC SMALL LETTER SHORT I */
&values[341], /* 170  CYRILLIC SMALL LETTER KA */
&values[343], /* 171  CYRILLIC SMALL LETTER EL */
&values[345], /* 172  CYRILLIC SMALL LETTER EM */
&values[347], /* 173  CYRILLIC SMALL LETTER EN */
&values[349], /* 174  CYRILLIC SMALL LETTER O */
&values[351], /* 175  CYRILLIC SMALL LETTER PE */
&values[353], /* 176  LIGHT SHADE */
&values[355], /* 177  MEDIUM SHADE */
&values[357], /* 178  DARK SHADE */
&values[359], /* 179  BOX DRAWINGS LIGHT VERTICAL */
&values[361], /* 180  BOX DRAWINGS LIGHT VERTICAL AND LEFT */
&values[363], /* 181  BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE */
&values[365], /* 182  BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE */
&values[367], /* 183  BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE */
&values[369], /* 184  BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE */
&values[371], /* 185  BOX DRAWINGS DOUBLE VERTICAL AND LEFT */
&values[373], /* 186  BOX DRAWINGS DOUBLE VERTICAL */
&values[375], /* 187  BOX DRAWINGS DOUBLE DOWN AND LEFT */
&values[377], /* 188  BOX DRAWINGS DOUBLE UP AND LEFT */
&values[379], /* 189  BOX DRAWINGS UP DOUBLE AND LEFT SINGLE */
&values[381], /* 190  BOX DRAWINGS UP SINGLE AND LEFT DOUBLE */
&values[383], /* 191  BOX DRAWINGS LIGHT DOWN AND LEFT */
&values[385], /* 192  BOX DRAWINGS LIGHT UP AND RIGHT */
&values[387], /* 193  BOX DRAWINGS LIGHT UP AND HORIZONTAL */
&values[389], /* 194  BOX DRAWINGS LIGHT DOWN AND HORIZONTAL */
&values[391], /* 195  BOX DRAWINGS LIGHT VERTICAL AND RIGHT */
&values[393], /* 196  BOX DRAWINGS LIGHT HORIZONTAL */
&values[395], /* 197  BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL */
&values[397], /* 198  BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE */
&values[399], /* 199  BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE */
&values[401], /* 200  BOX DRAWINGS DOUBLE UP AND RIGHT */
&values[403], /* 201  BOX DRAWINGS DOUBLE DOWN AND RIGHT */
&values[405], /* 202  BOX DRAWINGS DOUBLE UP AND HORIZONTAL */
&values[407], /* 203  BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL */
&values[409], /* 204  BOX DRAWINGS DOUBLE VERTICAL AND RIGHT */
&values[411], /* 205  BOX DRAWINGS DOUBLE HORIZONTAL */
&values[413], /* 206  BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL */
&values[415], /* 207  BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE */
&values[417], /* 208  BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE */
&values[419], /* 209  BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE */
&values[421], /* 210  BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE */
&values[423], /* 211  BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE */
&values[425], /* 212  BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE */
&values[427], /* 213  BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE */
&values[429], /* 214  BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE */
&values[431], /* 215  BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE */
&values[433], /* 216  BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE */
&values[435], /* 217  BOX DRAWINGS LIGHT UP AND LEFT */
&values[437], /* 218  BOX DRAWINGS LIGHT DOWN AND RIGHT */
&values[439], /* 219  FULL BLOCK */
&values[441], /* 220  LOWER HALF BLOCK */
&values[443], /* 221  LEFT HALF BLOCK */
&values[445], /* 222  RIGHT HALF BLOCK */
&values[447], /* 223  UPPER HALF BLOCK */
&values[449], /* 224  CYRILLIC SMALL LETTER ER */
&values[451], /* 225  CYRILLIC SMALL LETTER ES */
&values[453], /* 226  CYRILLIC SMALL LETTER TE */
&values[455], /* 227  CYRILLIC SMALL LETTER U */
&values[457], /* 228  CYRILLIC SMALL LETTER EF */
&values[459], /* 229  CYRILLIC SMALL LETTER HA */
&values[461], /* 230  CYRILLIC SMALL LETTER TSE */
&values[463], /* 231  CYRILLIC SMALL LETTER CHE */
&values[465], /* 232  CYRILLIC SMALL LETTER SHA */
&values[467], /* 233  CYRILLIC SMALL LETTER SHCHA */
&values[469], /* 234  CYRILLIC SMALL LETTER HARD SIGN */
&values[471], /* 235  CYRILLIC SMALL LETTER YERU */
&values[473], /* 236  CYRILLIC SMALL LETTER SOFT SIGN */
&values[475], /* 237  CYRILLIC SMALL LETTER E */
&values[477], /* 238  CYRILLIC SMALL LETTER YU */
&values[479], /* 239  CYRILLIC SMALL LETTER YA */
&values[481], /* 240  CYRILLIC CAPITAL LETTER IO */
&values[483], /* 241  CYRILLIC SMALL LETTER IO */
&values[485], /* 242  CYRILLIC CAPITAL LETTER UKRAINIAN IE */
&values[487], /* 243  CYRILLIC SMALL LETTER UKRAINIAN IE */
&values[489], /* 244  CYRILLIC CAPITAL LETTER YI */
&values[491], /* 245  CYRILLIC SMALL LETTER YI */
&values[493], /* 246  CYRILLIC CAPITAL LETTER SHORT U */
&values[495], /* 247  CYRILLIC SMALL LETTER SHORT U */
&values[497], /* 248  DEGREE SIGN */
&values[499], /* 249  BULLET OPERATOR */
&values[501], /* 250  MIDDLE DOT */
&values[503], /* 251  SQUARE ROOT */
&values[505], /* 252  NUMERO SIGN */
&values[507], /* 253  CURRENCY SIGN */
&values[509], /* 254  BLACK SQUARE */
&values[511], /* 255  NO-BREAK SPACE */
}};
