/* This file was autogenerated from the file 
 * CP869.TXT from UNICODE.ORG */

/*     Name:     cp869_DOSGreek2 to Unicode table */
/*     Unicode version: 2.0 */
/*     Table version: 2.00 */
/*     Table format:  Format A */
/*     Date:          04/24/96 */
/*     Authors:       Lori Brownell <loribr@microsoft.com> */
/*                    K.D. Chang    <a-kchang@microsoft.com> */
/*     General notes: none */
/*     Format: Three tab-separated columns */
/*         Column #1 is the cp869_DOSGreek2 code (in hex) */
/*         Column #2 is the Unicode (in hex as 0xXXXX) */
/*         Column #3 is the Unicode name (follows a comment sign, '#') */
/*     The entries are in cp869_DOSGreek2 order */
/*  first 32 positions of cp437 */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0xfffd, 0xffff, 0x263a, 0xffff, 0x263b, 0xffff, 0x2665, 
0xffff, 0x2666, 0xffff, 0x2663, 0xffff, 0x2660, 0xffff, 0x2022, 
0xffff, 0x25d8, 0xffff, 0x25cb, 0xffff, 0x25d9, 0xffff, 0x2642, 
0xffff, 0x2640, 0xffff, 0x266a, 0xffff, 0x266b, 0xffff, 0x263c, 
0xffff, 0x25ba, 0xffff, 0x25c4, 0xffff, 0x2195, 0xffff, 0x203c, 
0xffff, 0x00b6, 0xffff, 0x00a7, 0xffff, 0x25ac, 0xffff, 0x21a8, 
0xffff, 0x2191, 0xffff, 0x2193, 0xffff, 0x2192, 0xffff, 0x2190, 
0xffff, 0x221f, 0xffff, 0x2194, 0xffff, 0x25b2, 0xffff, 0x25bc, 
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0x2302, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0386, 
0xffff, 0xffff, 0x00b7, 0xffff, 0x00ac, 0xffff, 0x00a6, 0xffff, 
0x2018, 0xffff, 0x2019, 0xffff, 0x0388, 0xffff, 0x2015, 0xffff, 
0x0389, 0xffff, 0x038a, 0xffff, 0x03aa, 0xffff, 0x038c, 0xffff, 
0xffff, 0xffff, 0x038e, 0xffff, 0x03ab, 0xffff, 0x00a9, 0xffff, 
0x038f, 0xffff, 0x00b2, 0xffff, 0x00b3, 0xffff, 0x03ac, 0xffff, 
0x00a3, 0xffff, 0x03ad, 0xffff, 0x03ae, 0xffff, 0x03af, 0xffff, 
0x03ca, 0xffff, 0x0390, 0xffff, 0x03cc, 0xffff, 0x03cd, 0xffff, 
0x0391, 0xffff, 0x0392, 0xffff, 0x0393, 0xffff, 0x0394, 0xffff, 
0x0395, 0xffff, 0x0396, 0xffff, 0x0397, 0xffff, 0x00bd, 0xffff, 
0x0398, 0xffff, 0x0399, 0xffff, 0x00ab, 0xffff, 0x00bb, 0xffff, 
0x2591, 0xffff, 0x2592, 0xffff, 0x2593, 0xffff, 0x2502, 0xffff, 
0x2524, 0xffff, 0x039a, 0xffff, 0x039b, 0xffff, 0x039c, 0xffff, 
0x039d, 0xffff, 0x2563, 0xffff, 0x2551, 0xffff, 0x2557, 0xffff, 
0x255d, 0xffff, 0x039e, 0xffff, 0x039f, 0xffff, 0x2510, 0xffff, 
0x2514, 0xffff, 0x2534, 0xffff, 0x252c, 0xffff, 0x251c, 0xffff, 
0x2500, 0xffff, 0x253c, 0xffff, 0x03a0, 0xffff, 0x03a1, 0xffff, 
0x255a, 0xffff, 0x2554, 0xffff, 0x2569, 0xffff, 0x2566, 0xffff, 
0x2560, 0xffff, 0x2550, 0xffff, 0x256c, 0xffff, 0x03a3, 0xffff, 
0x03a4, 0xffff, 0x03a5, 0xffff, 0x03a6, 0xffff, 0x03a7, 0xffff, 
0x03a8, 0xffff, 0x03a9, 0xffff, 0x03b1, 0xffff, 0x03b2, 0xffff, 
0x03b3, 0xffff, 0x2518, 0xffff, 0x250c, 0xffff, 0x2588, 0xffff, 
0x2584, 0xffff, 0x03b4, 0xffff, 0x03b5, 0xffff, 0x2580, 0xffff, 
0x03b6, 0xffff, 0x03b7, 0xffff, 0x03b8, 0xffff, 0x03b9, 0xffff, 
0x03ba, 0xffff, 0x03bb, 0xffff, 0x03bc, 0xffff, 0x03bd, 0xffff, 
0x03be, 0xffff, 0x03bf, 0xffff, 0x03c0, 0xffff, 0x03c1, 0xffff, 
0x03c3, 0xffff, 0x03c2, 0xffff, 0x03c4, 0xffff, 0x0384, 0xffff, 
0x00ad, 0xffff, 0x00b1, 0xffff, 0x03c5, 0xffff, 0x03c6, 0xffff, 
0x03c7, 0xffff, 0x00a7, 0xffff, 0x03c8, 0xffff, 0x0385, 0xffff, 
0x00b0, 0xffff, 0x00a8, 0xffff, 0x03c9, 0xffff, 0x03cb, 0xffff, 
0x03b0, 0xffff, 0x03ce, 0xffff, 0x25a0, 0xffff, 0x00a0, 0xffff, 
};

struct psf_mapping256 m_CP869 = { "CP869", 
256, {
&values[1], /* 0  */
&values[3], /* 1  */
&values[5], /* 2  */
&values[7], /* 3  */
&values[9], /* 4  */
&values[11], /* 5  */
&values[13], /* 6  */
&values[15], /* 7  */
&values[17], /* 8  */
&values[19], /* 9  */
&values[21], /* 10  */
&values[23], /* 11  */
&values[25], /* 12  */
&values[27], /* 13  */
&values[29], /* 14  */
&values[31], /* 15  */
&values[33], /* 16  */
&values[35], /* 17  */
&values[37], /* 18  */
&values[39], /* 19  */
&values[41], /* 20  */
&values[43], /* 21  */
&values[45], /* 22  */
&values[47], /* 23  */
&values[49], /* 24  */
&values[51], /* 25  */
&values[53], /* 26  */
&values[55], /* 27  */
&values[57], /* 28  */
&values[59], /* 29  */
&values[61], /* 30  */
&values[63], /* 31  */
&values[65], /* 32 SPACE */
&values[67], /* 33 EXCLAMATION MARK */
&values[69], /* 34 QUOTATION MARK */
&values[71], /* 35 NUMBER SIGN */
&values[73], /* 36 DOLLAR SIGN */
&values[75], /* 37 PERCENT SIGN */
&values[77], /* 38 AMPERSAND */
&values[79], /* 39 APOSTROPHE */
&values[81], /* 40 LEFT PARENTHESIS */
&values[83], /* 41 RIGHT PARENTHESIS */
&values[85], /* 42 ASTERISK */
&values[87], /* 43 PLUS SIGN */
&values[89], /* 44 COMMA */
&values[91], /* 45 HYPHEN-MINUS */
&values[93], /* 46 FULL STOP */
&values[95], /* 47 SOLIDUS */
&values[97], /* 48 DIGIT ZERO */
&values[99], /* 49 DIGIT ONE */
&values[101], /* 50 DIGIT TWO */
&values[103], /* 51 DIGIT THREE */
&values[105], /* 52 DIGIT FOUR */
&values[107], /* 53 DIGIT FIVE */
&values[109], /* 54 DIGIT SIX */
&values[111], /* 55 DIGIT SEVEN */
&values[113], /* 56 DIGIT EIGHT */
&values[115], /* 57 DIGIT NINE */
&values[117], /* 58 COLON */
&values[119], /* 59 SEMICOLON */
&values[121], /* 60 LESS-THAN SIGN */
&values[123], /* 61 EQUALS SIGN */
&values[125], /* 62 GREATER-THAN SIGN */
&values[127], /* 63 QUESTION MARK */
&values[129], /* 64 COMMERCIAL AT */
&values[131], /* 65 LATIN CAPITAL LETTER A */
&values[133], /* 66 LATIN CAPITAL LETTER B */
&values[135], /* 67 LATIN CAPITAL LETTER C */
&values[137], /* 68 LATIN CAPITAL LETTER D */
&values[139], /* 69 LATIN CAPITAL LETTER E */
&values[141], /* 70 LATIN CAPITAL LETTER F */
&values[143], /* 71 LATIN CAPITAL LETTER G */
&values[145], /* 72 LATIN CAPITAL LETTER H */
&values[147], /* 73 LATIN CAPITAL LETTER I */
&values[149], /* 74 LATIN CAPITAL LETTER J */
&values[151], /* 75 LATIN CAPITAL LETTER K */
&values[153], /* 76 LATIN CAPITAL LETTER L */
&values[155], /* 77 LATIN CAPITAL LETTER M */
&values[157], /* 78 LATIN CAPITAL LETTER N */
&values[159], /* 79 LATIN CAPITAL LETTER O */
&values[161], /* 80 LATIN CAPITAL LETTER P */
&values[163], /* 81 LATIN CAPITAL LETTER Q */
&values[165], /* 82 LATIN CAPITAL LETTER R */
&values[167], /* 83 LATIN CAPITAL LETTER S */
&values[169], /* 84 LATIN CAPITAL LETTER T */
&values[171], /* 85 LATIN CAPITAL LETTER U */
&values[173], /* 86 LATIN CAPITAL LETTER V */
&values[175], /* 87 LATIN CAPITAL LETTER W */
&values[177], /* 88 LATIN CAPITAL LETTER X */
&values[179], /* 89 LATIN CAPITAL LETTER Y */
&values[181], /* 90 LATIN CAPITAL LETTER Z */
&values[183], /* 91 LEFT SQUARE BRACKET */
&values[185], /* 92 REVERSE SOLIDUS */
&values[187], /* 93 RIGHT SQUARE BRACKET */
&values[189], /* 94 CIRCUMFLEX ACCENT */
&values[191], /* 95 LOW LINE */
&values[193], /* 96 GRAVE ACCENT */
&values[195], /* 97 LATIN SMALL LETTER A */
&values[197], /* 98 LATIN SMALL LETTER B */
&values[199], /* 99 LATIN SMALL LETTER C */
&values[201], /* 100 LATIN SMALL LETTER D */
&values[203], /* 101 LATIN SMALL LETTER E */
&values[205], /* 102 LATIN SMALL LETTER F */
&values[207], /* 103 LATIN SMALL LETTER G */
&values[209], /* 104 LATIN SMALL LETTER H */
&values[211], /* 105 LATIN SMALL LETTER I */
&values[213], /* 106 LATIN SMALL LETTER J */
&values[215], /* 107 LATIN SMALL LETTER K */
&values[217], /* 108 LATIN SMALL LETTER L */
&values[219], /* 109 LATIN SMALL LETTER M */
&values[221], /* 110 LATIN SMALL LETTER N */
&values[223], /* 111 LATIN SMALL LETTER O */
&values[225], /* 112 LATIN SMALL LETTER P */
&values[227], /* 113 LATIN SMALL LETTER Q */
&values[229], /* 114 LATIN SMALL LETTER R */
&values[231], /* 115 LATIN SMALL LETTER S */
&values[233], /* 116 LATIN SMALL LETTER T */
&values[235], /* 117 LATIN SMALL LETTER U */
&values[237], /* 118 LATIN SMALL LETTER V */
&values[239], /* 119 LATIN SMALL LETTER W */
&values[241], /* 120 LATIN SMALL LETTER X */
&values[243], /* 121 LATIN SMALL LETTER Y */
&values[245], /* 122 LATIN SMALL LETTER Z */
&values[247], /* 123 LEFT CURLY BRACKET */
&values[249], /* 124 VERTICAL LINE */
&values[251], /* 125 RIGHT CURLY BRACKET */
&values[253], /* 126 TILDE */
&values[255], /* 127 HOUSE */
&values[257], /* 128 UNDEFINED */
&values[258], /* 129 UNDEFINED */
&values[259], /* 130 UNDEFINED */
&values[260], /* 131 UNDEFINED */
&values[261], /* 132 UNDEFINED */
&values[262], /* 133 UNDEFINED */
&values[263], /* 134 GREEK CAPITAL LETTER ALPHA WITH TONOS */
&values[265], /* 135 UNDEFINED */
&values[266], /* 136 MIDDLE DOT */
&values[268], /* 137 NOT SIGN */
&values[270], /* 138 BROKEN BAR */
&values[272], /* 139 LEFT SINGLE QUOTATION MARK */
&values[274], /* 140 RIGHT SINGLE QUOTATION MARK */
&values[276], /* 141 GREEK CAPITAL LETTER EPSILON WITH TONOS */
&values[278], /* 142 HORIZONTAL BAR */
&values[280], /* 143 GREEK CAPITAL LETTER ETA WITH TONOS */
&values[282], /* 144 GREEK CAPITAL LETTER IOTA WITH TONOS */
&values[284], /* 145 GREEK CAPITAL LETTER IOTA WITH DIALYTIKA */
&values[286], /* 146 GREEK CAPITAL LETTER OMICRON WITH TONOS */
&values[288], /* 147 UNDEFINED */
&values[289], /* 148 UNDEFINED */
&values[290], /* 149 GREEK CAPITAL LETTER UPSILON WITH TONOS */
&values[292], /* 150 GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA */
&values[294], /* 151 COPYRIGHT SIGN */
&values[296], /* 152 GREEK CAPITAL LETTER OMEGA WITH TONOS */
&values[298], /* 153 SUPERSCRIPT TWO */
&values[300], /* 154 SUPERSCRIPT THREE */
&values[302], /* 155 GREEK SMALL LETTER ALPHA WITH TONOS */
&values[304], /* 156 POUND SIGN */
&values[306], /* 157 GREEK SMALL LETTER EPSILON WITH TONOS */
&values[308], /* 158 GREEK SMALL LETTER ETA WITH TONOS */
&values[310], /* 159 GREEK SMALL LETTER IOTA WITH TONOS */
&values[312], /* 160 GREEK SMALL LETTER IOTA WITH DIALYTIKA */
&values[314], /* 161 GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS */
&values[316], /* 162 GREEK SMALL LETTER OMICRON WITH TONOS */
&values[318], /* 163 GREEK SMALL LETTER UPSILON WITH TONOS */
&values[320], /* 164 GREEK CAPITAL LETTER ALPHA */
&values[322], /* 165 GREEK CAPITAL LETTER BETA */
&values[324], /* 166 GREEK CAPITAL LETTER GAMMA */
&values[326], /* 167 GREEK CAPITAL LETTER DELTA */
&values[328], /* 168 GREEK CAPITAL LETTER EPSILON */
&values[330], /* 169 GREEK CAPITAL LETTER ZETA */
&values[332], /* 170 GREEK CAPITAL LETTER ETA */
&values[334], /* 171 VULGAR FRACTION ONE HALF */
&values[336], /* 172 GREEK CAPITAL LETTER THETA */
&values[338], /* 173 GREEK CAPITAL LETTER IOTA */
&values[340], /* 174 LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[342], /* 175 RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
&values[344], /* 176 LIGHT SHADE */
&values[346], /* 177 MEDIUM SHADE */
&values[348], /* 178 DARK SHADE */
&values[350], /* 179 BOX DRAWINGS LIGHT VERTICAL */
&values[352], /* 180 BOX DRAWINGS LIGHT VERTICAL AND LEFT */
&values[354], /* 181 GREEK CAPITAL LETTER KAPPA */
&values[356], /* 182 GREEK CAPITAL LETTER LAMDA */
&values[358], /* 183 GREEK CAPITAL LETTER MU */
&values[360], /* 184 GREEK CAPITAL LETTER NU */
&values[362], /* 185 BOX DRAWINGS DOUBLE VERTICAL AND LEFT */
&values[364], /* 186 BOX DRAWINGS DOUBLE VERTICAL */
&values[366], /* 187 BOX DRAWINGS DOUBLE DOWN AND LEFT */
&values[368], /* 188 BOX DRAWINGS DOUBLE UP AND LEFT */
&values[370], /* 189 GREEK CAPITAL LETTER XI */
&values[372], /* 190 GREEK CAPITAL LETTER OMICRON */
&values[374], /* 191 BOX DRAWINGS LIGHT DOWN AND LEFT */
&values[376], /* 192 BOX DRAWINGS LIGHT UP AND RIGHT */
&values[378], /* 193 BOX DRAWINGS LIGHT UP AND HORIZONTAL */
&values[380], /* 194 BOX DRAWINGS LIGHT DOWN AND HORIZONTAL */
&values[382], /* 195 BOX DRAWINGS LIGHT VERTICAL AND RIGHT */
&values[384], /* 196 BOX DRAWINGS LIGHT HORIZONTAL */
&values[386], /* 197 BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL */
&values[388], /* 198 GREEK CAPITAL LETTER PI */
&values[390], /* 199 GREEK CAPITAL LETTER RHO */
&values[392], /* 200 BOX DRAWINGS DOUBLE UP AND RIGHT */
&values[394], /* 201 BOX DRAWINGS DOUBLE DOWN AND RIGHT */
&values[396], /* 202 BOX DRAWINGS DOUBLE UP AND HORIZONTAL */
&values[398], /* 203 BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL */
&values[400], /* 204 BOX DRAWINGS DOUBLE VERTICAL AND RIGHT */
&values[402], /* 205 BOX DRAWINGS DOUBLE HORIZONTAL */
&values[404], /* 206 BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL */
&values[406], /* 207 GREEK CAPITAL LETTER SIGMA */
&values[408], /* 208 GREEK CAPITAL LETTER TAU */
&values[410], /* 209 GREEK CAPITAL LETTER UPSILON */
&values[412], /* 210 GREEK CAPITAL LETTER PHI */
&values[414], /* 211 GREEK CAPITAL LETTER CHI */
&values[416], /* 212 GREEK CAPITAL LETTER PSI */
&values[418], /* 213 GREEK CAPITAL LETTER OMEGA */
&values[420], /* 214 GREEK SMALL LETTER ALPHA */
&values[422], /* 215 GREEK SMALL LETTER BETA */
&values[424], /* 216 GREEK SMALL LETTER GAMMA */
&values[426], /* 217 BOX DRAWINGS LIGHT UP AND LEFT */
&values[428], /* 218 BOX DRAWINGS LIGHT DOWN AND RIGHT */
&values[430], /* 219 FULL BLOCK */
&values[432], /* 220 LOWER HALF BLOCK */
&values[434], /* 221 GREEK SMALL LETTER DELTA */
&values[436], /* 222 GREEK SMALL LETTER EPSILON */
&values[438], /* 223 UPPER HALF BLOCK */
&values[440], /* 224 GREEK SMALL LETTER ZETA */
&values[442], /* 225 GREEK SMALL LETTER ETA */
&values[444], /* 226 GREEK SMALL LETTER THETA */
&values[446], /* 227 GREEK SMALL LETTER IOTA */
&values[448], /* 228 GREEK SMALL LETTER KAPPA */
&values[450], /* 229 GREEK SMALL LETTER LAMDA */
&values[452], /* 230 GREEK SMALL LETTER MU */
&values[454], /* 231 GREEK SMALL LETTER NU */
&values[456], /* 232 GREEK SMALL LETTER XI */
&values[458], /* 233 GREEK SMALL LETTER OMICRON */
&values[460], /* 234 GREEK SMALL LETTER PI */
&values[462], /* 235 GREEK SMALL LETTER RHO */
&values[464], /* 236 GREEK SMALL LETTER SIGMA */
&values[466], /* 237 GREEK SMALL LETTER FINAL SIGMA */
&values[468], /* 238 GREEK SMALL LETTER TAU */
&values[470], /* 239 GREEK TONOS */
&values[472], /* 240 SOFT HYPHEN */
&values[474], /* 241 PLUS-MINUS SIGN */
&values[476], /* 242 GREEK SMALL LETTER UPSILON */
&values[478], /* 243 GREEK SMALL LETTER PHI */
&values[480], /* 244 GREEK SMALL LETTER CHI */
&values[482], /* 245 SECTION SIGN */
&values[484], /* 246 GREEK SMALL LETTER PSI */
&values[486], /* 247 GREEK DIALYTIKA TONOS */
&values[488], /* 248 DEGREE SIGN */
&values[490], /* 249 DIAERESIS */
&values[492], /* 250 GREEK SMALL LETTER OMEGA */
&values[494], /* 251 GREEK SMALL LETTER UPSILON WITH DIALYTIKA */
&values[496], /* 252 GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS */
&values[498], /* 253 GREEK SMALL LETTER OMEGA WITH TONOS */
&values[500], /* 254 BLACK SQUARE */
&values[502], /* 255 NO-BREAK SPACE */
}};
