/* This file was autogenerated from the file 
 * CP864.TXT from UNICODE.ORG */

/*     Name:     cp864_DOSArabic to Unicode table */
/*     Unicode version: 2.0 */
/*     Table version: 2.00 */
/*     Table format:  Format A */
/*     Date:          04/24/96 */
/*     Authors:       Lori Brownell <loribr@microsoft.com> */
/*                    K.D. Chang    <a-kchang@microsoft.com> */
/*     General notes: none */
/*     Format: Three tab-separated columns */
/*         Column #1 is the cp864_DOSArabic code (in hex) */
/*         Column #2 is the Unicode (in hex as 0xXXXX) */
/*         Column #3 is the Unicode name (follows a comment sign, '#') */
/*     The entries are in cp864_DOSArabic order */
/*  first 32 positions of cp437 */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0xfffd, 0xffff, 0x263a, 0xffff, 0x263b, 0xffff, 0x2665, 
0xffff, 0x2666, 0xffff, 0x2663, 0xffff, 0x2660, 0xffff, 0x2022, 
0xffff, 0x25d8, 0xffff, 0x25cb, 0xffff, 0x25d9, 0xffff, 0x2642, 
0xffff, 0x2640, 0xffff, 0x266a, 0xffff, 0x266b, 0xffff, 0x263c, 
0xffff, 0x25ba, 0xffff, 0x25c4, 0xffff, 0x2195, 0xffff, 0x203c, 
0xffff, 0x00b6, 0xffff, 0x00a7, 0xffff, 0x25ac, 0xffff, 0x21a8, 
0xffff, 0x2191, 0xffff, 0x2193, 0xffff, 0x2192, 0xffff, 0x2190, 
0xffff, 0x221f, 0xffff, 0x2194, 0xffff, 0x25b2, 0xffff, 0x25bc, 
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x066a, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0x2302, 
0xffff, 0x00b0, 0xffff, 0x00b7, 0xffff, 0x2219, 0xffff, 0x221a, 
0xffff, 0x2592, 0xffff, 0x2500, 0xffff, 0x2502, 0xffff, 0x253c, 
0xffff, 0x2524, 0xffff, 0x252c, 0xffff, 0x251c, 0xffff, 0x2534, 
0xffff, 0x2510, 0xffff, 0x250c, 0xffff, 0x2514, 0xffff, 0x2518, 
0xffff, 0x03b2, 0xffff, 0x221e, 0xffff, 0x03c6, 0xffff, 0x00b1, 
0xffff, 0x00bd, 0xffff, 0x00bc, 0xffff, 0x2248, 0xffff, 0x00ab, 
0xffff, 0x00bb, 0xffff, 0xfef7, 0xffff, 0xfef8, 0xffff, 0xffff, 
0xffff, 0xfefb, 0xffff, 0xfefc, 0xffff, 0xffff, 0x00a0, 0xffff, 
0x00ad, 0xffff, 0xfe82, 0xffff, 0x00a3, 0xffff, 0x00a4, 0xffff, 
0xfe84, 0xffff, 0xffff, 0xffff, 0xfe8e, 0xffff, 0xfe8f, 0xffff, 
0xfe95, 0xffff, 0xfe99, 0xffff, 0x060c, 0xffff, 0xfe9d, 0xffff, 
0xfea1, 0xffff, 0xfea5, 0xffff, 0x0660, 0xffff, 0x0661, 0xffff, 
0x0662, 0xffff, 0x0663, 0xffff, 0x0664, 0xffff, 0x0665, 0xffff, 
0x0666, 0xffff, 0x0667, 0xffff, 0x0668, 0xffff, 0x0669, 0xffff, 
0xfed1, 0xffff, 0x061b, 0xffff, 0xfeb1, 0xffff, 0xfeb5, 0xffff, 
0xfeb9, 0xffff, 0x061f, 0xffff, 0x00a2, 0xffff, 0xfe80, 0xffff, 
0xfe81, 0xffff, 0xfe83, 0xffff, 0xfe85, 0xffff, 0xfeca, 0xffff, 
0xfe8b, 0xffff, 0xfe8d, 0xffff, 0xfe91, 0xffff, 0xfe93, 0xffff, 
0xfe97, 0xffff, 0xfe9b, 0xffff, 0xfe9f, 0xffff, 0xfea3, 0xffff, 
0xfea7, 0xffff, 0xfea9, 0xffff, 0xfeab, 0xffff, 0xfead, 0xffff, 
0xfeaf, 0xffff, 0xfeb3, 0xffff, 0xfeb7, 0xffff, 0xfebb, 0xffff, 
0xfebf, 0xffff, 0xfec1, 0xffff, 0xfec5, 0xffff, 0xfecb, 0xffff, 
0xfecf, 0xffff, 0x00a6, 0xffff, 0x00ac, 0xffff, 0x00f7, 0xffff, 
0x00d7, 0xffff, 0xfec9, 0xffff, 0x0640, 0xffff, 0xfed3, 0xffff, 
0xfed7, 0xffff, 0xfedb, 0xffff, 0xfedf, 0xffff, 0xfee3, 0xffff, 
0xfee7, 0xffff, 0xfeeb, 0xffff, 0xfeed, 0xffff, 0xfeef, 0xffff, 
0xfef3, 0xffff, 0xfebd, 0xffff, 0xfecc, 0xffff, 0xfece, 0xffff, 
0xfecd, 0xffff, 0xfee1, 0xffff, 0xfe7d, 0xffff, 0x0651, 0xffff, 
0xfee5, 0xffff, 0xfee9, 0xffff, 0xfeec, 0xffff, 0xfef0, 0xffff, 
0xfef2, 0xffff, 0xfed0, 0xffff, 0xfed5, 0xffff, 0xfef5, 0xffff, 
0xfef6, 0xffff, 0xfedd, 0xffff, 0xfed9, 0xffff, 0xfef1, 0xffff, 
0x25a0, 0xffff, 0xffff, };

struct psf_mapping256 m_CP864 = { "CP864", 
256, {
&values[1], /* 0  */
&values[3], /* 1  */
&values[5], /* 2  */
&values[7], /* 3  */
&values[9], /* 4  */
&values[11], /* 5  */
&values[13], /* 6  */
&values[15], /* 7  */
&values[17], /* 8  */
&values[19], /* 9  */
&values[21], /* 10  */
&values[23], /* 11  */
&values[25], /* 12  */
&values[27], /* 13  */
&values[29], /* 14  */
&values[31], /* 15  */
&values[33], /* 16  */
&values[35], /* 17  */
&values[37], /* 18  */
&values[39], /* 19  */
&values[41], /* 20  */
&values[43], /* 21  */
&values[45], /* 22  */
&values[47], /* 23  */
&values[49], /* 24  */
&values[51], /* 25  */
&values[53], /* 26  */
&values[55], /* 27  */
&values[57], /* 28  */
&values[59], /* 29  */
&values[61], /* 30  */
&values[63], /* 31  */
&values[65], /* 32 SPACE */
&values[67], /* 33 EXCLAMATION MARK */
&values[69], /* 34 QUOTATION MARK */
&values[71], /* 35 NUMBER SIGN */
&values[73], /* 36 DOLLAR SIGN */
&values[75], /* 37 ARABIC PERCENT SIGN */
&values[77], /* 38 AMPERSAND */
&values[79], /* 39 APOSTROPHE */
&values[81], /* 40 LEFT PARENTHESIS */
&values[83], /* 41 RIGHT PARENTHESIS */
&values[85], /* 42 ASTERISK */
&values[87], /* 43 PLUS SIGN */
&values[89], /* 44 COMMA */
&values[91], /* 45 HYPHEN-MINUS */
&values[93], /* 46 FULL STOP */
&values[95], /* 47 SOLIDUS */
&values[97], /* 48 DIGIT ZERO */
&values[99], /* 49 DIGIT ONE */
&values[101], /* 50 DIGIT TWO */
&values[103], /* 51 DIGIT THREE */
&values[105], /* 52 DIGIT FOUR */
&values[107], /* 53 DIGIT FIVE */
&values[109], /* 54 DIGIT SIX */
&values[111], /* 55 DIGIT SEVEN */
&values[113], /* 56 DIGIT EIGHT */
&values[115], /* 57 DIGIT NINE */
&values[117], /* 58 COLON */
&values[119], /* 59 SEMICOLON */
&values[121], /* 60 LESS-THAN SIGN */
&values[123], /* 61 EQUALS SIGN */
&values[125], /* 62 GREATER-THAN SIGN */
&values[127], /* 63 QUESTION MARK */
&values[129], /* 64 COMMERCIAL AT */
&values[131], /* 65 LATIN CAPITAL LETTER A */
&values[133], /* 66 LATIN CAPITAL LETTER B */
&values[135], /* 67 LATIN CAPITAL LETTER C */
&values[137], /* 68 LATIN CAPITAL LETTER D */
&values[139], /* 69 LATIN CAPITAL LETTER E */
&values[141], /* 70 LATIN CAPITAL LETTER F */
&values[143], /* 71 LATIN CAPITAL LETTER G */
&values[145], /* 72 LATIN CAPITAL LETTER H */
&values[147], /* 73 LATIN CAPITAL LETTER I */
&values[149], /* 74 LATIN CAPITAL LETTER J */
&values[151], /* 75 LATIN CAPITAL LETTER K */
&values[153], /* 76 LATIN CAPITAL LETTER L */
&values[155], /* 77 LATIN CAPITAL LETTER M */
&values[157], /* 78 LATIN CAPITAL LETTER N */
&values[159], /* 79 LATIN CAPITAL LETTER O */
&values[161], /* 80 LATIN CAPITAL LETTER P */
&values[163], /* 81 LATIN CAPITAL LETTER Q */
&values[165], /* 82 LATIN CAPITAL LETTER R */
&values[167], /* 83 LATIN CAPITAL LETTER S */
&values[169], /* 84 LATIN CAPITAL LETTER T */
&values[171], /* 85 LATIN CAPITAL LETTER U */
&values[173], /* 86 LATIN CAPITAL LETTER V */
&values[175], /* 87 LATIN CAPITAL LETTER W */
&values[177], /* 88 LATIN CAPITAL LETTER X */
&values[179], /* 89 LATIN CAPITAL LETTER Y */
&values[181], /* 90 LATIN CAPITAL LETTER Z */
&values[183], /* 91 LEFT SQUARE BRACKET */
&values[185], /* 92 REVERSE SOLIDUS */
&values[187], /* 93 RIGHT SQUARE BRACKET */
&values[189], /* 94 CIRCUMFLEX ACCENT */
&values[191], /* 95 LOW LINE */
&values[193], /* 96 GRAVE ACCENT */
&values[195], /* 97 LATIN SMALL LETTER A */
&values[197], /* 98 LATIN SMALL LETTER B */
&values[199], /* 99 LATIN SMALL LETTER C */
&values[201], /* 100 LATIN SMALL LETTER D */
&values[203], /* 101 LATIN SMALL LETTER E */
&values[205], /* 102 LATIN SMALL LETTER F */
&values[207], /* 103 LATIN SMALL LETTER G */
&values[209], /* 104 LATIN SMALL LETTER H */
&values[211], /* 105 LATIN SMALL LETTER I */
&values[213], /* 106 LATIN SMALL LETTER J */
&values[215], /* 107 LATIN SMALL LETTER K */
&values[217], /* 108 LATIN SMALL LETTER L */
&values[219], /* 109 LATIN SMALL LETTER M */
&values[221], /* 110 LATIN SMALL LETTER N */
&values[223], /* 111 LATIN SMALL LETTER O */
&values[225], /* 112 LATIN SMALL LETTER P */
&values[227], /* 113 LATIN SMALL LETTER Q */
&values[229], /* 114 LATIN SMALL LETTER R */
&values[231], /* 115 LATIN SMALL LETTER S */
&values[233], /* 116 LATIN SMALL LETTER T */
&values[235], /* 117 LATIN SMALL LETTER U */
&values[237], /* 118 LATIN SMALL LETTER V */
&values[239], /* 119 LATIN SMALL LETTER W */
&values[241], /* 120 LATIN SMALL LETTER X */
&values[243], /* 121 LATIN SMALL LETTER Y */
&values[245], /* 122 LATIN SMALL LETTER Z */
&values[247], /* 123 LEFT CURLY BRACKET */
&values[249], /* 124 VERTICAL LINE */
&values[251], /* 125 RIGHT CURLY BRACKET */
&values[253], /* 126 TILDE */
&values[255], /* 127 HOUSE */
&values[257], /* 128 DEGREE SIGN */
&values[259], /* 129 MIDDLE DOT */
&values[261], /* 130 BULLET OPERATOR */
&values[263], /* 131 SQUARE ROOT */
&values[265], /* 132 MEDIUM SHADE */
&values[267], /* 133 FORMS LIGHT HORIZONTAL */
&values[269], /* 134 FORMS LIGHT VERTICAL */
&values[271], /* 135 FORMS LIGHT VERTICAL AND HORIZONTAL */
&values[273], /* 136 FORMS LIGHT VERTICAL AND LEFT */
&values[275], /* 137 FORMS LIGHT DOWN AND HORIZONTAL */
&values[277], /* 138 FORMS LIGHT VERTICAL AND RIGHT */
&values[279], /* 139 FORMS LIGHT UP AND HORIZONTAL */
&values[281], /* 140 FORMS LIGHT DOWN AND LEFT */
&values[283], /* 141 FORMS LIGHT DOWN AND RIGHT */
&values[285], /* 142 FORMS LIGHT UP AND RIGHT */
&values[287], /* 143 FORMS LIGHT UP AND LEFT */
&values[289], /* 144 GREEK SMALL BETA */
&values[291], /* 145 INFINITY */
&values[293], /* 146 GREEK SMALL PHI */
&values[295], /* 147 PLUS-OR-MINUS SIGN */
&values[297], /* 148 FRACTION 1/2 */
&values[299], /* 149 FRACTION 1/4 */
&values[301], /* 150 ALMOST EQUAL TO */
&values[303], /* 151 LEFT POINTING GUILLEMET */
&values[305], /* 152 RIGHT POINTING GUILLEMET */
&values[307], /* 153 ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE ISOLATED FORM */
&values[309], /* 154 ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE FINAL FORM */
&values[311], /* 155 UNDEFINED */
&values[312], /* 156 UNDEFINED */
&values[313], /* 157 ARABIC LIGATURE LAM WITH ALEF ISOLATED FORM */
&values[315], /* 158 ARABIC LIGATURE LAM WITH ALEF FINAL FORM */
&values[317], /* 159 UNDEFINED */
&values[318], /* 160 NON-BREAKING SPACE */
&values[320], /* 161 SOFT HYPHEN */
&values[322], /* 162 ARABIC LETTER ALEF WITH MADDA ABOVE FINAL FORM */
&values[324], /* 163 POUND SIGN */
&values[326], /* 164 CURRENCY SIGN */
&values[328], /* 165 ARABIC LETTER ALEF WITH HAMZA ABOVE FINAL FORM */
&values[330], /* 166 UNDEFINED */
&values[331], /* 167 UNDEFINED */
&values[332], /* 168 ARABIC LETTER ALEF FINAL FORM */
&values[334], /* 169 ARABIC LETTER BEH ISOLATED FORM */
&values[336], /* 170 ARABIC LETTER TEH ISOLATED FORM */
&values[338], /* 171 ARABIC LETTER THEH ISOLATED FORM */
&values[340], /* 172 ARABIC COMMA */
&values[342], /* 173 ARABIC LETTER JEEM ISOLATED FORM */
&values[344], /* 174 ARABIC LETTER HAH ISOLATED FORM */
&values[346], /* 175 ARABIC LETTER KHAH ISOLATED FORM */
&values[348], /* 176 ARABIC-INDIC DIGIT ZERO */
&values[350], /* 177 ARABIC-INDIC DIGIT ONE */
&values[352], /* 178 ARABIC-INDIC DIGIT TWO */
&values[354], /* 179 ARABIC-INDIC DIGIT THREE */
&values[356], /* 180 ARABIC-INDIC DIGIT FOUR */
&values[358], /* 181 ARABIC-INDIC DIGIT FIVE */
&values[360], /* 182 ARABIC-INDIC DIGIT SIX */
&values[362], /* 183 ARABIC-INDIC DIGIT SEVEN */
&values[364], /* 184 ARABIC-INDIC DIGIT EIGHT */
&values[366], /* 185 ARABIC-INDIC DIGIT NINE */
&values[368], /* 186 ARABIC LETTER FEH ISOLATED FORM */
&values[370], /* 187 ARABIC SEMICOLON */
&values[372], /* 188 ARABIC LETTER SEEN ISOLATED FORM */
&values[374], /* 189 ARABIC LETTER SHEEN ISOLATED FORM */
&values[376], /* 190 ARABIC LETTER SAD ISOLATED FORM */
&values[378], /* 191 ARABIC QUESTION MARK */
&values[380], /* 192 CENT SIGN */
&values[382], /* 193 ARABIC LETTER HAMZA ISOLATED FORM */
&values[384], /* 194 ARABIC LETTER ALEF WITH MADDA ABOVE ISOLATED FORM */
&values[386], /* 195 ARABIC LETTER ALEF WITH HAMZA ABOVE ISOLATED FORM */
&values[388], /* 196 ARABIC LETTER WAW WITH HAMZA ABOVE ISOLATED FORM */
&values[390], /* 197 ARABIC LETTER AIN FINAL FORM */
&values[392], /* 198 ARABIC LETTER YEH WITH HAMZA ABOVE INITIAL FORM */
&values[394], /* 199 ARABIC LETTER ALEF ISOLATED FORM */
&values[396], /* 200 ARABIC LETTER BEH INITIAL FORM */
&values[398], /* 201 ARABIC LETTER TEH MARBUTA ISOLATED FORM */
&values[400], /* 202 ARABIC LETTER TEH INITIAL FORM */
&values[402], /* 203 ARABIC LETTER THEH INITIAL FORM */
&values[404], /* 204 ARABIC LETTER JEEM INITIAL FORM */
&values[406], /* 205 ARABIC LETTER HAH INITIAL FORM */
&values[408], /* 206 ARABIC LETTER KHAH INITIAL FORM */
&values[410], /* 207 ARABIC LETTER DAL ISOLATED FORM */
&values[412], /* 208 ARABIC LETTER THAL ISOLATED FORM */
&values[414], /* 209 ARABIC LETTER REH ISOLATED FORM */
&values[416], /* 210 ARABIC LETTER ZAIN ISOLATED FORM */
&values[418], /* 211 ARABIC LETTER SEEN INITIAL FORM */
&values[420], /* 212 ARABIC LETTER SHEEN INITIAL FORM */
&values[422], /* 213 ARABIC LETTER SAD INITIAL FORM */
&values[424], /* 214 ARABIC LETTER DAD INITIAL FORM */
&values[426], /* 215 ARABIC LETTER TAH ISOLATED FORM */
&values[428], /* 216 ARABIC LETTER ZAH ISOLATED FORM */
&values[430], /* 217 ARABIC LETTER AIN INITIAL FORM */
&values[432], /* 218 ARABIC LETTER GHAIN INITIAL FORM */
&values[434], /* 219 BROKEN VERTICAL BAR */
&values[436], /* 220 NOT SIGN */
&values[438], /* 221 DIVISION SIGN */
&values[440], /* 222 MULTIPLICATION SIGN */
&values[442], /* 223 ARABIC LETTER AIN ISOLATED FORM */
&values[444], /* 224 ARABIC TATWEEL */
&values[446], /* 225 ARABIC LETTER FEH INITIAL FORM */
&values[448], /* 226 ARABIC LETTER QAF INITIAL FORM */
&values[450], /* 227 ARABIC LETTER KAF INITIAL FORM */
&values[452], /* 228 ARABIC LETTER LAM INITIAL FORM */
&values[454], /* 229 ARABIC LETTER MEEM INITIAL FORM */
&values[456], /* 230 ARABIC LETTER NOON INITIAL FORM */
&values[458], /* 231 ARABIC LETTER HEH INITIAL FORM */
&values[460], /* 232 ARABIC LETTER WAW ISOLATED FORM */
&values[462], /* 233 ARABIC LETTER ALEF MAKSURA ISOLATED FORM */
&values[464], /* 234 ARABIC LETTER YEH INITIAL FORM */
&values[466], /* 235 ARABIC LETTER DAD ISOLATED FORM */
&values[468], /* 236 ARABIC LETTER AIN MEDIAL FORM */
&values[470], /* 237 ARABIC LETTER GHAIN FINAL FORM */
&values[472], /* 238 ARABIC LETTER GHAIN ISOLATED FORM */
&values[474], /* 239 ARABIC LETTER MEEM ISOLATED FORM */
&values[476], /* 240 ARABIC SHADDA MEDIAL FORM */
&values[478], /* 241 ARABIC SHADDAH */
&values[480], /* 242 ARABIC LETTER NOON ISOLATED FORM */
&values[482], /* 243 ARABIC LETTER HEH ISOLATED FORM */
&values[484], /* 244 ARABIC LETTER HEH MEDIAL FORM */
&values[486], /* 245 ARABIC LETTER ALEF MAKSURA FINAL FORM */
&values[488], /* 246 ARABIC LETTER YEH FINAL FORM */
&values[490], /* 247 ARABIC LETTER GHAIN MEDIAL FORM */
&values[492], /* 248 ARABIC LETTER QAF ISOLATED FORM */
&values[494], /* 249 ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE ISOLATED FORM */
&values[496], /* 250 ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE FINAL FORM */
&values[498], /* 251 ARABIC LETTER LAM ISOLATED FORM */
&values[500], /* 252 ARABIC LETTER KAF ISOLATED FORM */
&values[502], /* 253 ARABIC LETTER YEH ISOLATED FORM */
&values[504], /* 254 BLACK SQUARE */
&values[506], /* 255 UNDEFINED */
}};
