/* This file was autogenerated from the file 
 * CP874.TXT from UNICODE.ORG */

/*     Name:     cp874 to Unicode table */
/*     Unicode version: 2.0 */
/*     Table version: 2.00 */
/*     Table format:  Format A */
/*     Date:          04/15/98 */
/*     Contact:       cpxlate@microsoft.com */
/*     General notes: none */
/*     Format: Three tab-separated columns */
/*         Column #1 is the cp874 code (in hex) */
/*         Column #2 is the Unicode (in hex as 0xXXXX) */
/*         Column #3 is the Unicode name (follows a comment sign, '#') */
/*     The entries are in cp874 order */
/*  first 32 positions of cp437 */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0xfffd, 0xffff, 0x263a, 0xffff, 0x263b, 0xffff, 0x2665, 
0xffff, 0x2666, 0xffff, 0x2663, 0xffff, 0x2660, 0xffff, 0x2022, 
0xffff, 0x25d8, 0xffff, 0x25cb, 0xffff, 0x25d9, 0xffff, 0x2642, 
0xffff, 0x2640, 0xffff, 0x266a, 0xffff, 0x266b, 0xffff, 0x263c, 
0xffff, 0x25ba, 0xffff, 0x25c4, 0xffff, 0x2195, 0xffff, 0x203c, 
0xffff, 0x00b6, 0xffff, 0x00a7, 0xffff, 0x25ac, 0xffff, 0x21a8, 
0xffff, 0x2191, 0xffff, 0x2193, 0xffff, 0x2192, 0xffff, 0x2190, 
0xffff, 0x221f, 0xffff, 0x2194, 0xffff, 0x25b2, 0xffff, 0x25bc, 
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0x2302, 
0xffff, 0x20ac, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x2026, 
0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0x2018, 0xffff, 0x2019, 0xffff, 
0x201c, 0xffff, 0x201d, 0xffff, 0x2022, 0xffff, 0x2013, 0xffff, 
0x2014, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, 0x00a0, 0xffff, 0x0e01, 0xffff, 0x0e02, 0xffff, 
0x0e03, 0xffff, 0x0e04, 0xffff, 0x0e05, 0xffff, 0x0e06, 0xffff, 
0x0e07, 0xffff, 0x0e08, 0xffff, 0x0e09, 0xffff, 0x0e0a, 0xffff, 
0x0e0b, 0xffff, 0x0e0c, 0xffff, 0x0e0d, 0xffff, 0x0e0e, 0xffff, 
0x0e0f, 0xffff, 0x0e10, 0xffff, 0x0e11, 0xffff, 0x0e12, 0xffff, 
0x0e13, 0xffff, 0x0e14, 0xffff, 0x0e15, 0xffff, 0x0e16, 0xffff, 
0x0e17, 0xffff, 0x0e18, 0xffff, 0x0e19, 0xffff, 0x0e1a, 0xffff, 
0x0e1b, 0xffff, 0x0e1c, 0xffff, 0x0e1d, 0xffff, 0x0e1e, 0xffff, 
0x0e1f, 0xffff, 0x0e20, 0xffff, 0x0e21, 0xffff, 0x0e22, 0xffff, 
0x0e23, 0xffff, 0x0e24, 0xffff, 0x0e25, 0xffff, 0x0e26, 0xffff, 
0x0e27, 0xffff, 0x0e28, 0xffff, 0x0e29, 0xffff, 0x0e2a, 0xffff, 
0x0e2b, 0xffff, 0x0e2c, 0xffff, 0x0e2d, 0xffff, 0x0e2e, 0xffff, 
0x0e2f, 0xffff, 0x0e30, 0xffff, 0x0e31, 0xffff, 0x0e32, 0xffff, 
0x0e33, 0xffff, 0x0e34, 0xffff, 0x0e35, 0xffff, 0x0e36, 0xffff, 
0x0e37, 0xffff, 0x0e38, 0xffff, 0x0e39, 0xffff, 0x0e3a, 0xffff, 
0xffff, 0xffff, 0xffff, 0xffff, 0x0e3f, 0xffff, 0x0e40, 0xffff, 
0x0e41, 0xffff, 0x0e42, 0xffff, 0x0e43, 0xffff, 0x0e44, 0xffff, 
0x0e45, 0xffff, 0x0e46, 0xffff, 0x0e47, 0xffff, 0x0e48, 0xffff, 
0x0e49, 0xffff, 0x0e4a, 0xffff, 0x0e4b, 0xffff, 0x0e4c, 0xffff, 
0x0e4d, 0xffff, 0x0e4e, 0xffff, 0x0e4f, 0xffff, 0x0e50, 0xffff, 
0x0e51, 0xffff, 0x0e52, 0xffff, 0x0e53, 0xffff, 0x0e54, 0xffff, 
0x0e55, 0xffff, 0x0e56, 0xffff, 0x0e57, 0xffff, 0x0e58, 0xffff, 
0x0e59, 0xffff, 0x0e5a, 0xffff, 0x0e5b, 0xffff, 0xffff, 0xffff, 
0xffff, 0xffff, };

struct psf_mapping256 m_CP874 = { "CP874", 
256, {
&values[1], /* 0  */
&values[3], /* 1  */
&values[5], /* 2  */
&values[7], /* 3  */
&values[9], /* 4  */
&values[11], /* 5  */
&values[13], /* 6  */
&values[15], /* 7  */
&values[17], /* 8  */
&values[19], /* 9  */
&values[21], /* 10  */
&values[23], /* 11  */
&values[25], /* 12  */
&values[27], /* 13  */
&values[29], /* 14  */
&values[31], /* 15  */
&values[33], /* 16  */
&values[35], /* 17  */
&values[37], /* 18  */
&values[39], /* 19  */
&values[41], /* 20  */
&values[43], /* 21  */
&values[45], /* 22  */
&values[47], /* 23  */
&values[49], /* 24  */
&values[51], /* 25  */
&values[53], /* 26  */
&values[55], /* 27  */
&values[57], /* 28  */
&values[59], /* 29  */
&values[61], /* 30  */
&values[63], /* 31  */
&values[65], /* 32 SPACE */
&values[67], /* 33 EXCLAMATION MARK */
&values[69], /* 34 QUOTATION MARK */
&values[71], /* 35 NUMBER SIGN */
&values[73], /* 36 DOLLAR SIGN */
&values[75], /* 37 PERCENT SIGN */
&values[77], /* 38 AMPERSAND */
&values[79], /* 39 APOSTROPHE */
&values[81], /* 40 LEFT PARENTHESIS */
&values[83], /* 41 RIGHT PARENTHESIS */
&values[85], /* 42 ASTERISK */
&values[87], /* 43 PLUS SIGN */
&values[89], /* 44 COMMA */
&values[91], /* 45 HYPHEN-MINUS */
&values[93], /* 46 FULL STOP */
&values[95], /* 47 SOLIDUS */
&values[97], /* 48 DIGIT ZERO */
&values[99], /* 49 DIGIT ONE */
&values[101], /* 50 DIGIT TWO */
&values[103], /* 51 DIGIT THREE */
&values[105], /* 52 DIGIT FOUR */
&values[107], /* 53 DIGIT FIVE */
&values[109], /* 54 DIGIT SIX */
&values[111], /* 55 DIGIT SEVEN */
&values[113], /* 56 DIGIT EIGHT */
&values[115], /* 57 DIGIT NINE */
&values[117], /* 58 COLON */
&values[119], /* 59 SEMICOLON */
&values[121], /* 60 LESS-THAN SIGN */
&values[123], /* 61 EQUALS SIGN */
&values[125], /* 62 GREATER-THAN SIGN */
&values[127], /* 63 QUESTION MARK */
&values[129], /* 64 COMMERCIAL AT */
&values[131], /* 65 LATIN CAPITAL LETTER A */
&values[133], /* 66 LATIN CAPITAL LETTER B */
&values[135], /* 67 LATIN CAPITAL LETTER C */
&values[137], /* 68 LATIN CAPITAL LETTER D */
&values[139], /* 69 LATIN CAPITAL LETTER E */
&values[141], /* 70 LATIN CAPITAL LETTER F */
&values[143], /* 71 LATIN CAPITAL LETTER G */
&values[145], /* 72 LATIN CAPITAL LETTER H */
&values[147], /* 73 LATIN CAPITAL LETTER I */
&values[149], /* 74 LATIN CAPITAL LETTER J */
&values[151], /* 75 LATIN CAPITAL LETTER K */
&values[153], /* 76 LATIN CAPITAL LETTER L */
&values[155], /* 77 LATIN CAPITAL LETTER M */
&values[157], /* 78 LATIN CAPITAL LETTER N */
&values[159], /* 79 LATIN CAPITAL LETTER O */
&values[161], /* 80 LATIN CAPITAL LETTER P */
&values[163], /* 81 LATIN CAPITAL LETTER Q */
&values[165], /* 82 LATIN CAPITAL LETTER R */
&values[167], /* 83 LATIN CAPITAL LETTER S */
&values[169], /* 84 LATIN CAPITAL LETTER T */
&values[171], /* 85 LATIN CAPITAL LETTER U */
&values[173], /* 86 LATIN CAPITAL LETTER V */
&values[175], /* 87 LATIN CAPITAL LETTER W */
&values[177], /* 88 LATIN CAPITAL LETTER X */
&values[179], /* 89 LATIN CAPITAL LETTER Y */
&values[181], /* 90 LATIN CAPITAL LETTER Z */
&values[183], /* 91 LEFT SQUARE BRACKET */
&values[185], /* 92 REVERSE SOLIDUS */
&values[187], /* 93 RIGHT SQUARE BRACKET */
&values[189], /* 94 CIRCUMFLEX ACCENT */
&values[191], /* 95 LOW LINE */
&values[193], /* 96 GRAVE ACCENT */
&values[195], /* 97 LATIN SMALL LETTER A */
&values[197], /* 98 LATIN SMALL LETTER B */
&values[199], /* 99 LATIN SMALL LETTER C */
&values[201], /* 100 LATIN SMALL LETTER D */
&values[203], /* 101 LATIN SMALL LETTER E */
&values[205], /* 102 LATIN SMALL LETTER F */
&values[207], /* 103 LATIN SMALL LETTER G */
&values[209], /* 104 LATIN SMALL LETTER H */
&values[211], /* 105 LATIN SMALL LETTER I */
&values[213], /* 106 LATIN SMALL LETTER J */
&values[215], /* 107 LATIN SMALL LETTER K */
&values[217], /* 108 LATIN SMALL LETTER L */
&values[219], /* 109 LATIN SMALL LETTER M */
&values[221], /* 110 LATIN SMALL LETTER N */
&values[223], /* 111 LATIN SMALL LETTER O */
&values[225], /* 112 LATIN SMALL LETTER P */
&values[227], /* 113 LATIN SMALL LETTER Q */
&values[229], /* 114 LATIN SMALL LETTER R */
&values[231], /* 115 LATIN SMALL LETTER S */
&values[233], /* 116 LATIN SMALL LETTER T */
&values[235], /* 117 LATIN SMALL LETTER U */
&values[237], /* 118 LATIN SMALL LETTER V */
&values[239], /* 119 LATIN SMALL LETTER W */
&values[241], /* 120 LATIN SMALL LETTER X */
&values[243], /* 121 LATIN SMALL LETTER Y */
&values[245], /* 122 LATIN SMALL LETTER Z */
&values[247], /* 123 LEFT CURLY BRACKET */
&values[249], /* 124 VERTICAL LINE */
&values[251], /* 125 RIGHT CURLY BRACKET */
&values[253], /* 126 TILDE */
&values[255], /* 127 HOUSE */
&values[257], /* 128 EURO SIGN */
&values[259], /* 129 UNDEFINED */
&values[260], /* 130 UNDEFINED */
&values[261], /* 131 UNDEFINED */
&values[262], /* 132 UNDEFINED */
&values[263], /* 133 HORIZONTAL ELLIPSIS */
&values[265], /* 134 UNDEFINED */
&values[266], /* 135 UNDEFINED */
&values[267], /* 136 UNDEFINED */
&values[268], /* 137 UNDEFINED */
&values[269], /* 138 UNDEFINED */
&values[270], /* 139 UNDEFINED */
&values[271], /* 140 UNDEFINED */
&values[272], /* 141 UNDEFINED */
&values[273], /* 142 UNDEFINED */
&values[274], /* 143 UNDEFINED */
&values[275], /* 144 UNDEFINED */
&values[276], /* 145 LEFT SINGLE QUOTATION MARK */
&values[278], /* 146 RIGHT SINGLE QUOTATION MARK */
&values[280], /* 147 LEFT DOUBLE QUOTATION MARK */
&values[282], /* 148 RIGHT DOUBLE QUOTATION MARK */
&values[284], /* 149 BULLET */
&values[286], /* 150 EN DASH */
&values[288], /* 151 EM DASH */
&values[290], /* 152 UNDEFINED */
&values[291], /* 153 UNDEFINED */
&values[292], /* 154 UNDEFINED */
&values[293], /* 155 UNDEFINED */
&values[294], /* 156 UNDEFINED */
&values[295], /* 157 UNDEFINED */
&values[296], /* 158 UNDEFINED */
&values[297], /* 159 UNDEFINED */
&values[298], /* 160 NO-BREAK SPACE */
&values[300], /* 161 THAI CHARACTER KO KAI */
&values[302], /* 162 THAI CHARACTER KHO KHAI */
&values[304], /* 163 THAI CHARACTER KHO KHUAT */
&values[306], /* 164 THAI CHARACTER KHO KHWAI */
&values[308], /* 165 THAI CHARACTER KHO KHON */
&values[310], /* 166 THAI CHARACTER KHO RAKHANG */
&values[312], /* 167 THAI CHARACTER NGO NGU */
&values[314], /* 168 THAI CHARACTER CHO CHAN */
&values[316], /* 169 THAI CHARACTER CHO CHING */
&values[318], /* 170 THAI CHARACTER CHO CHANG */
&values[320], /* 171 THAI CHARACTER SO SO */
&values[322], /* 172 THAI CHARACTER CHO CHOE */
&values[324], /* 173 THAI CHARACTER YO YING */
&values[326], /* 174 THAI CHARACTER DO CHADA */
&values[328], /* 175 THAI CHARACTER TO PATAK */
&values[330], /* 176 THAI CHARACTER THO THAN */
&values[332], /* 177 THAI CHARACTER THO NANGMONTHO */
&values[334], /* 178 THAI CHARACTER THO PHUTHAO */
&values[336], /* 179 THAI CHARACTER NO NEN */
&values[338], /* 180 THAI CHARACTER DO DEK */
&values[340], /* 181 THAI CHARACTER TO TAO */
&values[342], /* 182 THAI CHARACTER THO THUNG */
&values[344], /* 183 THAI CHARACTER THO THAHAN */
&values[346], /* 184 THAI CHARACTER THO THONG */
&values[348], /* 185 THAI CHARACTER NO NU */
&values[350], /* 186 THAI CHARACTER BO BAIMAI */
&values[352], /* 187 THAI CHARACTER PO PLA */
&values[354], /* 188 THAI CHARACTER PHO PHUNG */
&values[356], /* 189 THAI CHARACTER FO FA */
&values[358], /* 190 THAI CHARACTER PHO PHAN */
&values[360], /* 191 THAI CHARACTER FO FAN */
&values[362], /* 192 THAI CHARACTER PHO SAMPHAO */
&values[364], /* 193 THAI CHARACTER MO MA */
&values[366], /* 194 THAI CHARACTER YO YAK */
&values[368], /* 195 THAI CHARACTER RO RUA */
&values[370], /* 196 THAI CHARACTER RU */
&values[372], /* 197 THAI CHARACTER LO LING */
&values[374], /* 198 THAI CHARACTER LU */
&values[376], /* 199 THAI CHARACTER WO WAEN */
&values[378], /* 200 THAI CHARACTER SO SALA */
&values[380], /* 201 THAI CHARACTER SO RUSI */
&values[382], /* 202 THAI CHARACTER SO SUA */
&values[384], /* 203 THAI CHARACTER HO HIP */
&values[386], /* 204 THAI CHARACTER LO CHULA */
&values[388], /* 205 THAI CHARACTER O ANG */
&values[390], /* 206 THAI CHARACTER HO NOKHUK */
&values[392], /* 207 THAI CHARACTER PAIYANNOI */
&values[394], /* 208 THAI CHARACTER SARA A */
&values[396], /* 209 THAI CHARACTER MAI HAN-AKAT */
&values[398], /* 210 THAI CHARACTER SARA AA */
&values[400], /* 211 THAI CHARACTER SARA AM */
&values[402], /* 212 THAI CHARACTER SARA I */
&values[404], /* 213 THAI CHARACTER SARA II */
&values[406], /* 214 THAI CHARACTER SARA UE */
&values[408], /* 215 THAI CHARACTER SARA UEE */
&values[410], /* 216 THAI CHARACTER SARA U */
&values[412], /* 217 THAI CHARACTER SARA UU */
&values[414], /* 218 THAI CHARACTER PHINTHU */
&values[416], /* 219 UNDEFINED */
&values[417], /* 220 UNDEFINED */
&values[418], /* 221 UNDEFINED */
&values[419], /* 222 UNDEFINED */
&values[420], /* 223 THAI CURRENCY SYMBOL BAHT */
&values[422], /* 224 THAI CHARACTER SARA E */
&values[424], /* 225 THAI CHARACTER SARA AE */
&values[426], /* 226 THAI CHARACTER SARA O */
&values[428], /* 227 THAI CHARACTER SARA AI MAIMUAN */
&values[430], /* 228 THAI CHARACTER SARA AI MAIMALAI */
&values[432], /* 229 THAI CHARACTER LAKKHANGYAO */
&values[434], /* 230 THAI CHARACTER MAIYAMOK */
&values[436], /* 231 THAI CHARACTER MAITAIKHU */
&values[438], /* 232 THAI CHARACTER MAI EK */
&values[440], /* 233 THAI CHARACTER MAI THO */
&values[442], /* 234 THAI CHARACTER MAI TRI */
&values[444], /* 235 THAI CHARACTER MAI CHATTAWA */
&values[446], /* 236 THAI CHARACTER THANTHAKHAT */
&values[448], /* 237 THAI CHARACTER NIKHAHIT */
&values[450], /* 238 THAI CHARACTER YAMAKKAN */
&values[452], /* 239 THAI CHARACTER FONGMAN */
&values[454], /* 240 THAI DIGIT ZERO */
&values[456], /* 241 THAI DIGIT ONE */
&values[458], /* 242 THAI DIGIT TWO */
&values[460], /* 243 THAI DIGIT THREE */
&values[462], /* 244 THAI DIGIT FOUR */
&values[464], /* 245 THAI DIGIT FIVE */
&values[466], /* 246 THAI DIGIT SIX */
&values[468], /* 247 THAI DIGIT SEVEN */
&values[470], /* 248 THAI DIGIT EIGHT */
&values[472], /* 249 THAI DIGIT NINE */
&values[474], /* 250 THAI CHARACTER ANGKHANKHU */
&values[476], /* 251 THAI CHARACTER KHOMUT */
&values[478], /* 252 UNDEFINED */
&values[479], /* 253 UNDEFINED */
&values[480], /* 254 UNDEFINED */
&values[481], /* 255 UNDEFINED */
}};
