/* This file was autogenerated from the Unicode mapping 
 * table LS3.uni in the format used by the Linux kbd package */

/*  LocoScript 3 <--> Unicode mapping table  */
/*  This uses psftools extensions (U* codes) and so probably won't be  */
/*  acceptable to the utilities in kbd(1) */
/*  First 32 characters are control codes & have no bitmaps. */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x00d8, 0xffff, 0x005f, 
0xffff, 0x00df, 0xffff, 0x005f, 0xffff, 0x0060, 0xffff, 0x0061, 
0xffff, 0x0062, 0xffff, 0x0063, 0xffff, 0x0064, 0xffff, 0x0065, 
0xffff, 0x0066, 0xffff, 0x0067, 0xffff, 0x0068, 0xffff, 0x0069, 
0xffff, 0x006a, 0xffff, 0x006b, 0xffff, 0x006c, 0xffff, 0x006d, 
0xffff, 0x006e, 0xffff, 0x006f, 0xffff, 0x0070, 0xffff, 0x0071, 
0xffff, 0x0072, 0xffff, 0x0073, 0xffff, 0x0074, 0xffff, 0x0075, 
0xffff, 0x0076, 0xffff, 0x0077, 0xffff, 0x0078, 0xffff, 0x0079, 
0xffff, 0x007a, 0xffff, 0x007b, 0xffff, 0x007c, 0xffff, 0x007d, 
0xffff, 0x00f8, 0xffff, 0xff10, 0x1ffff, 0x0030, 0xffff, 0x00a9, 
0xffff, 0x00ae, 0xffff, 0x2122, 0xffff, 0x25cb, 0xffff, 0x2022, 
0x1ffff, 0x25cf, 0xffff, 0x00bf, 0xffff, 0x00a1, 0xffff, 0x00aa, 
0xffff, 0x00ba, 0xffff, 0x00b6, 0xffff, 0x00a7, 0xffff, 0x00ab, 
0xffff, 0x00bb, 0xffff, 0x25c7, 0xffff, 0x2026, 0xffff, 0x00bd, 
0xffff, 0x2234, 0xffff, 0x2235, 0xffff, 0x2105, 0xffff, 0x2030, 
0xffff, 0x215f, 0xffff, 0x2020, 0xffff, 0x2021, 0xffff, 0x2014, 
0x1ffff, 0x2500, 0xffff, 0x00b1, 0xffff, 0x2264, 0xffff, 0x2260, 
0xffff, 0x2265, 0xffff, 0x2243, 0xffff, 0x2248, 0xffff, 0x0387, 
0xffff, 0x201e, 0xffff, 0x00a4, 0xffff, 0x20a3, 0xffff, 0x00a2, 
0xffff, 0x00a3, 0xffff, 0x20ba, 0xffff, 0x0192, 0xffff, 0x00a5, 
0xffff, 0x20a7, 0xffff, 0x215b, 0xffff, 0x00bc, 0xffff, 0x2153, 
0xffff, 0x215c, 0xffff, 0x215d, 0xffff, 0x2154, 0xffff, 0x00be, 
0xffff, 0x215e, 0xffff, 0x24ff, 0xffff, 0x2776, 0xffff, 0x2777, 
0xffff, 0x2778, 0xffff, 0x2779, 0xffff, 0x277a, 0xffff, 0x277b, 
0xffff, 0x277c, 0xffff, 0x277d, 0xffff, 0x277e, 0xffff, 0x2018, 
0xffff, 0x2019, 0xffff, 0x201c, 0xffff, 0x201d, 0xffff, 0x2039, 
0xffff, 0x203a, 0xffff, 0x2032, 0xffff, 0x2033, 0xffff, 0x00b7, 
0xffff, 0x00b0, 0xffff, 0x010f, 0xffff, 0x0165, 0xffff, 0x00e2, 
0xffff, 0x00fb, 0xffff, 0x00eb, 0xffff, 0x00ef, 0xffff, 0x00ff, 
0xffff, 0x0123, 0xffff, 0x0131, 0xffff, 0x2113, 0xffff, 0x00e1, 
0xffff, 0x00e9, 0xffff, 0x00ed, 0xffff, 0x00f3, 0xffff, 0x00fa, 
0xffff, 0x00e0, 0xffff, 0x00e8, 0xffff, 0x00ec, 0xffff, 0x00f2, 
0xffff, 0x00f9, 0xffff, 0x00ea, 0xffff, 0x00ee, 0xffff, 0x00f4, 
0xffff, 0x00e3, 0xffff, 0x00d5, 0xffff, 0x00e7, 0xffff, 0x00c6, 
0xffff, 0x00c7, 0xffff, 0x0132, 0xffff, 0x00c4, 0xffff, 0x00d6, 
0xffff, 0x00dc, 0xffff, 0x00c5, 0xffff, 0x00d1, 0xffff, 0x0110, 
0xffff, 0x0126, 0xffff, 0x013f, 0xffff, 0x0141, 0xffff, 0x0166, 
0xffff, 0x00de, 0xffff, 0x014a, 0xffff, 0x0138, 0xffff, 0x00e6, 
0xffff, 0x0153, 0xffff, 0x0133, 0xffff, 0x00e4, 0xffff, 0x00f6, 
0xffff, 0x00fc, 0xffff, 0x00e5, 0xffff, 0x00f1, 0xffff, 0x0111, 
0xffff, 0x0127, 0xffff, 0x0140, 0xffff, 0x0142, 0xffff, 0x0167, 
0xffff, 0x00fe, 0xffff, 0x014b, 0xffff, 0x00f0, 0xffff, 0x221e, 
0xffff, 0x2299, 0xffff, 0x2295, 0xffff, 0x2297, 0xffff, 0x25ef, 
0xffff, 0x2228, 0xffff, 0x2227, 0xffff, 0x00ac, 0xffff, 0x2205, 
0xffff, 0x2229, 0xffff, 0x222a, 0xffff, 0x2282, 0xffff, 0x2283, 
0xffff, 0x2286, 0xffff, 0x2287, 0xffff, 0x2208, 0x1ffff, 0x220a, 
0xffff, 0x2070, 0xffff, 0x00b9, 0xffff, 0x00b2, 0xffff, 0x00b3, 
0xffff, 0x2074, 0xffff, 0x2075, 0xffff, 0x2076, 0xffff, 0x2077, 
0xffff, 0x2078, 0xffff, 0x2079, 0xffff, 0x207f, 0xffff, 0x2213, 
0xffff, 0x226a, 0xffff, 0x223c, 0xffff, 0x226b, 0xffff, 0x222c, 
0xffff, 0x221a, 0xffff, 0x23a2, 0x1ffff, 0x23a5, 0xffff, 0x23a1, 
0xffff, 0x23a3, 0xffff, 0x23a4, 0xffff, 0x23a6, 0xffff, 0x222b, 
0xffff, 0x222e, 0xffff, 0x2202, 0xffff, 0x2207, 0xffff, 0x2203, 
0xffff, 0x220b, 0xffff, 0x27c2, 0xffff, 0x2200, 0xffff, 0x2220, 
0xffff, 0x2221, 0xffff, 0x220f, 0xffff, 0x2211, 0xffff, 0x27cb, 
0xffff, 0x2261, 0xffff, 0x2245, 0xffff, 0x221d, 0xffff, 0x00d7, 
0xffff, 0x00f7, 0xffff, 0x263a, 0xffff, 0x263b, 0xffff, 0x2642, 
0xffff, 0x2640, 0xffff, 0x2663, 0xffff, 0x2666, 0xffff, 0x2665, 
0xffff, 0x2660, 0xffff, 0x266a, 0xffff, 0x266b, 0xffff, 0x2713, 
0xffff, 0x2717, 0xffff, 0x274a, 0xffff, 0x25cf, 0xffff, 0x25a1, 
0xffff, 0x25a0, 0xffff, 0x2191, 0xffff, 0x2195, 0xffff, 0x2193, 
0xffff, 0x2190, 0xffff, 0x2194, 0xffff, 0x2192, 0xffff, 0x21e7, 
0xffff, 0x21f3, 0xffff, 0x21e9, 0xffff, 0x21e6, 0xffff, 0x2b04, 
0xffff, 0x21e8, 0xffff, 0x25b2, 0xffff, 0x25bc, 0xffff, 0x25c0, 
0xffff, 0x25b6, 0xffff, 0x0391, 0xffff, 0x0392, 0xffff, 0x0393, 
0xffff, 0x0394, 0xffff, 0x0395, 0xffff, 0x0396, 0xffff, 0x0397, 
0xffff, 0x0398, 0xffff, 0x0399, 0xffff, 0x039a, 0xffff, 0x039b, 
0xffff, 0x039c, 0xffff, 0x039d, 0xffff, 0x039e, 0xffff, 0x03a0, 
0xffff, 0x03a1, 0xffff, 0x03a3, 0xffff, 0x03a4, 0xffff, 0x03a5, 
0xffff, 0x03a6, 0xffff, 0x03a7, 0xffff, 0x03a8, 0xffff, 0x03a9, 
0xffff, 0x03b1, 0xffff, 0x03b2, 0xffff, 0x03b3, 0xffff, 0x03b4, 
0xffff, 0x03b5, 0xffff, 0x03b6, 0xffff, 0x03b7, 0xffff, 0x03b8, 
0xffff, 0x03b9, 0xffff, 0x03ba, 0xffff, 0x03bb, 0xffff, 0x03bc, 
0xffff, 0x03bd, 0xffff, 0x03be, 0xffff, 0x03c0, 0xffff, 0x03c1, 
0xffff, 0x03c3, 0xffff, 0x03c4, 0xffff, 0x03c5, 0xffff, 0x03c6, 
0xffff, 0x03c7, 0xffff, 0x03c8, 0xffff, 0x03c9, 0xffff, 0x03c2, 
0xffff, 0x03d5, 0xffff, 0x03ac, 0xffff, 0x03ad, 0xffff, 0x03ae, 
0xffff, 0x03cd, 0xffff, 0x03ce, 0xffff, 0x03cb, 0xffff, 0x03ca, 
0xffff, 0x1fb3, 0xffff, 0x1fc3, 0xffff, 0x1ff3, 0xffff, 0x03dd, 
0xffff, 0x03d9, 0xffff, 0x03f2, 0xffff, 0x03dc, 0xffff, 0x03d8, 
0xffff, 0x03f9, 0xffff, 0x03e1, 0xffff, 0x03db, 0xffff, 0x0375, 
0xffff, 0x013e, 0xffff, 0x013d, 0xffff, 0x2116, 0xffff, 0x0411, 
0xffff, 0x0412, 0xffff, 0x0413, 0xffff, 0x0490, 0xffff, 0x0414, 
0xffff, 0x0415, 0xffff, 0x0416, 0xffff, 0x0417, 0xffff, 0x0418, 
0xffff, 0x041a, 0xffff, 0x041b, 0xffff, 0x041c, 0xffff, 0x041d, 
0xffff, 0x041f, 0xffff, 0x0422, 0xffff, 0x0423, 0xffff, 0x0424, 
0xffff, 0x0426, 0xffff, 0x0427, 0xffff, 0x0428, 0xffff, 0x0429, 
0xffff, 0x042a, 0xffff, 0x042b, 0xffff, 0x042c, 0xffff, 0x042d, 
0xffff, 0x042e, 0xffff, 0x042f, 0xffff, 0x0431, 0xffff, 0x0432, 
0xffff, 0x0433, 0xffff, 0x0491, 0xffff, 0x0434, 0xffff, 0x0435, 
0xffff, 0x0436, 0xffff, 0x0437, 0xffff, 0x0438, 0xffff, 0x043a, 
0xffff, 0x043b, 0xffff, 0x043c, 0xffff, 0x043d, 0xffff, 0x043f, 
0xffff, 0x0442, 0xffff, 0x0443, 0xffff, 0x0444, 0xffff, 0x0446, 
0xffff, 0x0447, 0xffff, 0x0448, 0xffff, 0x0449, 0xffff, 0x044a, 
0xffff, 0x044b, 0xffff, 0x044c, 0xffff, 0x044d, 0xffff, 0x044e, 
0xffff, 0x044f, 0xffff, 0x0301, 0x00b4, 0xffff, 0x0300, 0x0060, 
0xffff, 0x0302, 0x005e, 0xffff, 0x0308, 0x00a8, 0xffff, 0x030c, 
0x02c7, 0xffff, 0x0307, 0x02d9, 0xffff, 0x0303, 0x007e, 0xffff, 
0x0306, 0x02d8, 0xffff, 0x030b, 0x02dd, 0xffff, 0x030a, 0x02da, 
0xffff, 0x0304, 0x02c9, 0xffff, 0x030f, 0xffff, 0x0327, 0x00b8, 
0xffff, 0x0328, 0x02db, 0xffff, 0x0326, 0xffff, 0x0338, 0xffff, 
0x0311, 0xffff, 0x0314, 0x1ffe, 0xffff, 0x0313, 0x1fbd, 0xffff, 
0x1fde, 0xffff, 0x1fce, 0xffff, 0x1fdd, 0xffff, 0x1fcd, 0xffff, 
0x1fdf, 0xffff, 0x1fcf, 0xffff, 0x0323, 0xffff, };

struct psf_mapping512 m_LS3 = { "LS3",
509, {
&values[0], /* 0  */
&values[0], /* 1  */
&values[0], /* 2  */
&values[0], /* 3  */
&values[0], /* 4  */
&values[0], /* 5  */
&values[0], /* 6  */
&values[0], /* 7  */
&values[0], /* 8  */
&values[0], /* 9  */
&values[0], /* 10  */
&values[0], /* 11  */
&values[0], /* 12  */
&values[0], /* 13  */
&values[0], /* 14  */
&values[0], /* 15  */
&values[0], /* 16  */
&values[0], /* 17  */
&values[0], /* 18  */
&values[0], /* 19  */
&values[0], /* 20  */
&values[0], /* 21  */
&values[0], /* 22  */
&values[0], /* 23  */
&values[0], /* 24  */
&values[0], /* 25  */
&values[0], /* 26  */
&values[0], /* 27  */
&values[0], /* 28  */
&values[0], /* 29  */
&values[0], /* 30  */
&values[0], /* 31  */
&values[1], /* 32  */
&values[3], /* 33  */
&values[5], /* 34  */
&values[7], /* 35  */
&values[9], /* 36  */
&values[11], /* 37  */
&values[13], /* 38  */
&values[15], /* 39  */
&values[17], /* 40  */
&values[19], /* 41  */
&values[21], /* 42  */
&values[23], /* 43  */
&values[25], /* 44  */
&values[27], /* 45  */
&values[29], /* 46  */
&values[31], /* 47  */
&values[33], /* 48  */
&values[35], /* 49  */
&values[37], /* 50  */
&values[39], /* 51  */
&values[41], /* 52  */
&values[43], /* 53  */
&values[45], /* 54  */
&values[47], /* 55  */
&values[49], /* 56  */
&values[51], /* 57  */
&values[53], /* 58  */
&values[55], /* 59  */
&values[57], /* 60  */
&values[59], /* 61  */
&values[61], /* 62  */
&values[63], /* 63  */
&values[65], /* 64  */
&values[67], /* 65  */
&values[69], /* 66  */
&values[71], /* 67  */
&values[73], /* 68  */
&values[75], /* 69  */
&values[77], /* 70  */
&values[79], /* 71  */
&values[81], /* 72  */
&values[83], /* 73  */
&values[85], /* 74  */
&values[87], /* 75  */
&values[89], /* 76  */
&values[91], /* 77  */
&values[93], /* 78  */
&values[95], /* 79  */
&values[97], /* 80  */
&values[99], /* 81  */
&values[101], /* 82  */
&values[103], /* 83  */
&values[105], /* 84  */
&values[107], /* 85  */
&values[109], /* 86  */
&values[111], /* 87  */
&values[113], /* 88  */
&values[115], /* 89  */
&values[117], /* 90  */
&values[119], /* 91  */
&values[121], /* 92  */
&values[123], /* 93  */
&values[125], /* 94  Ø */
&values[131], /* 95  */
&values[133], /* 96  ß */
&values[135], /* 97  */
&values[137], /* 98  */
&values[139], /* 99  */
&values[141], /* 100  */
&values[143], /* 101  */
&values[145], /* 102  */
&values[147], /* 103  */
&values[149], /* 104  */
&values[151], /* 105  */
&values[153], /* 106  */
&values[155], /* 107  */
&values[157], /* 108  */
&values[159], /* 109  */
&values[161], /* 110  */
&values[163], /* 111  */
&values[165], /* 112  */
&values[167], /* 113  */
&values[169], /* 114  */
&values[171], /* 115  */
&values[173], /* 116  */
&values[175], /* 117  */
&values[177], /* 118  */
&values[179], /* 119  */
&values[181], /* 120  */
&values[183], /* 121  */
&values[185], /* 122  */
&values[187], /* 123  */
&values[189], /* 124  */
&values[191], /* 125  */
&values[193], /* 126  ø */
&values[195], /* 127  Slashless zero. Map to 'Full width 0', but if that */
&values[199], /* 128  Copyright */
&values[201], /* 129  Registered */
&values[203], /* 130  Trademark */
&values[205], /* 131  Hollow bullet */
&values[207], /* 132  Solid bullet */
&values[211], /* 133  Upside down question mark */
&values[213], /* 134  Upside down pling */
&values[215], /* 135  Feminine ordinal */
&values[217], /* 136  Masculine ordinal */
&values[219], /* 137  Pilcrow */
&values[221], /* 138  Section */
&values[223], /* 139  Open quote */
&values[225], /* 140  Close quote */
&values[227], /* 141  White diamond */
&values[229], /* 142  Ellipsis */
&values[231], /* 143  Half */
&values[233], /* 144  Therefore */
&values[235], /* 145  Because */
&values[237], /* 146  Care of */
&values[239], /* 147  Per mille */
&values[241], /* 148  1/ */
&values[243], /* 149  Dagger */
&values[245], /* 150  Double dagger */
&values[247], /* 151  Dash (or Horizontal line) */
&values[251], /* 152  Plus or minus */
&values[253], /* 153  Less than or equal to */
&values[255], /* 154  Not equal to */
&values[257], /* 155  Greater than or equal to */
&values[259], /* 156  Asymptotically equal to */
&values[261], /* 157  Almost equal to */
&values[263], /* 158  Greek ano teleia */
&values[265], /* 159  Low double comma quotation mark */
&values[267], /* 160  Currency sign */
&values[269], /* 161  Franc sign */
&values[271], /* 162  Cent sign */
&values[273], /* 163  Pound sign */
&values[275], /* 164  Turkish lira sign (?) */
&values[277], /* 165  Florin */
&values[279], /* 166  Yen */
&values[281], /* 167  Peseta */
&values[283], /* 168  1/8 */
&values[285], /* 169  1/4 */
&values[287], /* 170  1/3 */
&values[289], /* 171  3/8 */
&values[291], /* 172  5/8 */
&values[293], /* 173  2/3 */
&values[295], /* 174  3/4 */
&values[297], /* 175  7/8 */
&values[299], /* 176  Circled 0 */
&values[301], /* 177  Circled 1 */
&values[303], /* 178  Circled 2 */
&values[305], /* 179  Circled 3 */
&values[307], /* 180  Circled 4 */
&values[309], /* 181  Circled 5 */
&values[311], /* 182  Circled 6 */
&values[313], /* 183  Circled 7 */
&values[315], /* 184  Circled 8 */
&values[317], /* 185  Circled 9 */
&values[319], /* 186  Left curly quote single */
&values[321], /* 187  Right curly quote single */
&values[323], /* 188  Left curly quote double */
&values[325], /* 189  Right curly quote double */
&values[327], /* 190  Left < quote single */
&values[329], /* 191  Right > quote single */
&values[331], /* 192  Minutes */
&values[333], /* 193  Seconds */
&values[335], /* 194  Decimal point */
&values[337], /* 195  Degree sign */
&values[0], /* 196  */
&values[0], /* 197  */
&values[339], /* 198  Lower case d caron */
&values[341], /* 199  Lower case t caron */
&values[343], /* 200  Lower case a circumflex */
&values[345], /* 201  Lower case u circumflex */
&values[347], /* 202  Lower case e diaeresis */
&values[349], /* 203  Lower case i diaeresis */
&values[351], /* 204  Lower case y diaeresis */
&values[353], /* 205  Lower case g cedilla */
&values[355], /* 206  Lower case i dotless */
&values[357], /* 207  Lower case l curly */
&values[359], /* 208  Lower case a acute */
&values[361], /* 209  Lower case e acute */
&values[363], /* 210  Lower case i acute */
&values[365], /* 211  Lower case o acute */
&values[367], /* 212  Lower case u acute */
&values[369], /* 213  Lower case a grave */
&values[371], /* 214  Lower case e grave */
&values[373], /* 215  Lower case i grave */
&values[375], /* 216  Lower case o grave */
&values[377], /* 217  Lower case u grave */
&values[379], /* 218  Lower case e circumflex */
&values[381], /* 219  Lower case i circumflex */
&values[383], /* 220  Lower case o circumflex */
&values[385], /* 221  Lower case a tilde */
&values[387], /* 222  Lower case o tilde */
&values[389], /* 223  Lower case c cedilla */
&values[391], /* 224  Upper case AE */
&values[393], /* 225  Upper case OE */
&values[395], /* 226  Upper case IJ */
&values[397], /* 227  Upper case A with diaeresis */
&values[399], /* 228  Upper case O with diaeresis */
&values[401], /* 229  Upper case U with diaeresis */
&values[403], /* 230  Upper case A with ring */
&values[405], /* 231  Upper case N with tilde */
&values[407], /* 232  Upper case D with stroke */
&values[409], /* 233  Upper case H with stroke */
&values[411], /* 234  Upper case L with dot */
&values[413], /* 235  Upper case L with stroke */
&values[415], /* 236  Upper case T with stroke */
&values[417], /* 237  Upper case thorn */
&values[419], /* 238  Upper case eng */
&values[421], /* 239  Lower case kra */
&values[423], /* 240  Lower case ae */
&values[425], /* 241  Lower case oe */
&values[427], /* 242  Lower case ij */
&values[429], /* 243  Lower case a with diaeresis */
&values[431], /* 244  Lower case o with diaeresis */
&values[433], /* 245  Lower case u with diaeresis */
&values[435], /* 246  Lower case a with ring */
&values[437], /* 247  Lower case n with tilde */
&values[439], /* 248  Lower case d with stroke */
&values[441], /* 249  Lower case h with stroke */
&values[443], /* 250  Lower case l with dot */
&values[445], /* 251  Lower case l with stroke */
&values[447], /* 252  Lower case t with stroke */
&values[449], /* 253  Lower case thorn */
&values[451], /* 254  Lower case eng */
&values[453], /* 255  Lower case eth */
&values[455], /* 256  Infinity  */
&values[457], /* 257  Arrow emerging */
&values[459], /* 258  Circle plus */
&values[461], /* 259  Arrow receding */
&values[463], /* 260  Large open circle */
&values[465], /* 261  Logical or */
&values[467], /* 262  Logical and */
&values[469], /* 263  Logical not */
&values[471], /* 264  Empty set */
&values[473], /* 265  Intersection */
&values[475], /* 266  Union */
&values[477], /* 267  Proper subset */
&values[479], /* 268  Proper superset */
&values[481], /* 269  Reflex subset */
&values[483], /* 270  Reflex superset */
&values[485], /* 271  Element */
&values[489], /* 272  Superscript 0 */
&values[491], /* 273  Superscript 1 */
&values[493], /* 274  Superscript 2 */
&values[495], /* 275  Superscript 3 */
&values[497], /* 276  Superscript 4 */
&values[499], /* 277  Superscript 5 */
&values[501], /* 278  Superscript 6 */
&values[503], /* 279  Superscript 7 */
&values[505], /* 280  Superscript 8 */
&values[507], /* 281  Superscript 9 */
&values[509], /* 282  Superscript n */
&values[511], /* 283  Minus or plus */
&values[513], /* 284  Much less than */
&values[515], /* 285  Tilde operator */
&values[517], /* 286  Much greater than */
&values[519], /* 287  Parallel */
&values[521], /* 288  Square root */
&values[523], /* 289  Square bracket extension */
&values[527], /* 290  Left square bracket upper corner */
&values[529], /* 291  Left square bracket lower corner */
&values[531], /* 292  Right square bracket upper corner */
&values[533], /* 293  Right square bracket lower corner */
&values[535], /* 294  Integral */
&values[537], /* 295  Contour integral */
&values[539], /* 296  Partial differential */
&values[541], /* 297  Nabla */
&values[543], /* 298  There exists */
&values[545], /* 299  Contains as a member */
&values[547], /* 300  Perpendicular */
&values[549], /* 301  For all */
&values[551], /* 302  Angle */
&values[553], /* 303  Measured angle */
&values[555], /* 304  Product */
&values[557], /* 305  Summation */
&values[559], /* 306  Mathematical rising diagonal */
&values[0], /* 307  */
&values[0], /* 308  */
&values[0], /* 309  */
&values[0], /* 310  */
&values[0], /* 311  */
&values[0], /* 312  */
&values[0], /* 313  */
&values[0], /* 314  */
&values[561], /* 315  Identical to */
&values[563], /* 316  Approximately equal to */
&values[565], /* 317  Proportional to */
&values[567], /* 318  Multiplication sign */
&values[569], /* 319  Division sign */
&values[571], /* 320  White smiling face */
&values[573], /* 321  Black smiling face */
&values[575], /* 322  Male sign */
&values[577], /* 323  Female sign */
&values[579], /* 324  Clubs */
&values[581], /* 325  Diamonds */
&values[583], /* 326  Hearts */
&values[585], /* 327  Spades */
&values[587], /* 328  Single quaver */
&values[589], /* 329  Double quaver */
&values[591], /* 330  Tick */
&values[593], /* 331  Cross */
&values[595], /* 332  Eight-spoked star */
&values[597], /* 333  Black circle */
&values[599], /* 334  White square */
&values[601], /* 335  Black square */
&values[603], /* 336  Up arrow */
&values[605], /* 337  Up and down arrow */
&values[607], /* 338  Down arrow */
&values[609], /* 339  Left arrow */
&values[611], /* 340  Left and right arrow */
&values[613], /* 341  Right arrow */
&values[615], /* 342  Up white arrow */
&values[617], /* 343  Up and down white arrow */
&values[619], /* 344  Down white arrow */
&values[621], /* 345  Left white arrow */
&values[623], /* 346  Left and right white arrow */
&values[625], /* 347  Right white arrow */
&values[627], /* 348  Upward-pointing triangle */
&values[629], /* 349  Downward-pointing triangle */
&values[631], /* 350  Leftward-pointing triangle */
&values[633], /* 351  Rightward-pointing triangle */
&values[635], /* 352  Capital Alpha */
&values[637], /* 353  Capital Beta */
&values[639], /* 354  Capital Gamma */
&values[641], /* 355  Capital Delta */
&values[643], /* 356  Capital Epsilon */
&values[645], /* 357  Capital Zeta */
&values[647], /* 358  Capital Eta */
&values[649], /* 359  Capital Theta */
&values[651], /* 360  Capital Iota */
&values[653], /* 361  Capital Kappa */
&values[655], /* 362  Capital Lambda */
&values[657], /* 363  Capital Mu */
&values[659], /* 364  Capital Nu */
&values[661], /* 365  Capital Xi */
&values[663], /* 366  Capital Pi */
&values[665], /* 367  Capital Rho */
&values[667], /* 368  Capital Sigma */
&values[669], /* 369  Capital Tau */
&values[671], /* 370  Capital Upsilon */
&values[673], /* 371  Capital Phi */
&values[675], /* 372  Capital Chi */
&values[677], /* 373  Capital Psi */
&values[679], /* 374  Capital Omega */
&values[681], /* 375  Lower case Alpha */
&values[683], /* 376  Lower case Beta */
&values[685], /* 377  Lower case Gamma */
&values[687], /* 378  Lower case Delta */
&values[689], /* 379  Lower case Epsilon */
&values[691], /* 380  Lower case Zeta */
&values[693], /* 381  Lower case Eta */
&values[695], /* 382  Lower case Theta */
&values[697], /* 383  Lower case Iota */
&values[699], /* 384  Lower case Kappa */
&values[701], /* 385  Lower case Lambda */
&values[703], /* 386  Lower case Mu */
&values[705], /* 387  Lower case Nu */
&values[707], /* 388  Lower case Xi */
&values[709], /* 389  Lower case Pi */
&values[711], /* 390  Lower case Rho */
&values[713], /* 391  Lower case Sigma */
&values[715], /* 392  Lower case Tau */
&values[717], /* 393  Lower case Upsilon */
&values[719], /* 394  Lower case Phi */
&values[721], /* 395  Lower case Chi */
&values[723], /* 396  Lower case Psi */
&values[725], /* 397  Lower case Omega */
&values[727], /* 398  Lower case terminal Sigma */
&values[729], /* 399  Phi symbol */
&values[731], /* 400  Lower case alpha with tonos */
&values[733], /* 401  Lower case epsilon with tonos */
&values[735], /* 402  Lower case eta with tonos */
&values[737], /* 403  Lower case iota with tonos */
&values[739], /* 404  Lower case omega with tonos */
&values[741], /* 405  Lower case upsilon with diaeresis */
&values[743], /* 406  Lower case iota with diaeresis */
&values[745], /* 407  Lower case alpha with iota subscript */
&values[747], /* 408  Lower case eta with iota subscript */
&values[749], /* 409  Lower case omega with iota subscript */
&values[751], /* 410  Lower case digamma */
&values[753], /* 411  Lower case qoppa */
&values[755], /* 412  Lower case lunate sigma */
&values[757], /* 413  Upper case digamma */
&values[759], /* 414  Upper case qoppa */
&values[761], /* 415  Upper case lunate sigma */
&values[763], /* 416  Lower case sampi	 */
&values[765], /* 417  Lower case stigma */
&values[767], /* 418  Greek lower numeral sign */
&values[0], /* 419  */
&values[0], /* 420  */
&values[0], /* 421  */
&values[769], /* 422  Lower case L with caron */
&values[771], /* 423  Upper case L with caron */
&values[773], /* 424  Numero sign */
&values[775], /* 425  Cyrillic capital Be */
&values[0], /* 426  */
&values[777], /* 427  Cyrillic capital Ve */
&values[779], /* 428  Cyrillic capital Ghe */
&values[781], /* 429  Cyrillic capital Ghe with upturn */
&values[783], /* 430  Cyrillic capital De */
&values[785], /* 431  Cyrillic captatl Ie */
&values[787], /* 432  Cyrillic capital Zhe */
&values[789], /* 433  Cyrillic capital Ze */
&values[791], /* 434  Cyrillic capital I */
&values[793], /* 435  Cyrillic capital Ka */
&values[795], /* 436  Cyrillic capital El */
&values[797], /* 437  Cyrillic capital Em */
&values[799], /* 438  Cyrillic capital En */
&values[801], /* 439  Cyrillic capital Pe */
&values[803], /* 440  Cyrillic capital Te */
&values[805], /* 441  Cyrillic capital U */
&values[807], /* 442  Cyrillic capital Ef */
&values[809], /* 443  Cyrillic capital Tse */
&values[811], /* 444  Cyrillic capital Che */
&values[813], /* 445  Cyrillic capital Sha */
&values[815], /* 446  Cyrillic capital Shcha */
&values[817], /* 447  Cyrillic capital hard sign */
&values[819], /* 448  Cyrillic capital Yeru	 */
&values[821], /* 449  Cyrillic capital soft sign */
&values[823], /* 450  Cyrillic capital E */
&values[825], /* 451  Cyrillic capital Yu */
&values[827], /* 452  Cyrillic capital Ya */
&values[829], /* 453  Cyrillic small be */
&values[831], /* 454  Cyrillic small ve */
&values[833], /* 455  Cyrillic small ghe */
&values[835], /* 456  Cyrillic small ghe with upturn */
&values[837], /* 457  Cyrillic small de */
&values[839], /* 458  Cyrillic small ie */
&values[841], /* 459  Cyrillic small zhe */
&values[843], /* 460  Cyrillic small ze */
&values[845], /* 461  Cyrillic small i */
&values[847], /* 462  Cyrillic small ka */
&values[849], /* 463  Cyrillic small el */
&values[851], /* 464  Cyrillic small em */
&values[853], /* 465  Cyrillic small en */
&values[855], /* 466  Cyrillic small pe */
&values[857], /* 467  Cyrillic small te */
&values[859], /* 468  Cyrillic small u */
&values[861], /* 469  Cyrillic small ef */
&values[863], /* 470  Cyrillic small tse */
&values[865], /* 471  Cyrillic small che */
&values[867], /* 472  Cyrillic small sha */
&values[869], /* 473  Cyrillic small shcha */
&values[871], /* 474  Cyrillic small hard sign */
&values[873], /* 475  Cyrillic small yeru */
&values[875], /* 476  Cyrillic small soft sign */
&values[877], /* 477  Cyrillic small e */
&values[879], /* 478  Cyrillic small yu */
&values[881], /* 479  Cyrillic small ya */
&values[883], /* 480  Acute accent */
&values[886], /* 481  Grave accent */
&values[889], /* 482  Circumflex accent */
&values[892], /* 483  Diaeresis */
&values[895], /* 484  Caron */
&values[898], /* 485  Dot above */
&values[901], /* 486  Tilde */
&values[904], /* 487  Breve */
&values[907], /* 488  Double acute accent */
&values[910], /* 489  Ring above */
&values[913], /* 490  Macron */
&values[916], /* 491  Double grave accent */
&values[918], /* 492  Cedilla */
&values[921], /* 493  Ogonek */
&values[924], /* 494  Latvian tail */
&values[926], /* 495  Stroke */
&values[928], /* 496  Inverted breve */
&values[930], /* 497  Rough breathing mark */
&values[933], /* 498  Smooth breathing mark */
&values[936], /* 499  Rough breathing and acute */
&values[938], /* 500  Smooth breathing and acute */
&values[940], /* 501  Rough breathing and grave */
&values[942], /* 502  Smooth breathing and grave */
&values[0], /* 503  */
&values[0], /* 504  */
&values[944], /* 505  Rough breathing and tilde */
&values[946], /* 506  Smooth breathing and tilde */
&values[0], /* 507  */
&values[948], /* 508  Combining dot below */
&values[0], /* 509  */
&values[0], /* 510  */
&values[0], /* 511  */
}};
