/* This file was autogenerated from the Unicode mapping 
 * table ppc860.uni in the format used by the Linux kbd package */

/*  PPC512: Codepage 860. Similar to the real codepage 860 but not quite the  */
/*  same. */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0x0000, 0xffff, 0x263a, 0xffff, 0x263b, 0xffff, 0x2665, 
0xffff, 0x2666, 0x25c6, 0xffff, 0x2663, 0xffff, 0x2660, 0xffff, 
0x2022, 0xffff, 0x25d8, 0xffff, 0x25cb, 0xffff, 0x25d9, 0xffff, 
0x2642, 0xffff, 0x2640, 0xffff, 0x266a, 0xffff, 0x266b, 0xffff, 
0x263c, 0xffff, 0x25b6, 0x25ba, 0xffff, 0x25c0, 0x25c4, 0xffff, 
0x2195, 0xffff, 0x203c, 0xffff, 0x00b6, 0xffff, 0x00a7, 0xffff, 
0x25ac, 0xffff, 0x21a8, 0xffff, 0x2191, 0xffff, 0x2193, 0xffff, 
0x2192, 0xffff, 0x2190, 0xffff, 0x221f, 0xffff, 0x2194, 0xffff, 
0x25b2, 0xffff, 0x25bc, 0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 
0x0022, 0x1ffff, 0x00a8, 0xffff, 0x0023, 0xffff, 0x0024, 0xffff, 
0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 0xffff, 0x0028, 0xffff, 
0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 0xffff, 0x002c, 0x1ffff, 
0x00b8, 0xffff, 0x002d, 0x1ffff, 0x00ad, 0xffff, 0x002e, 0xffff, 
0x002f, 0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 
0x0033, 0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 
0x0037, 0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 
0x003b, 0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 
0x003f, 0xffff, 0x0040, 0xffff, 0x0041, 0x1ffff, 0x00c0, 0x00c1, 
0x00c2, 0x00c3, 0xffff, 0x0042, 0xffff, 0x0043, 0x1ffff, 0x00a9, 
0xffff, 0x0044, 0xffff, 0x0045, 0x1ffff, 0x00c8, 0x00ca, 0x00cb, 
0xffff, 0x0046, 0xffff, 0x0047, 0xffff, 0x0048, 0xffff, 0x0049, 
0x1ffff, 0x00cc, 0x00cd, 0x00ce, 0x00cf, 0xffff, 0x004a, 0xffff, 
0x004b, 0x1ffff, 0x212a, 0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 
0x004e, 0xffff, 0x004f, 0x1ffff, 0x00d2, 0x00d3, 0x00d4, 0x00d5, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0x1ffff, 0x00ae, 
0xffff, 0x0053, 0xffff, 0x0054, 0xffff, 0x0055, 0x1ffff, 0x00d9, 
0x00da, 0x00db, 0xffff, 0x0056, 0xffff, 0x0057, 0xffff, 0x0058, 
0xffff, 0x0059, 0x1ffff, 0x00dd, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xf804, 0xffff, 0x0060, 0xffff, 0x0061, 0x1ffff, 0x00e3, 0xffff, 
0x0062, 0xffff, 0x0063, 0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 
0x0066, 0xffff, 0x0067, 0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 
0x006a, 0xffff, 0x006b, 0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 
0x006e, 0xffff, 0x006f, 0x1ffff, 0x00f5, 0xffff, 0x0070, 0xffff, 
0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 0xffff, 0x0074, 0xffff, 
0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 0xffff, 0x0078, 0x1ffff, 
0x00d7, 0xffff, 0x0079, 0x1ffff, 0x00fd, 0xffff, 0x007a, 0xffff, 
0x007b, 0xffff, 0x007c, 0x1ffff, 0x00a5, 0xffff, 0x007d, 0xffff, 
0x007e, 0xffff, 0x2302, 0xffff, 0x00c7, 0xffff, 0x00fc, 0xffff, 
0x00e9, 0xffff, 0x00e2, 0xffff, 0x00e3, 0xffff, 0x00e0, 0xffff, 
0x00c1, 0xffff, 0x00e7, 0xffff, 0x00cb, 0xffff, 0x00ca, 0xffff, 
0x00e8, 0xffff, 0x00cd, 0xffff, 0x00d4, 0xffff, 0x00ec, 0xffff, 
0x00c3, 0xffff, 0x00c2, 0xffff, 0x00c9, 0xffff, 0x00c0, 0xffff, 
0x00c8, 0xffff, 0x00f4, 0xffff, 0x00f5, 0xffff, 0x00f2, 0xffff, 
0x00da, 0xffff, 0x00f9, 0xffff, 0x00cc, 0xffff, 0x00d5, 0xffff, 
0x00dc, 0xffff, 0x00a2, 0xffff, 0x00a3, 0xffff, 0x00d9, 0xffff, 
0x20a7, 0xffff, 0x00d3, 0xffff, 0x00e1, 0xffff, 0x00ed, 0xffff, 
0x00f3, 0xffff, 0x00fa, 0xffff, 0x00f1, 0xffff, 0x00d1, 0xffff, 
0x00aa, 0xffff, 0x00ba, 0xffff, 0x00bf, 0xffff, 0x00d2, 0xffff, 
0x00ac, 0xffff, 0x00bd, 0xffff, 0x00bc, 0xffff, 0x00a1, 0xffff, 
0x00ab, 0xffff, 0x00bb, 0xffff, 0x2591, 0xffff, 0x2592, 0xffff, 
0x2593, 0xffff, 0x2502, 0xffff, 0x2524, 0xffff, 0x2561, 0xffff, 
0x2562, 0xffff, 0x2556, 0xffff, 0x2555, 0xffff, 0x2563, 0xffff, 
0x2551, 0xffff, 0x2557, 0xffff, 0x255d, 0xffff, 0x255c, 0xffff, 
0x255b, 0xffff, 0x2510, 0xffff, 0x2514, 0xffff, 0x2534, 0xffff, 
0x252c, 0xffff, 0x251c, 0xffff, 0x2500, 0xffff, 0x253c, 0xffff, 
0x255e, 0xffff, 0x255f, 0xffff, 0x255a, 0xffff, 0x2554, 0xffff, 
0x2569, 0xffff, 0x2566, 0xffff, 0x2560, 0xffff, 0x2550, 0xffff, 
0x256c, 0xffff, 0x2567, 0xffff, 0x2568, 0xffff, 0x2564, 0xffff, 
0x2565, 0xffff, 0x2559, 0xffff, 0x2558, 0xffff, 0x2552, 0xffff, 
0x2553, 0xffff, 0x256b, 0xffff, 0x256a, 0xffff, 0x2518, 0xffff, 
0x250c, 0xffff, 0x2588, 0xffff, 0x2584, 0xffff, 0x258c, 0xffff, 
0x2590, 0xffff, 0x2580, 0xffff, 0x03b1, 0xffff, 0x03b2, 0x00df, 
0xffff, 0x0393, 0xffff, 0x03c0, 0xffff, 0x03a3, 0xffff, 0x03c3, 
0xffff, 0x00b5, 0x03bc, 0xffff, 0x03c4, 0xffff, 0x03a6, 0x00d8, 
0xffff, 0x0398, 0xffff, 0x03a9, 0x2126, 0xffff, 0x03b4, 0xffff, 
0x221e, 0xffff, 0x03c6, 0x00f8, 0xffff, 0x2208, 0xffff, 0x2229, 
0xffff, 0x2261, 0xffff, 0x00b1, 0xffff, 0x2265, 0xffff, 0x2264, 
0xffff, 0x2320, 0xffff, 0x2321, 0xffff, 0x00f7, 0xffff, 0x2248, 
0xffff, 0x00b0, 0xffff, 0x2219, 0xffff, 0x00b7, 0xffff, 0x221a, 
0xffff, 0x207f, 0xffff, 0x00b2, 0xffff, 0x25a0, 0xfffd, 0xffff, 
0x00a0, 0xffff, };

struct psf_mapping256 m_PPC860 = { "PPC860",
256, {
&values[1], /* 0  */
&values[3], /* 1  */
&values[5], /* 2  */
&values[7], /* 3  */
&values[9], /* 4  */
&values[12], /* 5  */
&values[14], /* 6  */
&values[16], /* 7  */
&values[18], /* 8  */
&values[20], /* 9  */
&values[22], /* 10  */
&values[24], /* 11  */
&values[26], /* 12  */
&values[28], /* 13  */
&values[30], /* 14  */
&values[32], /* 15  */
&values[34], /* 16  */
&values[37], /* 17  */
&values[40], /* 18  */
&values[42], /* 19  */
&values[44], /* 20  */
&values[46], /* 21  */
&values[48], /* 22  */
&values[50], /* 23  */
&values[52], /* 24  */
&values[54], /* 25  */
&values[56], /* 26  */
&values[58], /* 27  */
&values[60], /* 28  */
&values[62], /* 29  */
&values[64], /* 30  */
&values[66], /* 31  */
&values[68], /* 32  */
&values[70], /* 33  */
&values[72], /* 34  */
&values[76], /* 35  */
&values[78], /* 36  */
&values[80], /* 37  */
&values[82], /* 38  */
&values[84], /* 39  */
&values[86], /* 40  */
&values[88], /* 41  */
&values[90], /* 42  */
&values[92], /* 43  */
&values[94], /* 44  */
&values[98], /* 45  */
&values[102], /* 46  */
&values[104], /* 47  */
&values[106], /* 48  */
&values[108], /* 49  */
&values[110], /* 50  */
&values[112], /* 51  */
&values[114], /* 52  */
&values[116], /* 53  */
&values[118], /* 54  */
&values[120], /* 55  */
&values[122], /* 56  */
&values[124], /* 57  */
&values[126], /* 58  */
&values[128], /* 59  */
&values[130], /* 60  */
&values[132], /* 61  */
&values[134], /* 62  */
&values[136], /* 63  */
&values[138], /* 64  */
&values[140], /* 65  */
&values[147], /* 66  */
&values[149], /* 67  */
&values[153], /* 68  */
&values[155], /* 69  */
&values[161], /* 70  */
&values[163], /* 71  */
&values[165], /* 72  */
&values[167], /* 73  */
&values[174], /* 74  */
&values[176], /* 75  */
&values[180], /* 76  */
&values[182], /* 77  */
&values[184], /* 78  */
&values[186], /* 79  */
&values[193], /* 80  */
&values[195], /* 81  */
&values[197], /* 82  */
&values[201], /* 83  */
&values[203], /* 84  */
&values[205], /* 85  */
&values[211], /* 86  */
&values[213], /* 87  */
&values[215], /* 88  */
&values[217], /* 89  */
&values[221], /* 90  */
&values[223], /* 91  */
&values[225], /* 92  */
&values[227], /* 93  */
&values[229], /* 94  */
&values[231], /* 95  */
&values[234], /* 96  */
&values[236], /* 97  */
&values[240], /* 98  */
&values[242], /* 99  */
&values[244], /* 100  */
&values[246], /* 101  */
&values[248], /* 102  */
&values[250], /* 103  */
&values[252], /* 104  */
&values[254], /* 105  */
&values[256], /* 106  */
&values[258], /* 107  */
&values[260], /* 108  */
&values[262], /* 109  */
&values[264], /* 110  */
&values[266], /* 111  */
&values[270], /* 112  */
&values[272], /* 113  */
&values[274], /* 114  */
&values[276], /* 115  */
&values[278], /* 116  */
&values[280], /* 117  */
&values[282], /* 118  */
&values[284], /* 119  */
&values[286], /* 120  */
&values[290], /* 121  */
&values[294], /* 122  */
&values[296], /* 123  */
&values[298], /* 124  */
&values[302], /* 125  */
&values[304], /* 126  */
&values[306], /* 127  */
&values[308], /* 128  */
&values[310], /* 129  */
&values[312], /* 130  */
&values[314], /* 131  a with circumflex */
&values[316], /* 132  a with tilde */
&values[318], /* 133  */
&values[320], /* 134  Capital A acute */
&values[322], /* 135  */
&values[324], /* 136  Capital E diaresis */
&values[326], /* 137  Capital E circumflex */
&values[328], /* 138  */
&values[330], /* 139  Capital I acute */
&values[332], /* 140  O grave */
&values[334], /* 141  */
&values[336], /* 142  A tilde */
&values[338], /* 143  A circumflex */
&values[340], /* 144  E acute */
&values[342], /* 145  A grave */
&values[344], /* 146  E grave */
&values[346], /* 147  o circumflex */
&values[348], /* 148  o tilde */
&values[350], /* 149  */
&values[352], /* 150  U acute */
&values[354], /* 151  */
&values[356], /* 152  I grave */
&values[358], /* 153  O tilde */
&values[360], /* 154  */
&values[362], /* 155  cent */
&values[364], /* 156  pound */
&values[366], /* 157  U grave */
&values[368], /* 158  Pesata */
&values[370], /* 159  U acute */
&values[372], /* 160  */
&values[374], /* 161  */
&values[376], /* 162  */
&values[378], /* 163  */
&values[380], /* 164  */
&values[382], /* 165  */
&values[384], /* 166  */
&values[386], /* 167  */
&values[388], /* 168  */
&values[390], /* 169  O grave */
&values[392], /* 170  */
&values[394], /* 171  */
&values[396], /* 172  */
&values[398], /* 173  */
&values[400], /* 174  */
&values[402], /* 175  */
&values[404], /* 176  */
&values[406], /* 177  */
&values[408], /* 178  */
&values[410], /* 179  */
&values[412], /* 180  */
&values[414], /* 181  */
&values[416], /* 182  */
&values[418], /* 183  */
&values[420], /* 184  */
&values[422], /* 185  */
&values[424], /* 186  */
&values[426], /* 187  */
&values[428], /* 188  */
&values[430], /* 189  */
&values[432], /* 190  */
&values[434], /* 191  */
&values[436], /* 192  */
&values[438], /* 193  */
&values[440], /* 194  */
&values[442], /* 195  */
&values[444], /* 196  */
&values[446], /* 197  */
&values[448], /* 198  */
&values[450], /* 199  */
&values[452], /* 200  */
&values[454], /* 201  */
&values[456], /* 202  */
&values[458], /* 203  */
&values[460], /* 204  */
&values[462], /* 205  */
&values[464], /* 206  */
&values[466], /* 207  */
&values[468], /* 208  */
&values[470], /* 209  */
&values[472], /* 210  */
&values[474], /* 211  */
&values[476], /* 212  */
&values[478], /* 213  */
&values[480], /* 214  */
&values[482], /* 215  */
&values[484], /* 216  */
&values[486], /* 217  */
&values[488], /* 218  */
&values[490], /* 219  */
&values[492], /* 220  */
&values[494], /* 221  */
&values[496], /* 222  */
&values[498], /* 223  */
&values[500], /* 224  */
&values[502], /* 225  */
&values[505], /* 226  */
&values[507], /* 227  */
&values[509], /* 228  */
&values[511], /* 229  */
&values[513], /* 230  */
&values[516], /* 231  */
&values[518], /* 232  */
&values[521], /* 233  */
&values[523], /* 234  */
&values[526], /* 235  */
&values[528], /* 236  */
&values[530], /* 237  */
&values[533], /* 238  Element of */
&values[535], /* 239  */
&values[537], /* 240  */
&values[539], /* 241  */
&values[541], /* 242  */
&values[543], /* 243  */
&values[545], /* 244  */
&values[547], /* 245  */
&values[549], /* 246  */
&values[551], /* 247  */
&values[553], /* 248  */
&values[555], /* 249  */
&values[557], /* 250  */
&values[559], /* 251  */
&values[561], /* 252  */
&values[563], /* 253  */
&values[565], /* 254  */
&values[568], /* 255  */
}};
