/* This file was autogenerated from the Unicode mapping 
 * table PRINTIT.uni in the format used by the Linux kbd package */

/*  MML Systems PrintIt <--> Unicode mapping table  */
/*  This uses psftools extensions (U* codes) and so probably won't be  */
/*  acceptable to the utilities in kbd(1) */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0x0020, 0xffff, 0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 
0xffff, 0x0024, 0xffff, 0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 
0xffff, 0x0028, 0xffff, 0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 
0xffff, 0x002c, 0xffff, 0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 
0xffff, 0x0030, 0xffff, 0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 
0xffff, 0x0034, 0xffff, 0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 
0xffff, 0x0038, 0xffff, 0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 
0xffff, 0x003c, 0xffff, 0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 
0xffff, 0x0040, 0xffff, 0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 
0xffff, 0x0044, 0xffff, 0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 
0xffff, 0x0048, 0xffff, 0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 
0xffff, 0x004c, 0xffff, 0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 
0xffff, 0x0050, 0xffff, 0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 
0xffff, 0x0054, 0xffff, 0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 
0xffff, 0x0058, 0xffff, 0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 
0xffff, 0x005c, 0xffff, 0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 
0xffff, 0x0060, 0xffff, 0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 
0xffff, 0x0064, 0xffff, 0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 
0xffff, 0x0068, 0xffff, 0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 
0xffff, 0x006c, 0xffff, 0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 
0xffff, 0x0070, 0xffff, 0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 
0xffff, 0x0074, 0xffff, 0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 
0xffff, 0x0078, 0xffff, 0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 
0xffff, 0x007c, 0xffff, 0x007d, 0xffff, 0x007e, 0xffff, 0x25b3, 
0x1ffff, 0x2302, 0xffff, 0x253c, 0xffff, 0x2534, 0xffff, 0x252c, 
0xffff, 0x2524, 0xffff, 0x251c, 0xffff, 0x2500, 0xffff, 0x2502, 
0xffff, 0x250c, 0x1ffff, 0x256d, 0xffff, 0x2510, 0x1ffff, 0x256e, 
0xffff, 0x2514, 0x1ffff, 0x2570, 0xffff, 0x2518, 0x1ffff, 0x256f, 
0xffff, 0x2592, 0xffff, 0x2588, 0xffff, 0x2584, 0xffff, 0x258c, 
0xffff, 0x25cf, 0x1ffff, 0x2022, 0xffff, 0x25cb, 0xffff, 0x2663, 
0xffff, 0x2665, 0xffff, 0x2666, 0xffff, 0x2660, 0xffff, 0x266a, 
0xffff, 0x1f57b, 0x1ffff, 0x1f4de, 0xffff, 0x2708, 0xffff, 0x1f377, 
0xffff, 0x1fbc5, 0xffff, 0x2191, 0xffff, 0x2193, 0xffff, 0x00d7, 
0xffff, 0x00f7, 0xffff, 0x00b1, 0xffff, 0x00c5, 0xffff, 0x00c4, 
0xffff, 0x00e5, 0xffff, 0x0227, 0xffff, 0x00e4, 0xffff, 0x00e1, 
0xffff, 0x00e0, 0xffff, 0x00e2, 0xffff, 0x00aa, 0xffff, 0x00c9, 
0xffff, 0x00eb, 0xffff, 0x00e9, 0xffff, 0x00e8, 0xffff, 0x00ea, 
0xffff, 0x00ef, 0xffff, 0x00ed, 0xffff, 0x00ec, 0xffff, 0x00ee, 
0xffff, 0x00d6, 0xffff, 0x00f6, 0xffff, 0x00f3, 0xffff, 0x00f2, 
0xffff, 0x00f4, 0xffff, 0x00ba, 0xffff, 0x00dc, 0xffff, 0x00fc, 
0xffff, 0x00fa, 0xffff, 0x00f9, 0xffff, 0x00fb, 0xffff, 0x00d1, 
0xffff, 0x00f1, 0xffff, 0x00a1, 0xffff, 0x00bf, 0xffff, 0x00ff, 
0xffff, 0x00df, 0xffff, 0x03a6, 0xffff, 0x03d5, 0x1ffff, 0x03d6, 
0xffff, 0x00a4, 0xffff, 0x00c6, 0xffff, 0x00e6, 0xffff, 0x1e84, 
0xffff, 0x1e85, 0xffff, 0x20a7, 0xffff, 0x00a7, 0xffff, 0x00c7, 
0xffff, 0x00e7, 0xffff, 0x00bd, 0xffff, 0x00bc, 0xffff, 0x0192, 
0xffff, 0x00b0, 0xffff, 0x26ac, 0xffff, 0x00a8, 0x1ffff, 0x0308, 
0xffff, 0x00a5, 0xffff, 0x00a2, 0xffff, 0x1fbc8, 0xffff, };

struct psf_mapping256 m_PRINTIT = { "PRINTIT",
219, {
&values[0], /* 0  */
&values[0], /* 1  */
&values[0], /* 2  */
&values[0], /* 3  */
&values[0], /* 4  */
&values[0], /* 5  */
&values[0], /* 6  */
&values[0], /* 7  */
&values[0], /* 8  */
&values[0], /* 9  */
&values[0], /* 10  */
&values[0], /* 11  */
&values[0], /* 12  */
&values[0], /* 13  */
&values[0], /* 14  */
&values[0], /* 15  */
&values[0], /* 16  */
&values[0], /* 17  */
&values[0], /* 18  */
&values[0], /* 19  */
&values[0], /* 20  */
&values[0], /* 21  */
&values[0], /* 22  */
&values[0], /* 23  */
&values[0], /* 24  */
&values[0], /* 25  */
&values[0], /* 26  */
&values[0], /* 27  */
&values[0], /* 28  */
&values[0], /* 29  */
&values[0], /* 30  */
&values[0], /* 31  */
&values[1], /* 32  */
&values[3], /* 33  */
&values[5], /* 34  */
&values[7], /* 35  */
&values[9], /* 36  */
&values[11], /* 37  */
&values[13], /* 38  */
&values[15], /* 39  */
&values[17], /* 40  */
&values[19], /* 41  */
&values[21], /* 42  */
&values[23], /* 43  */
&values[25], /* 44  */
&values[27], /* 45  */
&values[29], /* 46  */
&values[31], /* 47  */
&values[33], /* 48  */
&values[35], /* 49  */
&values[37], /* 50  */
&values[39], /* 51  */
&values[41], /* 52  */
&values[43], /* 53  */
&values[45], /* 54  */
&values[47], /* 55  */
&values[49], /* 56  */
&values[51], /* 57  */
&values[53], /* 58  */
&values[55], /* 59  */
&values[57], /* 60  */
&values[59], /* 61  */
&values[61], /* 62  */
&values[63], /* 63  */
&values[65], /* 64  */
&values[67], /* 65  */
&values[69], /* 66  */
&values[71], /* 67  */
&values[73], /* 68  */
&values[75], /* 69  */
&values[77], /* 70  */
&values[79], /* 71  */
&values[81], /* 72  */
&values[83], /* 73  */
&values[85], /* 74  */
&values[87], /* 75  */
&values[89], /* 76  */
&values[91], /* 77  */
&values[93], /* 78  */
&values[95], /* 79  */
&values[97], /* 80  */
&values[99], /* 81  */
&values[101], /* 82  */
&values[103], /* 83  */
&values[105], /* 84  */
&values[107], /* 85  */
&values[109], /* 86  */
&values[111], /* 87  */
&values[113], /* 88  */
&values[115], /* 89  */
&values[117], /* 90  */
&values[119], /* 91  */
&values[121], /* 92  */
&values[123], /* 93  */
&values[125], /* 94  */
&values[127], /* 95  */
&values[129], /* 96  */
&values[131], /* 97  */
&values[133], /* 98  */
&values[135], /* 99  */
&values[137], /* 100  */
&values[139], /* 101  */
&values[141], /* 102  */
&values[143], /* 103  */
&values[145], /* 104  */
&values[147], /* 105  */
&values[149], /* 106  */
&values[151], /* 107  */
&values[153], /* 108  */
&values[155], /* 109  */
&values[157], /* 110  */
&values[159], /* 111  */
&values[161], /* 112  */
&values[163], /* 113  */
&values[165], /* 114  */
&values[167], /* 115  */
&values[169], /* 116  */
&values[171], /* 117  */
&values[173], /* 118  */
&values[175], /* 119  */
&values[177], /* 120  */
&values[179], /* 121  */
&values[181], /* 122  */
&values[183], /* 123  */
&values[185], /* 124  */
&values[187], /* 125  */
&values[189], /* 126  */
&values[191], /* 127  White upward-pointing triangle */
&values[195], /* 128  Crossroads */
&values[197], /* 129  Bottom junction */
&values[199], /* 130  Top junction */
&values[201], /* 131  Right junction */
&values[203], /* 132  Left junction */
&values[205], /* 133  Horizontal */
&values[207], /* 134  Vertical line */
&values[209], /* 135  Top left corner */
&values[213], /* 136  Top right corner */
&values[217], /* 137  Bottom left corner */
&values[221], /* 138  Bottom right corner */
&values[225], /* 139  Medium shade */
&values[227], /* 140  Full block */
&values[229], /* 141  Lower half block */
&values[231], /* 142  Left half block */
&values[233], /* 143  Solid bullet */
&values[237], /* 144  Hollow bullet */
&values[239], /* 145  Clubs */
&values[241], /* 146  Hearts */
&values[243], /* 147  Diamonds */
&values[245], /* 148  Spades */
&values[247], /* 149  Single quaver */
&values[249], /* 150  Telephone receiver */
&values[253], /* 151  Airplane */
&values[0], /* 152  */
&values[255], /* 153  Wineglass */
&values[257], /* 154  Stick figure */
&values[259], /* 155  Up arrow */
&values[261], /* 156  Down arrow */
&values[263], /* 157  Multiplication sign */
&values[265], /* 158  Division sign */
&values[267], /* 159  Plus or minus */
&values[269], /* 160  A with ring */
&values[271], /* 161  A with diaeresis */
&values[273], /* 162  a with ring */
&values[275], /* 163  a with dot */
&values[277], /* 164  a with diaeresis */
&values[279], /* 165  a acute */
&values[281], /* 166  a grave */
&values[283], /* 167  a circumflex */
&values[285], /* 168  Feminine ordinal */
&values[287], /* 169  E acute */
&values[289], /* 170  e diaeresis */
&values[291], /* 171  e acute */
&values[0], /* 172  */
&values[293], /* 173  e grave */
&values[295], /* 174  e circumflex */
&values[297], /* 175  i diaeresis */
&values[299], /* 176  i acute */
&values[301], /* 177  i grave */
&values[303], /* 178  i circumflex */
&values[305], /* 179  O diaeresis */
&values[307], /* 180  o diaeresis */
&values[309], /* 181  o acute */
&values[311], /* 182  o grave */
&values[313], /* 183  o circumflex */
&values[315], /* 184  Masculine ordinal */
&values[317], /* 185  U diaeresis */
&values[319], /* 186  u diaeresis */
&values[321], /* 187  u acute */
&values[323], /* 188  u grave */
&values[0], /* 189  */
&values[325], /* 190  u circumflex */
&values[327], /* 191  N tilde */
&values[329], /* 192  n tilde */
&values[0], /* 193  */
&values[331], /* 194  Upside down ! */
&values[333], /* 195  Upside down ? */
&values[335], /* 196  y diaeresis */
&values[337], /* 197  Sharp S */
&values[339], /* 198  Capital Phi */
&values[341], /* 199  Little phi */
&values[345], /* 200  Currency symbol */
&values[347], /* 201  AE */
&values[349], /* 202  ae */
&values[0], /* 203  */
&values[351], /* 204  W diaeresis */
&values[353], /* 205  w diaeresis */
&values[355], /* 206  Peseta */
&values[357], /* 207  Section */
&values[359], /* 208  C cedilla */
&values[361], /* 209  c cedilla */
&values[363], /* 210  Half */
&values[365], /* 211  Quarter */
&values[367], /* 212  Florin */
&values[369], /* 213  Degree symbol */
&values[371], /* 214  Small white circle */
&values[373], /* 215  Diaeresis */
&values[377], /* 216  Yen sign */
&values[379], /* 217  Cent sign */
&values[381], /* 218  Stick figure leaning right */
&values[0], /* 219  */
&values[0], /* 220  */
&values[0], /* 221  */
&values[0], /* 222  */
&values[0], /* 223  */
&values[0], /* 224  */
&values[0], /* 225  */
&values[0], /* 226  */
&values[0], /* 227  */
&values[0], /* 228  */
&values[0], /* 229  */
&values[0], /* 230  */
&values[0], /* 231  */
&values[0], /* 232  */
&values[0], /* 233  */
&values[0], /* 234  */
&values[0], /* 235  */
&values[0], /* 236  */
&values[0], /* 237  */
&values[0], /* 238  */
&values[0], /* 239  */
&values[0], /* 240  */
&values[0], /* 241  */
&values[0], /* 242  */
&values[0], /* 243  */
&values[0], /* 244  */
&values[0], /* 245  */
&values[0], /* 246  */
&values[0], /* 247  */
&values[0], /* 248  */
&values[0], /* 249  */
&values[0], /* 250  */
&values[0], /* 251  */
&values[0], /* 252  */
&values[0], /* 253  */
&values[0], /* 254  */
&values[0], /* 255  */
}};
