/* This file was autogenerated from the Unicode mapping 
 * table QX10.uni in the format used by the Linux kbd package */

/*  Epson QX10 <--> Unicode mapping table  */
/*  This uses psftools extensions (U* codes) and so probably won't be  */
/*  acceptable to the utilities in kbd(1) */
#include <stdio.h>
#include "psflib.h"

static psf_dword values[] = {
0xffff, 0x0000, 0xffff, 0x263a, 0xffff, 0x263b, 0xffff, 0x2022, 
0xffff, 0x25d8, 0xffff, 0x25ce, 0x29be, 0xffff, 0x25d9, 0xffff, 
0x2642, 0xffff, 0x2640, 0xffff, 0x266b, 0xffff, 0x263c, 0xffff, 
0x25c4, 0xffff, 0x25ba, 0xffff, 0x2195, 0xffff, 0x203c, 0xffff, 
0x00b6, 0xffff, 0x221e, 0xffff, 0x220e, 0xffff, 0x2229, 0xffff, 
0x2261, 0xffff, 0x2265, 0xffff, 0x2264, 0xffff, 0x25ac, 0xffff, 
0x21b2, 0xffff, 0x2192, 0xffff, 0x2190, 0xffff, 0x221f, 0xffff, 
0x2194, 0xffff, 0x25b2, 0xffff, 0x25bc, 0xffff, 0x0020, 0xffff, 
0x0021, 0xffff, 0x0022, 0xffff, 0x0023, 0xffff, 0x0024, 0xffff, 
0x0025, 0xffff, 0x0026, 0xffff, 0x0027, 0xffff, 0x0028, 0xffff, 
0x0029, 0xffff, 0x002a, 0xffff, 0x002b, 0xffff, 0x002c, 0xffff, 
0x002d, 0xffff, 0x002e, 0xffff, 0x002f, 0xffff, 0x0030, 0xffff, 
0x0031, 0xffff, 0x0032, 0xffff, 0x0033, 0xffff, 0x0034, 0xffff, 
0x0035, 0xffff, 0x0036, 0xffff, 0x0037, 0xffff, 0x0038, 0xffff, 
0x0039, 0xffff, 0x003a, 0xffff, 0x003b, 0xffff, 0x003c, 0xffff, 
0x003d, 0xffff, 0x003e, 0xffff, 0x003f, 0xffff, 0x0040, 0xffff, 
0x0041, 0xffff, 0x0042, 0xffff, 0x0043, 0xffff, 0x0044, 0xffff, 
0x0045, 0xffff, 0x0046, 0xffff, 0x0047, 0xffff, 0x0048, 0xffff, 
0x0049, 0xffff, 0x004a, 0xffff, 0x004b, 0xffff, 0x004c, 0xffff, 
0x004d, 0xffff, 0x004e, 0xffff, 0x004f, 0xffff, 0x0050, 0xffff, 
0x0051, 0xffff, 0x0052, 0xffff, 0x0053, 0xffff, 0x0054, 0xffff, 
0x0055, 0xffff, 0x0056, 0xffff, 0x0057, 0xffff, 0x0058, 0xffff, 
0x0059, 0xffff, 0x005a, 0xffff, 0x005b, 0xffff, 0x005c, 0xffff, 
0x005d, 0xffff, 0x005e, 0xffff, 0x005f, 0xffff, 0x0060, 0xffff, 
0x0061, 0xffff, 0x0062, 0xffff, 0x0063, 0xffff, 0x0064, 0xffff, 
0x0065, 0xffff, 0x0066, 0xffff, 0x0067, 0xffff, 0x0068, 0xffff, 
0x0069, 0xffff, 0x006a, 0xffff, 0x006b, 0xffff, 0x006c, 0xffff, 
0x006d, 0xffff, 0x006e, 0xffff, 0x006f, 0xffff, 0x0070, 0xffff, 
0x0071, 0xffff, 0x0072, 0xffff, 0x0073, 0xffff, 0x0074, 0xffff, 
0x0075, 0xffff, 0x0076, 0xffff, 0x0077, 0xffff, 0x0078, 0xffff, 
0x0079, 0xffff, 0x007a, 0xffff, 0x007b, 0xffff, 0x007c, 0xffff, 
0x007d, 0xffff, 0x007e, 0xffff, 0x25b3, 0x1ffff, 0x2302, 0xffff, 
0x253c, 0xffff, 0x2534, 0xffff, 0x252c, 0xffff, 0x2524, 0xffff, 
0x251c, 0xffff, 0x2500, 0xffff, 0x2502, 0xffff, 0x250c, 0x1ffff, 
0x256d, 0xffff, 0x2510, 0x1ffff, 0x256e, 0xffff, 0x2514, 0x1ffff, 
0x2570, 0xffff, 0x2518, 0x1ffff, 0x256f, 0xffff, 0x2592, 0xffff, 
0x2588, 0xffff, 0x2584, 0xffff, 0x258c, 0xffff, 0x25cf, 0x1ffff, 
0x2022, 0xffff, 0x25cb, 0xffff, 0x2663, 0xffff, 0x2665, 0xffff, 
0x2666, 0xffff, 0x2660, 0xffff, 0x266a, 0xffff, 0x1f57b, 0x1ffff, 
0x1f4de, 0xffff, 0x2708, 0xffff, 0x1f377, 0xffff, 0x1fbc5, 0xffff, 
0x2191, 0xffff, 0x2193, 0xffff, 0x00d7, 0xffff, 0x00f7, 0xffff, 
0x00b1, 0xffff, 0x00c5, 0xffff, 0x00c4, 0xffff, 0x00e5, 0xffff, 
0x0227, 0xffff, 0x00e4, 0xffff, 0x00e1, 0xffff, 0x00e0, 0xffff, 
0x00e2, 0xffff, 0x00aa, 0xffff, 0x00c9, 0xffff, 0x00eb, 0xffff, 
0x00e9, 0xffff, 0x00e8, 0xffff, 0x00ea, 0xffff, 0x00ef, 0xffff, 
0x00ed, 0xffff, 0x00ec, 0xffff, 0x00ee, 0xffff, 0x00d6, 0xffff, 
0x00f6, 0xffff, 0x00f3, 0xffff, 0x00f2, 0xffff, 0x00f4, 0xffff, 
0x00ba, 0xffff, 0x00dc, 0xffff, 0x00fc, 0xffff, 0x00fa, 0xffff, 
0x00f9, 0xffff, 0x00fb, 0xffff, 0x00d1, 0xffff, 0x00f1, 0xffff, 
0x00a1, 0xffff, 0x00bf, 0xffff, 0x00ff, 0xffff, 0x00df, 0xffff, 
0x03a6, 0xffff, 0x03d5, 0x1ffff, 0x03d6, 0xffff, 0x00a4, 0xffff, 
0x00c6, 0xffff, 0x00e6, 0xffff, 0x1e84, 0xffff, 0x1e85, 0xffff, 
0x20a7, 0xffff, 0x00a7, 0xffff, 0x00c7, 0xffff, 0x00e7, 0xffff, 
0x00bd, 0xffff, 0x00bc, 0xffff, 0x0192, 0xffff, 0x00b0, 0xffff, 
0x26ac, 0xffff, 0x00a8, 0x1ffff, 0x0308, 0xffff, 0x00a5, 0xffff, 
0x00a2, 0xffff, 0x00a3, 0xffff, 0x20a4, 0xffff, 0x2310, 0xffff, 
0x00ac, 0xffff, 0x00ab, 0xffff, 0x00bb, 0xffff, 0x256c, 0xffff, 
0x2569, 0xffff, 0x2566, 0xffff, 0x2563, 0xffff, 0x2560, 0xffff, 
0x2550, 0xffff, 0x2551, 0xffff, 0x2554, 0xffff, 0x2557, 0xffff, 
0x255a, 0xffff, 0x255d, 0xffff, 0x2590, 0xffff, 0x2580, 0xffff, 
0x03b1, 0xffff, 0x03b3, 0xffff, 0x03c0, 0xffff, 0x03a3, 0xffff, 
0x03c3, 0xffff, 0x03bc, 0xffff, 0x03c4, 0xffff, 0x03b8, 0xffff, 
0x03a9, 0xffff, 0x03b4, 0xffff, 0x2320, 0xffff, 0x2321, 0xffff, 
0x2248, 0xffff, 0x02d9, 0xffff, 0x221a, 0xffff, 0x207f, 0xffff, 
0x00b2, 0xffff, 0x25a0, 0xffff, 0x1d125, 0xffff, };

struct psf_mapping256 m_QX10 = { "QX10",
256, {
&values[1], /* 0  */
&values[3], /* 1  White smiling face */
&values[5], /* 2  Black smiling face */
&values[7], /* 3  Bullet */
&values[9], /* 4  Inverse bullet */
&values[11], /* 5  Bullseye / circled white bullet */
&values[14], /* 6  Inverse white circle */
&values[16], /* 7  Male symbol */
&values[18], /* 8  Female symbol */
&values[20], /* 9  Double quaver */
&values[22], /* 10  White sun with rays */
&values[24], /* 11  Triangle pointing left */
&values[26], /* 12  Triangle pointing right */
&values[28], /* 13  Arrow up and down */
&values[30], /* 14  Double pling */
&values[32], /* 15  Pilcrow */
&values[34], /* 16  Infinity */
&values[36], /* 17  Element of */
&values[38], /* 18  Intersection */
&values[40], /* 19  Identical to */
&values[42], /* 20  Greater than or equal to */
&values[44], /* 21  Less than or equal to */
&values[46], /* 22  Black rectangle */
&values[48], /* 23  Downwards arrow with tip leftwards */
&values[0], /* 24  */
&values[0], /* 25  */
&values[50], /* 26  Arrow pointing right */
&values[52], /* 27  Arrow pointing left */
&values[54], /* 28  Right angle */
&values[56], /* 29  Arrow pointing left and right */
&values[58], /* 30  Triangle pointing up */
&values[60], /* 31  Triangle pointing down */
&values[62], /* 32  */
&values[64], /* 33  */
&values[66], /* 34  */
&values[68], /* 35  */
&values[70], /* 36  */
&values[72], /* 37  */
&values[74], /* 38  */
&values[76], /* 39  */
&values[78], /* 40  */
&values[80], /* 41  */
&values[82], /* 42  */
&values[84], /* 43  */
&values[86], /* 44  */
&values[88], /* 45  */
&values[90], /* 46  */
&values[92], /* 47  */
&values[94], /* 48  */
&values[96], /* 49  */
&values[98], /* 50  */
&values[100], /* 51  */
&values[102], /* 52  */
&values[104], /* 53  */
&values[106], /* 54  */
&values[108], /* 55  */
&values[110], /* 56  */
&values[112], /* 57  */
&values[114], /* 58  */
&values[116], /* 59  */
&values[118], /* 60  */
&values[120], /* 61  */
&values[122], /* 62  */
&values[124], /* 63  */
&values[126], /* 64  */
&values[128], /* 65  */
&values[130], /* 66  */
&values[132], /* 67  */
&values[134], /* 68  */
&values[136], /* 69  */
&values[138], /* 70  */
&values[140], /* 71  */
&values[142], /* 72  */
&values[144], /* 73  */
&values[146], /* 74  */
&values[148], /* 75  */
&values[150], /* 76  */
&values[152], /* 77  */
&values[154], /* 78  */
&values[156], /* 79  */
&values[158], /* 80  */
&values[160], /* 81  */
&values[162], /* 82  */
&values[164], /* 83  */
&values[166], /* 84  */
&values[168], /* 85  */
&values[170], /* 86  */
&values[172], /* 87  */
&values[174], /* 88  */
&values[176], /* 89  */
&values[178], /* 90  */
&values[180], /* 91  */
&values[182], /* 92  */
&values[184], /* 93  */
&values[186], /* 94  */
&values[188], /* 95  */
&values[190], /* 96  */
&values[192], /* 97  */
&values[194], /* 98  */
&values[196], /* 99  */
&values[198], /* 100  */
&values[200], /* 101  */
&values[202], /* 102  */
&values[204], /* 103  */
&values[206], /* 104  */
&values[208], /* 105  */
&values[210], /* 106  */
&values[212], /* 107  */
&values[214], /* 108  */
&values[216], /* 109  */
&values[218], /* 110  */
&values[220], /* 111  */
&values[222], /* 112  */
&values[224], /* 113  */
&values[226], /* 114  */
&values[228], /* 115  */
&values[230], /* 116  */
&values[232], /* 117  */
&values[234], /* 118  */
&values[236], /* 119  */
&values[238], /* 120  */
&values[240], /* 121  */
&values[242], /* 122  */
&values[244], /* 123  */
&values[246], /* 124  */
&values[248], /* 125  */
&values[250], /* 126  */
&values[252], /* 127  White upward-pointing triangle */
&values[256], /* 128  Crossroads */
&values[258], /* 129  Bottom junction */
&values[260], /* 130  Top junction */
&values[262], /* 131  Right junction */
&values[264], /* 132  Left junction */
&values[266], /* 133  Horizontal */
&values[268], /* 134  Vertical line */
&values[270], /* 135  Top left corner */
&values[274], /* 136  Top right corner */
&values[278], /* 137  Bottom left corner */
&values[282], /* 138  Bottom right corner */
&values[286], /* 139  Medium shade */
&values[288], /* 140  Full block */
&values[290], /* 141  Lower half block */
&values[292], /* 142  Left half block */
&values[294], /* 143  Solid bullet */
&values[298], /* 144  Hollow bullet */
&values[300], /* 145  Clubs */
&values[302], /* 146  Hearts */
&values[304], /* 147  Diamonds */
&values[306], /* 148  Spades */
&values[308], /* 149  Single quaver */
&values[310], /* 150  Telephone receiver */
&values[314], /* 151  Airplane */
&values[0], /* 152  */
&values[316], /* 153  Wineglass */
&values[318], /* 154  Stick figure */
&values[320], /* 155  Up arrow */
&values[322], /* 156  Down arrow */
&values[324], /* 157  Multiplication sign */
&values[326], /* 158  Division sign */
&values[328], /* 159  Plus or minus */
&values[330], /* 160  A with ring */
&values[332], /* 161  A with diaeresis */
&values[334], /* 162  a with ring */
&values[336], /* 163  a with dot */
&values[338], /* 164  a with diaeresis */
&values[340], /* 165  a acute */
&values[342], /* 166  a grave */
&values[344], /* 167  a circumflex */
&values[346], /* 168  Feminine ordinal */
&values[348], /* 169  E acute */
&values[350], /* 170  e diaeresis */
&values[352], /* 171  e acute */
&values[0], /* 172  */
&values[354], /* 173  e grave */
&values[356], /* 174  e circumflex */
&values[358], /* 175  i diaeresis */
&values[360], /* 176  i acute */
&values[362], /* 177  i grave */
&values[364], /* 178  i circumflex */
&values[366], /* 179  O diaeresis */
&values[368], /* 180  o diaeresis */
&values[370], /* 181  o acute */
&values[372], /* 182  o grave */
&values[374], /* 183  o circumflex */
&values[376], /* 184  Masculine ordinal */
&values[378], /* 185  U diaeresis */
&values[380], /* 186  u diaeresis */
&values[382], /* 187  u acute */
&values[384], /* 188  u grave */
&values[0], /* 189  */
&values[386], /* 190  u circumflex */
&values[388], /* 191  N tilde */
&values[390], /* 192  n tilde */
&values[0], /* 193  */
&values[392], /* 194  Upside down ! */
&values[394], /* 195  Upside down ? */
&values[396], /* 196  y diaeresis */
&values[398], /* 197  Sharp S */
&values[400], /* 198  Capital Phi */
&values[402], /* 199  Little phi */
&values[406], /* 200  Currency symbol */
&values[408], /* 201  AE */
&values[410], /* 202  ae */
&values[0], /* 203  */
&values[412], /* 204  W diaeresis */
&values[414], /* 205  w diaeresis */
&values[416], /* 206  Peseta */
&values[418], /* 207  Section */
&values[420], /* 208  C cedilla */
&values[422], /* 209  c cedilla */
&values[424], /* 210  Half */
&values[426], /* 211  Quarter */
&values[428], /* 212  Florin */
&values[430], /* 213  Degree symbol */
&values[432], /* 214  Small white circle */
&values[434], /* 215  Diaeresis */
&values[438], /* 216  Yen sign */
&values[440], /* 217  Cent sign */
&values[442], /* 218  Pound sign */
&values[444], /* 219  Lira sign */
&values[446], /* 220  Reversed not sign */
&values[448], /* 221  Not sign */
&values[450], /* 222  Open double-angle quotation mark */
&values[452], /* 223  Close double-angle quotation mark */
&values[454], /* 224  Crossroads */
&values[456], /* 225  Bottom junction */
&values[458], /* 226  Top junction */
&values[460], /* 227  Right junction */
&values[462], /* 228  Left junction */
&values[464], /* 229  Horizontal */
&values[466], /* 230  Vertical line */
&values[468], /* 231  Top left corner */
&values[470], /* 232  Top right corner */
&values[472], /* 233  Bottom left corner */
&values[474], /* 234  Bottom right corner */
&values[476], /* 235  Right half block */
&values[478], /* 236  Top half block */
&values[480], /* 237  Alpha */
&values[482], /* 238  Gamma */
&values[484], /* 239  Pi */
&values[486], /* 240  Sigma */
&values[488], /* 241  Lower case sigma */
&values[490], /* 242  Mu */
&values[492], /* 243  Tau */
&values[494], /* 244  Theta */
&values[496], /* 245  Omega */
&values[498], /* 246  Delta */
&values[500], /* 247  Top half of integral */
&values[502], /* 248  Bottom half of integral */
&values[504], /* 249  Approximately equal */
&values[506], /* 250  Dot above */
&values[508], /* 251  Square root */
&values[510], /* 252  Superscript N */
&values[512], /* 253  Superscript 2 */
&values[514], /* 254  Black squre */
&values[516], /* 255  Drum clef */
}};
